#pragma once

#define GAME_FNAMES(x) \
	x(Invalid) \
	x(Actor) \
	x(APawn) \
	x(ACharacter) \
	x(AEQSTestingPawn) \
	x(APlayerCharacter) \
	x(ADefaultPawn) \
	x(ASpectatorPawn) \
	x(APathfinderVehicle) \
	x(APlayerCameraDrone) \
	x(AFSDPawn) \
	x(ACaretaker) \
	x(AEscortMule) \
	x(ATowerModuleBase) \
	x(AAimingTowerModule) \
	x(AGuntowerModule) \
	x(AHostileGuntowerModule) \
	x(AHostileTargetingGuntowerModule) \
	x(ALMGGuntoweModule) \
	x(AHomingFireModule) \
	x(ARandomFiringGuntowerModule) \
	x(ARadialFireModule) \
	x(AGuntowerWeakPoint) \
	x(ATowerEventModule) \
	x(AAimingTowerEventModule) \
	x(AEnemyPawn) \
	x(AStabberVineRoot) \
	x(AParasiteEnemy) \
	x(AInsectSwarmSpawner) \
	x(AHydraWeedHealer) \
	x(AShootingPlant) \
	x(AHydraWeedShooter) \
	x(AHydraWeedCore) \
	x(AFacilityTurret) \
	x(ASpinningFacilityturret) \
	x(AAimingFacilityTurret) \
	x(ATentacleBase) \
	x(AFacilityTentacle) \
	x(AStabberVine) \
	x(ATerminatorTentacle) \
	x(ACaveLeech) \
	x(AEnemyDeepPathfinderCharacter) \
	x(AAFlyingBug) \
	x(ABomber) \
	x(AFlyingLifter) \
	x(AJellyBreeder) \
	x(AConvertedRobot) \
	x(AFlyingEnemyDeepPathfinderCharacter) \
	x(AFriendlyParasite) \
	x(AHalloweenSkull) \
	x(AInsectSwarmEnemy) \
	x(APatrolBot) \
	x(APlagueWorm) \
	x(AProspectorRobot) \
	x(ASharkEnemy) \
	x(AShredder) \
	x(ASpiderEnemy) \
	x(ATerminatorEnemy) \
	x(AWoodLouse) \
	x(ABosco) \
	x(ABP_Bosco_C) \
	x(ACaveWorm) \
	x(AMaggot) \
	x(ADroneBase) \
	x(ADroneCharacter) \
	x(AMULE) \
	x(AMolly) \
	x(ABP_Donkey_C) \
	x(AMiniMule) \
	x(ARecallableActor) \
	x(ARecallableSentryGun) \
    x(ITM_DeepDiveStatus_Stage_C) \
    x(ITM_MisDesMutator_C) \
    x(ITM_SeasonMenu_BG_C) \
    x(ITM_RestoreSaveCategoryList_Entry_C) \
    x(ITM_UpgGear_TierRow_C) \
    x(ITM_CommunityGoalProgress_C) \
    x(ITM_BarGlass_Item_PotOGold_C) \
    x(ITM_Overclocks_Equip_Item_C) \
    x(ITM_Loadout_ItemWindow_C) \
    x(ITM_MisSel_MissionIconBasic_Locked_C) \
    x(ITM_ItemCategories_C) \
    x(ITM_SeasonContentToggle_C) \
    x(ITM_Craft_ItemIcon_C) \
    x(ITM_LoadoutSelectorBar_C) \
    x(ITM_Overclock_Details_C) \
    x(ITM_FactionToolTip_C) \
    x(ITM_LoadoutSelectButton_C) \
    x(ITM_CommunityGoalRewardToolTip_C) \
    x(ITM_BarGlass_Item_WormholeSpecial_C) \
    x(ITM_BarGlass_Item_BlackOutStout_C) \
    x(ITM_PerkInfoBox_C) \
    x(ITM_PendingMod_C) \
    x(ITM_MissionComplete_MissionState_Failure_C) \
    x(ITM_BarGlass_Item_MaltRockBearer_C) \
    x(ITM_Wardrobe_ItemSelector_C) \
    x(ITM_Flare_Large_C) \
    x(ITM_LoadOut_PerksEquip_Item_C) \
    x(ITM_ServerList_AttentionBox_C) \
    x(ITM_Job_Section_Header_C) \
    x(ITM_Trading_ResourcePoster_C) \
    x(ITM_BarGlass_Item_DarkMokite_C) \
    x(ITM_Season_LevelInfinity_C) \
    x(ITM_WeeklyMissionOverlay_C) \
    x(ITM_MissionComplete_DeepDiveHeader_C) \
    x(ITM_Wardrobe_ItemSlot_Base_C) \
    x(ITM_DeepDive_MisCompBG_C) \
    x(ITM_MisSel_RegionImage_C) \
    x(ITM_WeaponInfo_C) \
    x(ITM_TopBar_CharacterLevel_C) \
    x(ITM_BarGlass_Item_GlyphidSlammer_Support_C) \
    x(ITM_SeasonEditor_Level_C) \
    x(ITM_CampaignItem_Member_C) \
    x(ITM_Biome_ResourceIcon_C) \
    x(ITM_DeepDives_ServerFilters_C) \
    x(ITM_BarGlass_Item_DUMMY_C) \
    x(ITM_SaveSlot_Entry_C) \
    x(ITM_TopBar_PlayerCounter_C) \
    x(ITM_Craft_ResourceBig_C) \
    x(ITM_SeasonEventBonus_C) \
    x(ITM_Refinery_Pipeline_C) \
    x(ITM_CharacterIcon_C) \
    x(ITM_LoadoutIconSelector_C) \
    x(ITM_Season_Level_C) \
    x(ITM_ServerEntry_TeamLine_C) \
    x(ITM_CurrentSaveSlot_RankOrLevelReadout_C) \
    x(ITM_BarGlass_Item_ArkenStout_C) \
    x(ITM_MissionBar_Objective_C) \
    x(ITM_DeepDives_ServerList_Entry_C) \
    x(ITM_PropHunt_HunterItem_C) \
    x(ITM_Season_NextReward_C) \
    x(ITM_AnyRetiredRequirement_C) \
    x(ITM_MissionComplete_MissionState_Success_C) \
    x(ITM_CommunityGoalRecruitment_C) \
    x(ITM_CommunityGoalResult_ConsoleScreenV1_C) \
    x(ITM_MutatorIcon_C) \
    x(ITM_SeasonProgressBar_C) \
    x(ITM_Mod_Joining_C) \
    x(ITM_MutatorsAndWarnings_Entry1_C) \
    x(ITM_LoadOut_PerksEquip_Slot_C) \
    x(ITM_Wardrobe_ItemSlot_ArmorVanity_C) \
    x(ITM_MissionInfo_C) \
    x(ITM_SocialMediaButtons_C) \
    x(ITM_Special_ButtonCutCorner_C) \
    x(ITM_BaseUpgradeIcon_C) \
    x(ITM_AOE_Grenade_Base_C) \
    x(ITM_Craft_ResourceSmall_C) \
    x(ITM_Season_CharacterIcon_C) \
    x(ITM_SegmentedHealthBar_C) \
    x(ITM_CreateNewSaveSlot_Entry_C) \
    x(ITM_Craft_Resource_C) \
    x(ITM_CreditsEntry_C) \
    x(ITM_MissionComplete_ResourceBox_C) \
    x(ITM_SeasonEditor_EmptySpot_C) \
    x(ITM_MisSel_Biome_C) \
    x(ITM_SeasonPlagueCleanBonus_C) \
    x(ITM_Craft_ItemBox_C) \
    x(ITM_DeepDiveHeader_C) \
    x(ITM_HealthBar_C) \
    x(ITM_FactionLogo_C) \
    x(ITM_BarGlass_Item_SmartStout_C) \
    x(ITM_CommunityGoal_TotalProgress_C) \
    x(ITM_Community_Console_ClaimReward_C) \
    x(ITM_Gear_Bar_C) \
    x(ITM_PrivatePublic_C) \
    x(ITM_Wardrobe_ItemSlot_VictoryMoves_C) \
    x(ITM_TopBar_PlayerRank_C) \
    x(ITM_BarGlass_Item_Gutwrecker_C) \
    x(ITM_CleanupDrop_C) \
    x(ITM_BarGlass_Item_SlayerStout_C) \
    x(ITM_DeepDiveInfo_C) \
    x(ITM_DLC_Entry_C) \
    x(ITM_Loadout_PerksEquip_Selection_C) \
    x(ITM_CommunityGoalFactionSelection_C) \
    x(ITM_BarGlass_Item_RockBlaster_C) \
    x(ITM_Modding_LoadoutSelection_C) \
    x(ITM_Flare_Small_Driller_C) \
    x(ITM_MisSel_DotMarker_WorkEnvironment_C) \
    x(ITM_MissionComplete_Resource_C) \
    x(ITM_MisSel_PlanetZone_C) \
    x(ITM_Trading_Resource_C) \
    x(ITM_Mod_C) \
    x(ITM_CampaignProgress_Small_C) \
    x(ITM_HackingTool_C) \
    x(ITM_CleanupDrop_WalkingPlagueHeart_C) \
    x(ITM_Season_RewardImageSingle_C) \
    x(ITM_MissionMapIcon_LevelLock_C) \
    x(ITM_MisSel_BG_Planet_C) \
    x(ITM_DragRotateCharacter_C) \
    x(ITM_DeepDive_StageIcon_C) \
    x(ITM_Tab_Modding_C) \
    x(ITM_SonyTeamLeader_C) \
    x(ITM_TimeText_C) \
    x(ITM_TopBar_Resources_C) \
    x(ITM_LoadoutIcon_C) \
    x(ITM_CampaignCompletedRequirement_C) \
    x(ITM_SupplyBarItem_C) \
    x(ITM_BarGlass_Item_MacteraBrew_C) \
    x(ITM_CampaignProgress_NoBrackets_C) \
    x(ITM_CommunityGoal_TotalProgress_ConsoleScreenV2_C) \
    x(ITM_Overclocks_Equip_C) \
    x(ITM_SeasonEditor_Reward_C) \
    x(ITM_MissionBar_Warning_C) \
    x(ITM_Season_ChallengeTimer_C) \
    x(ITM_TreeOfVanity_Node_C) \
    x(ITM_Wardrobe_ItemSlot_Vanity_C) \
    x(ITM_TreeOfVanityEditor_NodeIcon_C) \
    x(ITM_MisSel_ObjectiveSecondary_C) \
    x(ITM_ItemIcon_C) \
    x(ITM_RestoreSaveList_Entry_C) \
    x(ITM_UpgGear_UpgIconSingle_C) \
    x(ITM_MisSel_ResourceIcon_C) \
    x(ITM_MatrixCore_C) \
    x(ITM_MisSel_Timer_C) \
    x(ITM_SupplyBar_C) \
    x(ITM_HostIcon_C) \
    x(ITM_MasteryBar_Block_C) \
    x(ITM_MenuDamageIndicator_C) \
    x(ITM_ValidSeedRequirement_C) \
    x(ITM_BarGlass_Item_PropHunt_C) \
    x(ITM_SupplyDrop_C) \
    x(ITM_Season_Challenge_C) \
    x(ITM_MisSel_DotMarker_MissionLength_C) \
    x(ITM_DeepDives_ServerList_C) \
    x(ITM_Trading_BasketItem_C) \
    x(ITM_MissionMapIcon_Objective_C) \
    x(ITM_InfoBox_C) \
    x(ITM_BarGlass_Item_LeafloversSpecial_C) \
    x(ITM_Prerequisites_C) \
    x(ITM_Grenade_Base_C) \
    x(ITM_DeepDives_LaunchButton_C) \
    x(ITM_CharacterBuffIcon_C) \
    x(ITM_Overclock_Details_Item_C) \
    x(ITM_MisSel_RegionImage1_C) \
    x(ITM_BaseFlare_C) \
    x(ITM_Pickaxe_Slot_C) \
    x(ITM_Season_LevelEndGradient_C) \
    x(ITM_Wardrobe_ItemSelector_Entry_C) \
    x(ITM_BasicTutorialWindow_C) \
    x(ITM_Jobs_WeeklyBG_C) \
    x(ITM_BarGlass_Item_GlyphidSlammer_C) \
    x(ITM_CommunityGoal_C) \
    x(ITM_MisSel_DotMarker_C) \
    x(ITM_BarGlass_Item_TunnelRat_C) \
    x(ITM_Loadout_UpgradeBar_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_GrenadeIcon_Lock_C) \
    x(ITM_TerrainScanner_C) \
    x(ITM_CurrentSaveSlot_Resources_C) \
    x(ITM_BarGlass_Item_BurningLove_C) \
    x(ITM_MissionMap_Icon_BG_C) \
    x(ITM_MisSel_MissionCount_C) \
    x(ITM_DeepDives_RejoinButton_C) \
    x(ITM_SeasonEvent_C) \
    x(ITM_CampaignItem_SmallEmpty_C) \
    x(ITM_Loadout_PerksEquip_C) \
    x(ITM_Season_Progress_Small_C) \
    x(ITM_Flare_Small_Engineer_C) \
    x(ITM_ResetFaction_ConsoleScreenV1_C) \
    x(ITM_BarGlass_Item_OilyOafBrew_C) \
    x(ITM_RetirementBadge_C) \
    x(ITM_CampaignProgress_C) \
    x(ITM_HealthBarPercentWWarning_C) \
    x(ITM_DeepDives_Start_C) \
    x(ITM_MenuBackground_C) \
    x(ITM_GeneratedIcon_Item_C) \
    x(ITM_SaveSlot_Entry_ClassIcon_C) \
    x(ITM_MissionComplete_MissionState_C) \
    x(ITM_MisSel_BiomeBase_C) \
    x(ITM_SkinItem_C) \
    x(ITM_ServerList_Warning_C) \
    x(ITM_DeepDives_Join_C) \
    x(ITM_BarGlass_Item_FlintlockesDelight_C) \
    x(ITM_ObjectiveBox_InMission_C) \
    x(ITM_BarGlass_Item_SeasonedMoonrider_C) \
    x(ITM_MisSel_DotMarker_CaveDifficulty_C) \
    x(ITM_BarGlass_Item_BlacklockLager_C) \
    x(ITM_GrenadeThrow_C) \
    x(ITM_HealthBarSection_C) \
    x(ITM_LoadOut_PerksEquip_None_C) \
    x(ITM_Pipeline_BrokenIcon_C) \
    x(ITM_SeasonEndWarningTimer_C) \
    x(ITM_Flare_Small_C) \
    x(ITM_Season_LevelUp_C) \
    x(ITM_EscortMuleHealthBar_C) \
    x(ITM_BarGlass_Item_UnderhillDeluxe_C) \
    x(ITM_MisSel_MissionMapIcon_C) \
    x(ITM_MasteryBar_Icon_C) \
    x(ITM_RestoreSave_C) \
    x(ITM_Modding_ToolTip_Entry_C) \
    x(ITM_DeepDiveHeaderElite_C) \
    x(ITM_UpgGear_SideBar_C) \
    x(ITM_ServerList_Entry_C) \
    x(ITM_PreventDuplicateCharacters_C) \
    x(ITM_SeasonLogo_C) \
    x(ITM_SocialMediaButton_C) \
    x(ITM_CharacterSwitcherBar_C) \
    x(ITM_MisSel_FullBiome_C) \
    x(ITM_SeasonChallengeIcon_C) \
    x(ITM_MisSel_MissionIconBasic_C) \
    x(ITM_CommunityGoalRecruitment_ConsoleScreenV1_C) \
    x(ITM_Flare_Large_Scout_C) \
    x(ITM_FuelCannisterStatus_C) \
    x(ITM_DeepDiveStatus_Animator_C) \
    x(ITM_MisSel_ObjectivePrimary_C) \
    x(ITM_JobsEntry_Resource_C) \
    x(ITM_CommunityGoalResult_C) \
    x(ITM_Modding_Loadout_C) \
    x(ITM_SegmentedArmorBar_C) \
    x(ITM_BarGlass_Item_RandoWeisser_C) \
    x(ITM_UpgGear_GearStat_C) \
    x(ITM_UpgGear_GearTab_C) \
    x(ITM_Flare_Large_Gunner_C) \
    x(ITM_DeepDives_Launcher_C) \
    x(ITM_TopBar_ResourceCounter_C) \
    x(ITM_BarGlass_Item_Oktoberfest_C) \
    x(ITM_BarGlass_Item_BlackreachBlonde_C) \
    x(ITM_BarGlass_Item_RockyMountain_C) \
    x(ITM_NewsTicker_C) \
    x(ITM_Overclock_Icon_C) \
    x(ITM_Campaign_Icon_C) \
    x(ITM_ItemUnlockedIcon_C) \
    x(ITM_OnlineRestricted_C) \
    x(ITM_DragRotateCharacterShowroom_C) \
    x(ITM_ServerList_Entry_PlayerIcons_C) \
    x(ITM_BigButton_C) \
    x(ITM_CharacterDeepDive_C) \
    x(ITM_ResetFaction_C) \
    x(ITM_BossFightContainer_C) \
    x(ITM_EscMenu_BriefingV2_C) \
    x(ITM_Wardrobe_ClassSelector_C) \
    x(ITM_DeepDive_Codename_C) \
    x(ITM_Grenade_HE_Base_C) \
    x(ITM_WarningAndMutator_C) \
    x(ITM_Season_Progress_TerminalVersion_C) \
    x(ITM_ClassLevelRequirement_C) \
    x(ITM_StatusScreen_PerkItem_C) \
    x(ITM_SkinIcon_C) \
    x(ITM_Challenge_InfoBox_C) \
    x(ITM_TopBar_CharacterIcon_C) \
    x(ITM_WarningWithPercent_C) \
    x(ITM_FactionSelect_C) \
    x(ITM_MasteryBar_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_C) \
    x(ITM_CommunityGoalReward_C) \
    x(ITM_BarGlass_Item_OilyOafBrew_SupporterEdition_C) \
    x(ITM_MissionBarDropPod_Objective_C) \
    x(ITM_RestoreSave_Resources_C) \
    x(ITM_BarGlass_Item_SkullCrusherAle_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_GrenadeIcon_C) \
    x(ITM_Trading_DailyDeal_C) \
    x(ITM_EscapeMenu_MissionModifier_C) \
    x(ITM_BarGlass_Item_Backbreaker_C) \
    x(ITM_UnlockedCelebration_C) \
    x(ITM_MisSel_MissionIcon_C) \
    x(ITM_MisSel_MissionIconSmall_C) \
    x(ITM_CommunityGoal_ConsoleScreenV2_C) \
    x(ITM_SaveSlot_Entry_Header_C) \
    x(ITM_DeepDive_ObjectiveIcon_C) \
    x(ITM_WeaponAndPerkInfo_C) \
    x(ITM_UpgGear_ResourceCounter_C) \
    x(ITM_BarGlass_Item_C) \
    x(ITM_CharacterData_C) \
    x(ITM_CommunityGoalInformation_C) \
    x(ITM_CommunityGoalCountdown_C) \
    x(ITM_Wardrobe_ItemSelector_ToolTip_C) \
    x(ITM_CampaignItem_C) \
    x(ITM_SeasonPlagueHeartBonus_C) \
    x(ITM_ChaCus_ItemSelector_C) \
    x(WPN_PlagueSoaper_C) \
    x(WPN_DualMPs_C) \
    x(WPN_DetPack_Detonator_Driller_C) \
    x(WPN_RocketRifle_C) \
    x(WPN_JetPackItem_C) \
    x(WPN_SMG_OneHand_C) \
    x(WPN_PlasmaCarbine_C) \
    x(WPN_LaserPistol_C) \
    x(WPN_PipelineBuilder_C) \
    x(WPN_ChargeBlaster_C) \
    x(WPN_OilExtractor_C) \
    x(WPN_BurstPistol_C) \
    x(WPN_HeavyParticleCannon_C) \
    x(WPN_Pickaxe_C) \
    x(WPN_Pickaxe_Engineer_C) \
    x(WPN_FlameThrower_C) \
    x(WPN_PlatformGun_C) \
    x(WPN_MicroMissileLauncher_C) \
    x(WPN_MicrowaveGun_C) \
    x(WPN_SoapVacuum_C) \
    x(WPN_RockCracker_Builder_C) \
    x(WPN_AssaultRifle_C) \
    x(WPN_Revolver_C) \
    x(WPN_CombatShotgun_C) \
    x(WPN_Pickaxe_Gunner_C) \
    x(WPN_Crossbow_C) \
    x(WPN_Pickaxe_Scout_C) \
    x(WPN_FuelLine_Builder_C) \
    x(WPN_GrenadeLauncher_C) \
    x(WPN_Gatling_C) \
    x(WPN_Autocannon_C) \
    x(WPN_GooCannon_C) \
    x(WPN_GrapplingGun_C) \
    x(WPN_RecallableSentryGun_C) \
    x(WPN_DetPack_Detonator_C) \
    x(WPN_LaserPointer_C) \
    x(WPN_LineCutter_C) \
    x(WPN_ZipLineGun_C) \
    x(WPN_CoilGun_C) \
    x(WPN_FlareGun_C) \
    x(WPN_Cryospray_C) \
    x(WPN_M1000_C) \
    x(WPN_LockOnRifle_C) \
    x(WPN_DoubleDrills_C) \
    x(WPN_Extractor_C) \
    x(WPN_SawedOffShotgun_C) \
    x(WPN_ShieldRegeneratorItem_C) \
    x(WPN_Pickaxe_Driller_C) \
    x(WPN_Pistol_A_C) \
	x(ENE_JellyBreeder_Normal_C) \
	x(ENE_Butterfly_C) \
	x(ENE_Spider_Grunt_Guard_C) \
	x(ENE_Bomber_Fire_C) \
	x(ENE_FlyingCritterBase_C) \
	x(ENE_Spider_Grunt_Guard_Radioactive_C) \
	x(ENE_Spider_Spitter_C) \
	x(ENE_FacilityTurret_Spinning_C) \
	x(ENE_Spider_ExploderTank_Ghost_C) \
	x(ENE_Spider_Grunt_Guard_Ice_C) \
	x(ENE_FacilityTurret_Burst_C) \
	x(ENE_Spider_Drone_C) \
	x(ENE_Spider_Shooter_Ground_C) \
	x(ENE_Spider_Grunt_Normal_C) \
	x(ENE_Spider_Exploding_C) \
	x(ENE_Spider_Tank_Amber_C) \
	x(ENE_HydraWeed_Core_C) \
	x(ENE_JellyBreeder_Base_C) \
	x(ENE_Spider_Amber_Shooter_C) \
	x(ENE_Spider_Tank_Ice_C) \
	x(ENE_Jelly_Passive_C) \
	x(ENE_Spider_Boss_TwinA_C) \
	x(ENE_ShootingPlant_Small_C) \
	x(ENE_Jelly_Swarmer_C) \
	x(ENE_Prospector_C) \
	x(ENE_FacilityTentacle_End_C) \
	x(ENE_Spider_Tank_Rock_C) \
	x(ENE_Spider_ExploderTank_King_C) \
	x(ENE_Harvester_C) \
	x(ENE_Spider_Exploding_Rockpox_Plague_C) \
	x(ENE_Bomber_Rockpox_Plague_C) \
	x(ENE_Spider_ShieldTank_C) \
	x(ENE_FacilityTurret_Sniper_C) \
	x(ENE_Spider_Shooter_C) \
	x(ENE_Spider_Swarmer_Radioactive_C) \
	x(ENE_Spider_RapidShooter_Elite_C) \
	x(ENE_Bomber_Child_C) \
	x(ENE_Spider_Charger_C) \
	x(ENE_Spider_Swarmer_Pheromoned_C) \
	x(ENE_PlagueLarva_C) \
	x(ENE_Jelly_Swarmer_Child_C) \
	x(ENE_Jelly_Spawn_Child_C) \
	x(ENE_FacilityTentacle_Burrowing_C) \
	x(ENE_SpiderSpawner_C) \
	x(ENE_Spider_Shooter_Normal_Elite_C) \
	x(ENE_Spider_Exploding_Warning_Radioactive_C) \
	x(ENE_Spider_Tank_Radioactive_C) \
	x(ENE_Grabber_C) \
	x(ENE_Spider_Boss_HeavySpawn_C) \
	x(ENE_BoughWasp_Nest_Medium2_C) \
	x(ENE_Spider_Grunt_Attacker_Ice_C) \
	x(ENE_Shredder_C) \
	x(ENE_Spider_RapidShooter_C) \
	x(ENE_Spider_Tank_Generic_C) \
	x(ENE_Spider_Tank_Normal_C) \
	x(ENE_BoughWasp_Nest_Medium_C) \
	x(ENE_Spider_Boss_Base_C) \
	x(ENE_Spider_Boss_TwinBase_C) \
	x(ENE_BoughWasp_Swarm_C) \
	x(ENE_Spider_Exploding_Radioactive_C) \
	x(ENE_LootBug_C) \
	x(ENE_Spider_Tank_Base_C) \
	x(ENE_Mactera_TripleShooter_C) \
	x(ENE_TerminatorTentacle_C) \
	x(ENE_LootBug_Gold_C) \
	x(ENE_Spider_Grunt_Rock_C) \
	x(ENE_Terminator_C) \
	x(ENE_Spider_Grunt_Attacker_Radioactive_C) \
	x(ENE_Spider_Shooter_Rockpox_Plague_C) \
	x(ENE_Spider_Boss_TwinB_C) \
	x(ENE_Spider_ExploderTank_C) \
	x(ENE_Spider_Boss_Heavy_C) \
	x(ENE_GliderBeast_C) \
	x(ENE_Flea_C) \
	x(ENE_Spider_Grunt_Attacker_C) \
	x(ENE_ElectricPlantVThree_C) \
	x(ENE_Spider_Tank_Boss_C) \
	x(ENE_Spider_Grunt_Radioactive_C) \
	x(ENE_Spider_Stinger_C) \
	x(ENE_PF_SpiderBase_C) \
	x(ENE_Spider_Spawn_C) \
	x(ENE_Maggot_Red1_C) \
	x(ENE_StabberVines2_C) \
	x(ENE_Spider_Swarmer_C) \
	x(ENE_Spider_Buffer_C) \
	x(ENE_Mactera_Shooter_Normal_C) \
	x(ENE_Spider_Swarmer_Ice_C) \
	x(ENE_ShootingPlant_C) \
	x(ENE_Parasite_C) \
	x(ENE_Mactera_Amber_C) \
	x(ENE_InsectSwarm_Spawner_C) \
	x(ENE_Woodlouse_Youngling_C) \
	x(ENE_Bomber_Ice_C) \
	x(ENE_Spider_Grunt_Base_C) \
	x(ENE_BoughWasp_Nest_Medium3_C) \
	x(ENE_Bomber_C) \
	x(ENE_Maggot_C) \
	x(ENE_SmallShootingPlant_RegenPod_C) \
	x(ENE_Shredder_Base_C) \
	x(ENE_StabberVine_Tentacle_C) \
	x(ENE_InfestationLarva_C) \
	x(ENE_Woodlouse_C) \
	x(ENE_Shark_C) \
	x(ENE_Maggot_Normal_C) \
	x(ENE_FlyingSmartRock_C) \
	x(ENE_EnemySpawner_C) \
	x(ENE_Spider_Exploding_Warning_C) \
	x(ENE_Spider_Grunt_Ice_C) \
	x(ENE_FacilityTurret_Barrier_C) \
	x(ENE_FacilityTentacle_C) \
	x(ENE_Jelly_Passive_Mother_C) \
	x(ENE_InsectSwarm_C) \
	x(ENE_Maggot_Azure_C) \
	x(ENE_Spider_Shooter_Queen_C) \
	x(ENE_JellyBreeder_RockpoxPlague_C) \
	x(ENE_WalkingPlagueheart_C) \
	x(ENE_Spider_Hoarder_C) \
	x(ENE_StabberVines_C) \
	x(ENE_Spider_Tank_RockpoxPlague_C) \
	x(ENE_FacilityCaretaker_C) \
	x(ENE_InfectedMule_C) \
	x(ENE_Mactera_Shooter_Base_C) \
	x(ENE_Maggot_HollowBough_Grub_C) \
	x(ENE_Spider_Shooter_Normal_C) \
	x(ENE_Spider_Grunt_RockpoxPlague_C) \
	x(ENE_CaveLeech_C) \
	x(ENE_FacilityTurret_Base_C) \
	x(ENE_Maggot_Green1_C) \
	x(ENE_Maggot_SplineTrail_C) \
	x(ENE_Mactera_Shooter_HeavyVeteran_C) \
	x(ENE_PlagueShark_C) \
	x(ENE_Spider_Lobber_C) \
	x(ENE_PatrolBot_C) \
	x(ENE_PatrolBot_Caretaker_C) \
	x(ENE_SpiderBase_Large_C) \
	x(ENE_BoughWasp_Nest_Small_C) \
	x(ENE_Spider_Lobber_Base_C) \
    x(BP_Gem_C) \
    x(InProgress) \
