#pragma once

/**
 * Name: Deep_Rock_Galactic
 * Version: 1.38.91584.0
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Enums
	// --------------------------------------------------
	/**
	 * BoneSkeletalMesh SK_DropPod_Drill.SK_DropPod_Drill
	 */
	enum class EBone_SK_DropPod_Drill : uint8_t
	{
		Root_DropPod_Drill = 0,
		Drill01            = 1,
		Drill02            = 2,
		Drill03            = 3,
		Drill04            = 4
	};

	/**
	 * BoneSkeletalMesh SK_DropPod_Airlock02.SK_DropPod_Airlock02
	 */
	enum class EBone_SK_DropPod_Airlock02 : uint8_t
	{
		Root_DropPod_Airlock    = 0,
		InnerAirlock_LowerCore  = 1,
		InnerAirlock_LowerShell = 2,
		InnerAirlock_UpperCore  = 3,
		InnerAirlock_UpperShell = 4,
		OuterAirlock_Left       = 5,
		OuterAirlock_Right      = 6,
		OuterAirlock_Top        = 7,
		InnerAirlock_LowerWire  = 8,
		InnerAirlock_UpperWire  = 9
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Head001.SK_Vanity_Head001
	 */
	enum class EBone_SK_Vanity_Head001 : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_CombatShotgun_C.SK_CombatShotgun_C
	 */
	enum class EBone_SK_CombatShotgun_C : uint8_t
	{
		SK_CombatShotgun_A_Root         = 0,
		SK_CombatShotgun_A_Bullet       = 1,
		SK_CombatShotgun_A_Muzzle       = 2,
		SK_CombatShotgun_A_Slide        = 3,
		SK_CombatShotgun_A_Casing       = 4,
		SK_CombatShotgun_A_TopPart_A    = 5,
		SK_CombatShotgun_A_TopPart_B    = 6,
		SK_CombatShotgun_A_Dustcover    = 7,
		SK_CombatShotgun_A_DustcoverPin = 8,
		SK_CombatShotgun_A_Ejector      = 9,
		SK_CombatShotgun_A_Forend       = 10,
		SK_CombatShotgun_A_Mag          = 11,
		SK_CombatShotgun_A_Mag_Empty    = 12
	};

	/**
	 * BoneSkeletalMesh SK_Flier_Shooter.SK_Flier_Shooter
	 */
	enum class EBone_SK_Flier_Shooter : uint8_t
	{
		ShooterBug_Root            = 0,
		ShooterBug_Body            = 1,
		ShooterBug_Head            = 2,
		ShooterBug_Mandible_L_3    = 3,
		ShooterBug_Mandible_L_2    = 4,
		ShooterBug_Mandible_R_3    = 5,
		ShooterBug_Mandible_R_2    = 6,
		ShooterBug_Upper_Lip       = 7,
		ShooterBug_Lower_Lip       = 8,
		ShooterBug_Right_Lip       = 9,
		ShooterBug_Left_Lip        = 10,
		ShooterBug_LWing_Front_2   = 11,
		ShooterBug_LWing_Front_3   = 12,
		ShooterBug_RArm_Front_2    = 13,
		ShooterBug_RArm_Front_3    = 14,
		ShooterBug_RArm_Front_Palm = 15,
		ShooterBug_LArm_Front_2    = 16,
		ShooterBug_LArm_Front_3    = 17,
		ShooterBug_LArm_Front_Palm = 18,
		ShooterBug_RArm_Back_2     = 19,
		ShooterBug_RArm_Back_3     = 20,
		ShooterBug_RArm_Back_Palm  = 21,
		ShooterBug_LArm_Back_2     = 22,
		ShooterBug_LArm_Back_3     = 23,
		ShooterBug_LArm_Back_Palm  = 24,
		ShooterBug_LWing_Back_2    = 25,
		ShooterBug_LWing_Back_3    = 26,
		ShooterBug_RWing_Back_2    = 27,
		ShooterBug_RWing_Back_3    = 28,
		ShooterBug_RWing_Front_2   = 29,
		ShooterBug_RWing_Front_3   = 30,
		ShooterBug_Tail_2          = 31,
		ShooterBug_Tail_3          = 32,
		ShooterBug_Tail_4          = 33,
		ShooterBug_Tail_5          = 34,
		ShooterBug_Tail_6          = 35,
		ShooterBug_Tail_7          = 36,
		ShooterBug_WeakPoint       = 37,
		ShooterBug_Armor_R         = 38,
		ShooterBug_Armor_L         = 39
	};

	/**
	 * BoneSkeletalMesh SK_Flier_Grabber_A.SK_Flier_Grabber_A
	 */
	enum class EBone_SK_Flier_Grabber_A : uint8_t
	{
		GrabberBug_Root             = 0,
		GrabberBug_Body             = 1,
		GrabberBug_Head             = 2,
		GrabberBug_Mandible_L_3     = 3,
		GrabberBug_Mandible_R_3     = 4,
		GrabberBug_LWing_Front_2    = 5,
		GrabberBug_LWing_Front_3    = 6,
		GrabberBug_RArm_Front_2     = 7,
		GrabberBug_RArm_Front_3     = 8,
		GrabberBug_RArm_Front_Palm  = 9,
		GrabberBug_RFront_Toe       = 10,
		GrabberBug_LArm_Front_2     = 11,
		GrabberBug_LArm_Front_3     = 12,
		GrabberBug_LArm_Front_Palm  = 13,
		GrabberBug_LFront_Toe       = 14,
		GrabberBug_RArm_Back_2      = 15,
		GrabberBug_RArm_Back_3      = 16,
		GrabberBug_RArm_Back_Palm   = 17,
		GrabberBug_RBack_Toe        = 18,
		GrabberBug_LArm_Back_2      = 19,
		GrabberBug_LArm_Back_3      = 20,
		GrabberBug_LArm_Back_Palm   = 21,
		GrabberBug_LBack_Toe        = 22,
		GrabberBug_LWing_Back_2     = 23,
		GrabberBug_LWing_Back_3     = 24,
		GrabberBug_RWing_Back_2     = 25,
		GrabberBug_RWing_Back_3     = 26,
		GrabberBug_RWing_Front_2    = 27,
		GrabberBug_RWing_Front_3    = 28,
		GrabberBug_Tail_2           = 29,
		GrabberBug_Tail_3           = 30,
		GrabberBug_Tail_4           = 31,
		GrabberBug_Tail_5           = 32,
		GrabberBug_Tail_6           = 33,
		GrabberBug_Tail_7           = 34,
		GrabberBug_LArm_Middle_2    = 35,
		GrabberBug_LArm_Middle_3    = 36,
		GrabberBug_LArm_Middle_Palm = 37,
		GrabberBug_LMiddle_Toe      = 38,
		GrabberBug_RArm_Middle_2    = 39,
		GrabberBug_RArm_Middle_3    = 40,
		GrabberBug_RArm_Middle_Palm = 41,
		GrabberBug_RMiddle_Toe      = 42,
		GrabberBug_Back             = 43,
		GrabberBug_WeakSpot         = 44
	};

	/**
	 * BoneSkeletalMesh SK_Flier_Heavy.SK_Flier_Heavy
	 */
	enum class EBone_SK_Flier_Heavy : uint8_t
	{
		ShooterBug_Root            = 0,
		ShooterBug_Body            = 1,
		ShooterBug_Head            = 2,
		ShooterBug_Mandible_L_3    = 3,
		ShooterBug_Mandible_L_2    = 4,
		ShooterBug_Mandible_R_3    = 5,
		ShooterBug_Mandible_R_2    = 6,
		ShooterBug_Upper_Lip       = 7,
		ShooterBug_Lower_Lip       = 8,
		ShooterBug_Right_Lip       = 9,
		ShooterBug_Left_Lip        = 10,
		ShooterBug_LWing_Front_2   = 11,
		ShooterBug_LWing_Front_3   = 12,
		ShooterBug_RArm_Front_2    = 13,
		ShooterBug_RArm_Front_3    = 14,
		ShooterBug_RArm_Front_Palm = 15,
		ShooterBug_LArm_Front_2    = 16,
		ShooterBug_LArm_Front_3    = 17,
		ShooterBug_LArm_Front_Palm = 18,
		ShooterBug_RArm_Back_2     = 19,
		ShooterBug_RArm_Back_3     = 20,
		ShooterBug_RArm_Back_Palm  = 21,
		ShooterBug_LArm_Back_2     = 22,
		ShooterBug_LArm_Back_3     = 23,
		ShooterBug_LArm_Back_Palm  = 24,
		ShooterBug_LWing_Back_2    = 25,
		ShooterBug_LWing_Back_3    = 26,
		ShooterBug_RWing_Back_2    = 27,
		ShooterBug_RWing_Back_3    = 28,
		ShooterBug_RWing_Front_2   = 29,
		ShooterBug_RWing_Front_3   = 30,
		ShooterBug_Tail_2          = 31,
		ShooterBug_Tail_3          = 32,
		ShooterBug_Tail_4          = 33,
		ShooterBug_Tail_5          = 34,
		ShooterBug_Tail_6          = 35,
		ShooterBug_Tail_7          = 36,
		ShooterBug_WeakPoint       = 37,
		ShooterBug_Armor_R         = 38,
		ShooterBug_Armor_L         = 39
	};

	/**
	 * BoneSkeletalMesh SK_Flier_Triple_Shooter.SK_Flier_Triple_Shooter
	 */
	enum class EBone_SK_Flier_Triple_Shooter : uint8_t
	{
		ShooterBug_Root            = 0,
		ShooterBug_Body            = 1,
		ShooterBug_Head            = 2,
		ShooterBug_Mandible_L_3    = 3,
		ShooterBug_Mandible_L_2    = 4,
		ShooterBug_Mandible_R_3    = 5,
		ShooterBug_Mandible_R_2    = 6,
		ShooterBug_Upper_Lip       = 7,
		ShooterBug_Lower_Lip       = 8,
		ShooterBug_Right_Lip       = 9,
		ShooterBug_Left_Lip        = 10,
		ShooterBug_LWing_Front_2   = 11,
		ShooterBug_LWing_Front_3   = 12,
		ShooterBug_RArm_Front_2    = 13,
		ShooterBug_RArm_Front_3    = 14,
		ShooterBug_RArm_Front_Palm = 15,
		ShooterBug_LArm_Front_2    = 16,
		ShooterBug_LArm_Front_3    = 17,
		ShooterBug_LArm_Front_Palm = 18,
		ShooterBug_RArm_Back_2     = 19,
		ShooterBug_RArm_Back_3     = 20,
		ShooterBug_RArm_Back_Palm  = 21,
		ShooterBug_LArm_Back_2     = 22,
		ShooterBug_LArm_Back_3     = 23,
		ShooterBug_LArm_Back_Palm  = 24,
		ShooterBug_LWing_Back_2    = 25,
		ShooterBug_LWing_Back_3    = 26,
		ShooterBug_RWing_Back_2    = 27,
		ShooterBug_RWing_Back_3    = 28,
		ShooterBug_RWing_Front_2   = 29,
		ShooterBug_RWing_Front_3   = 30,
		ShooterBug_Tail_2          = 31,
		ShooterBug_Tail_3          = 32,
		ShooterBug_Tail_4          = 33,
		ShooterBug_Tail_5          = 34,
		ShooterBug_Tail_6          = 35,
		ShooterBug_Tail_7          = 36,
		ShooterBug_WeakPoint       = 37,
		ShooterBug_Armor_R         = 38,
		ShooterBug_Armor_L         = 39
	};

	/**
	 * BoneSkeletalMesh SK_Spider_Tank_A.SK_Spider_Tank_A
	 */
	enum class EBone_SK_Spider_Tank_A : uint8_t
	{
		Spider_Root                = 0,
		Spider_Chest               = 1,
		Spider_Back                = 2,
		Spider_Head                = 3,
		Spider_UpperJaw            = 4,
		Spider_LowerJaw            = 5,
		Spider_LeftLowerJaw        = 6,
		Spider_RightLowerJaw       = 7,
		Spider_UpperJawSkin        = 8,
		Spider_NeckTop             = 9,
		Spider_NeckRight           = 10,
		Spider_NeckButtom          = 11,
		Spider_NeckLeft            = 12,
		Spider_LegL_Front_2        = 13,
		Spider_LegL_Front_3        = 14,
		Spider_LegL_Front_4        = 15,
		Spider_LegR_Front_Part_2   = 16,
		Spider_LegR_Front_Part_3   = 17,
		Spider_LegR_Front_Part_4   = 18,
		Spider_LegL_1_Part_2       = 19,
		Spider_LegL_1_Part_3       = 20,
		Spider_LegL_2_Part_2       = 21,
		Spider_LegL_2_Part_3       = 22,
		Spider_LegR_1_Part_2       = 23,
		Spider_LegR_1_Part_3       = 24,
		Spider_LegR_2_Part_2       = 25,
		Spider_LegR_2_Part_3       = 26,
		Spider_LegL_3_Part_2       = 27,
		Spider_LegL_3_Part_3       = 28,
		Spider_LegR_3_Part_2       = 29,
		Spider_LegR_3_Part_3       = 30,
		Spider_BackR_1_Armor       = 31,
		Spider_BackR_2_Armor       = 32,
		Spider_BackL_1_Armor       = 33,
		Spider_BackL_2_Armor       = 34,
		Spider_LegL_Front_Armor_3  = 35,
		Spider_LegL_Front_Armor_2  = 36,
		Spider_LegR_Front_Armor_3  = 37,
		Spider_LegR_Front_Armor_2  = 38,
		Spider_LegL_1_Armor        = 39,
		Spider_LegL_2_Armor        = 40,
		Spider_LegR_1_Armor        = 41,
		Spider_LegR_2_Armor        = 42,
		Spider_LegL_3_Armor        = 43,
		Spider_LegR_3_Armor        = 44,
		Spider_ChestL_1_Armor      = 45,
		Spider_ChestR_1_Armor      = 46,
		Spider_BackC_1_Armor       = 47,
		Spider_ChestC_1_Armor      = 48,
		Spider_ChestR_2_Armor      = 49,
		Spider_ChestL_2_Armor      = 50,
		SK_Spider_Shell_Root_R     = 51,
		SK_Spider_Shell_R          = 52,
		SK_Spider_Shell_Root_L     = 53,
		SK_Spider_Shell_L          = 54,
		SK_Spider_WeakSpot         = 55,
		SK_Spider_RageSpot_Root_L  = 56,
		SK_Spider_RageSpot_L       = 57,
		SK_Spider_RageSpot_Root_R  = 58,
		SK_Spider_RageSpot_R       = 59,
		SK_Spider_RageSpot_Root_C  = 60,
		SK_Spider_RageSpot_C       = 61,
		Spider_BackL_2_Armor001    = 62,
		SK_Spider_BackR_1_Armor    = 63,
		Spider_BackC_1_Armor001    = 64,
		SK_Spider_BackR_3_Armor    = 65,
		SK_Spider_BackL_3_Armor    = 66,
		SK_Spider_ChestR_1_Armor   = 67,
		SK_Spider_ChestL_1_Armor   = 68,
		SK_Spider_Breath_Muzzle    = 69,
		SK_Spider_LegL_Front_Armor = 70,
		SK_Spider_LegR_Front_Armor = 71,
		SK_Spider_Muzzle_R         = 72,
		SK_Spider_Muzzle_L         = 73,
		Spider_Back1               = 74,
		Spider_Tail1               = 75,
		Spider_Tail2               = 76,
		Spider_Tail3               = 77,
		Spider_Tail4               = 78,
		Spider_Tail5               = 79,
		Spider_Tail6               = 80,
		Spider_Tail7               = 81,
		Spider_Tail8               = 82,
		Spider_Tail_armor8         = 83,
		Spider_Tail_armor7         = 84,
		Spider_Tail_armor6         = 85,
		Spider_Tail_armor5         = 86,
		Spider_Tail_armor4         = 87,
		Spider_Tail_armor3         = 88,
		Spider_Tail_armor2         = 89,
		Spider_Tail_armor1         = 90,
		Spider_Butt_2              = 91,
		Spider_Butt_3              = 92,
		Spider_Butt_4              = 93,
		Spider_Butt_3_Scale        = 94,
		Spider_Butt_2_Scale        = 95,
		Spider_Butt_1_Scale        = 96,
		Spider_Butt_3_Armor        = 97,
		Spider_Butt_2_Armor        = 98,
		Spider_Butt_1_Armor        = 99,
		Spider_AntennaeBack        = 100
	};

	/**
	 * BoneSkeletalMesh SK_SlidingDoor01.SK_SlidingDoor01
	 */
	enum class EBone_SK_SlidingDoor01 : uint8_t
	{
		Frame         = 0,
		DoorMain      = 1,
		DoorSideInner = 2,
		DoorSide      = 3
	};

	/**
	 * BoneSkeletalMesh SK_jetBoot_crate.SK_jetBoot_crate
	 */
	enum class EBone_SK_jetBoot_crate : uint8_t
	{
		jetBootCrate_root  = 0,
		lid_001            = 1,
		Lock               = 2,
		lock_R             = 3,
		lock_L             = 4,
		lid_002            = 5,
		jetbootPlatform_01 = 6,
		jetBoot_01         = 7,
		jetbootPlatform_02 = 8,
		jetBoot_02         = 9,
		jetbootPlatform_03 = 10,
		jetBoot_03         = 11,
		jetbootPlatform_04 = 12,
		jetBoot_04         = 13
	};

	/**
	 * BoneSkeletalMesh SK_3P_Dwarf_Rig.SK_3P_Dwarf_Rig
	 */
	enum class EBone_SK_3P_Dwarf_Rig : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Dice.SK_Dice
	 */
	enum class EBone_SK_Dice : uint8_t
	{
		Root      = 0,
		String_00 = 1,
		String_01 = 2,
		String_02 = 3,
		Dice      = 4
	};

	/**
	 * BoneSkeletalMesh SK_Bosco_Default.SK_Bosco_Default
	 */
	enum class EBone_SK_Bosco_Default : uint8_t
	{
		MainBody        = 0,
		Hatch_Cover_R   = 1,
		Hatch_Cover_L   = 2,
		Ear_R           = 3,
		Ear_L           = 4,
		Gun_Arm_L       = 5,
		Gun_Case_L      = 6,
		Gun_Barrel01_L  = 7,
		Gun_Barrel02_L  = 8,
		Gun_Arm_R       = 9,
		Gun_Case_R      = 10,
		Gun_Barrel01_R  = 11,
		Gun_Barrel02__R = 12,
		LowerBody       = 13,
		Arm01_L         = 14,
		Arm02_L         = 15,
		Arm03_L         = 16,
		Arm01_R         = 17,
		Arm02_R         = 18,
		Arm03_R         = 19,
		MidRiff         = 20,
		Thruster_L      = 21,
		Thruster_R      = 22,
		Butterfly       = 23,
		Gun_Drum_L      = 24,
		Gun_Drum_R      = 25,
		Hat             = 26,
		Plague          = 27,
		Vial            = 28,
		Tube_back       = 29,
		Tube_R          = 30,
		Tube_L          = 31,
		Elf_hat01       = 32,
		Elf_hat02       = 33,
		Elf_hat03       = 34,
		Elf_hat04       = 35,
		Elf_hat05       = 36,
		Bag             = 37,
		Belt_M          = 38,
		Belt_R          = 39,
		Belt_L          = 40,
		Headband_M      = 41,
		Headband01_R    = 42,
		Headband02_R    = 43,
		Headband03_R    = 44,
		Headband01_L    = 45,
		Headband02_L    = 46,
		Headband03_L    = 47
	};

	/**
	 * BoneSkeletalMesh SK_DrinksBox.SK_DrinksBox
	 */
	enum class EBone_SK_DrinksBox : uint8_t
	{
		Box  = 0,
		Tray = 1,
		Lid  = 2
	};

	/**
	 * BoneSkeletalMesh SK_AutoCannon_Skin_Infected.SK_AutoCannon_Skin_Infected
	 */
	enum class EBone_SK_AutoCannon_Skin_Infected : uint8_t
	{
		SK_AutoCannon_A_Root              = 0,
		SK_AutoCannon_A_Muzzle_Left       = 1,
		SK_AutoCannon_A_Muzzle_Right      = 2,
		SK_AutoCannon_A_Mag_Anim          = 3,
		SK_AutoCannon_A_LeftAmmunition_C  = 4,
		SK_AutoCannon_A_LeftAmmunition_B  = 5,
		SK_AutoCannon_A_LeftAmmunition_A  = 6,
		SK_AutoCannon_A_LeftAmmunition_D  = 7,
		SK_AutoCannon_A_RightAmmunition_C = 8,
		SK_AutoCannon_A_RightAmmunition_D = 9,
		SK_AutoCannon_A_RightAmmunition_A = 10,
		SK_AutoCannon_A_RightAmmunition_B = 11,
		SK_AutoCannon_A_LeftHandle_B      = 12,
		SK_AutoCannon_A_LeftHandle_A      = 13,
		SK_AutoCannon_A_Barrel_Left       = 14,
		SK_AutoCannon_A_Spring_Left       = 15,
		SK_AutoCannon_A_Barrel_Right      = 16,
		SK_AutoCannon_A_Spring_Right      = 17,
		SK_AutoCannon_A_Slide_Left_C      = 18,
		SK_AutoCannon_A_Slide_Left_B      = 19,
		SK_AutoCannon_A_Slide_Left_A      = 20,
		SK_AutoCannon_A_Slide_Right_A     = 21,
		SK_AutoCannon_A_Slide_Right_B     = 22,
		SK_AutoCannon_A_Slide_Right_C     = 23,
		SK_AutoCannon_A_LoadArm_Left_A    = 24,
		SK_AutoCannon_A_LoadArm_Left_B    = 25,
		SK_AutoCannon_A_LoadArm_Right_A   = 26,
		SK_AutoCannon_A_LoadArm_Right_B   = 27,
		SK_AutoCannon_A_Mag_Static        = 28
	};

	/**
	 * BoneSkeletalMesh SK_Shredder.SK_Shredder
	 */
	enum class EBone_SK_Shredder : uint8_t
	{
		Root_base        = 0,
		Base             = 1,
		Shell_LowerBack  = 2,
		Shell_UpperBack  = 3,
		Torso            = 4,
		Shell_LowerFront = 5,
		Shell_UpperFront = 6,
		Knife_L          = 7,
		Knife_R          = 8
	};

	/**
	 * BoneSkeletalMesh SK_Mug011.SK_Mug011
	 */
	enum class EBone_SK_Mug011 : uint8_t
	{
		Mug001      = 0,
		Mug001_Foam = 1,
		Mug010      = 2,
		Mug019      = 3,
		Mug012      = 4,
		Mug013      = 5,
		Mug002      = 6,
		Mug014      = 7,
		Mug008      = 8,
		Mug011      = 9,
		Mug007      = 10,
		Mug018      = 11,
		Mug006      = 12,
		Mug003      = 13,
		Mug004      = 14,
		Mug015      = 15,
		Mug017      = 16,
		Mug009      = 17,
		Mug005      = 18,
		Mug016      = 19,
		Mug007_Foam = 20,
		FoamOrg     = 21,
		Mug020      = 22,
		Mug_020     = 23,
		Mug001_Lid  = 24,
		Mug_Sausage = 25,
		Mug_DLC08   = 26
	};

	/**
	 * BoneSkeletalMesh SK_Mug_Generic01.SK_Mug_Generic01
	 */
	enum class EBone_SK_Mug_Generic01 : uint8_t
	{
		Mug001      = 0,
		Mug001_Foam = 1,
		Mug010      = 2,
		Mug019      = 3,
		Mug012      = 4,
		Mug013      = 5,
		Mug002      = 6,
		Mug014      = 7,
		Mug008      = 8,
		Mug011      = 9,
		Mug007      = 10,
		Mug018      = 11,
		Mug006      = 12,
		Mug003      = 13,
		Mug004      = 14,
		Mug015      = 15,
		Mug017      = 16,
		Mug009      = 17,
		Mug005      = 18,
		Mug016      = 19,
		Mug007_Foam = 20,
		FoamOrg     = 21,
		Mug020      = 22,
		Mug_020     = 23,
		Mug001_Lid  = 24,
		Mug_Sausage = 25,
		Mug_DLC08   = 26
	};

	/**
	 * BoneSkeletalMesh SK_DetPack_Charge.SK_DetPack_Charge
	 */
	enum class EBone_SK_DetPack_Charge : uint8_t
	{
		SK_DetPack_Charge = 0
	};

	/**
	 * BoneSkeletalMesh SK_Plague_spider_Grunt_Leg.SK_Plague_spider_Grunt_Leg
	 */
	enum class EBone_SK_Plague_spider_Grunt_Leg : uint8_t
	{
		grunt_grp            = 0,
		GRUNT_SHOULDER       = 1,
		GRUNT_ELBOW          = 2,
		GRUNT_HAND           = 3,
		grunt_attachmentJnt1 = 4,
		grunt_attachmentJnt2 = 5,
		grunt_attachmentJnt3 = 6,
		GRUNT_BASE           = 7,
		SK_Spider_Grunt_LEG  = 8,
		grunt_attachments    = 9
	};

	/**
	 * BoneSkeletalMesh SK_Drill_Right_B.SK_Drill_Right_B
	 */
	enum class EBone_SK_Drill_Right_B : uint8_t
	{
		Right_Drill_Root          = 0,
		Right_Drill_DrillRotator1 = 1,
		Right_Drill_DrillRotator2 = 2,
		Right_Drill_DriveShaft    = 3,
		Right_Drill_Piston1       = 4,
		Right_Drill_Piston2       = 5
	};

	/**
	 * BoneSkeletalMesh SK_Drill_Left_B.SK_Drill_Left_B
	 */
	enum class EBone_SK_Drill_Left_B : uint8_t
	{
		Left_Drill_Root          = 0,
		Left_Drill_DrillRotator1 = 1,
		Left_Drill_DrillRotator2 = 2,
		Left_Drill_DriveShaft    = 3,
		Left_Drill_Piston1       = 4,
		Left_Drill_Piston2       = 5
	};

	/**
	 * BoneSkeletalMesh SK_DualMachinePistol_A.SK_DualMachinePistol_A
	 */
	enum class EBone_SK_DualMachinePistol_A : uint8_t
	{
		SK_DualMachinePistol_A_Root           = 0,
		SK_DualMachinePistol_A_Break          = 1,
		SK_DualMachinePistol_A_Trigger        = 2,
		SK_DualMachinePistol_A_FireAction     = 3,
		SK_DualMachinePistol_A_Vent           = 4,
		SK_DualMachinePistol_A_Muzzle         = 5,
		SK_DualMachinePistol_A_Mag_Stationary = 6,
		SK_DualMachinePistol_A_Mag_Animate    = 7
	};

	/**
	 * BoneSkeletalMesh SK_HandGrenade_U.SK_HandGrenade_U
	 */
	enum class EBone_SK_HandGrenade_U : uint8_t
	{
		SK_HandGrenade_U_Root  = 0,
		SK_HandGrenade_U_Clamp = 1,
		SK_HandGrenade_U_Body  = 2,
		SK_HandGrenade_U_Mag   = 3
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_ArmorDriller003_FP.SK_Vanity_ArmorDriller003_FP
	 */
	enum class EBone_SK_Vanity_ArmorDriller003_FP : uint8_t
	{
		Dwarf_RootBone         = 0,
		Dwarf_Pelvis           = 1,
		Dwarf_Spine1           = 2,
		Dwarf_Spine2           = 3,
		Dwarf_Spine3           = 4,
		Dwarf_Ribcage          = 5,
		Dwarf_Neck             = 6,
		Dwarf_Head             = 7,
		Dwarf_Camera_Attach    = 8,
		Dwarf_ArmLShoulder     = 9,
		Dwarf_ArmL1            = 10,
		Dwarf_ArmL21           = 11,
		Dwarf_ArmL22           = 12,
		Dwarf_ArmLHand         = 13,
		Dwarf_ArmLDigit01      = 14,
		Dwarf_ArmLDigit02      = 15,
		Dwarf_ArmLDigit03      = 16,
		Dwarf_ArmLDigit012     = 17,
		Dwarf_ArmLDigit013     = 18,
		Dwarf_ArmLDigit014     = 19,
		Dwarf_ArmLDigit015     = 20,
		Dwarf_ArmLDigit016     = 21,
		Dwarf_ArmLDigit017     = 22,
		Dwarf_ArmLDigit018     = 23,
		Dwarf_ArmLDigit019     = 24,
		Dwarf_ArmLDigit08      = 25,
		Dwarf_ArmLDigit09      = 26,
		Dwarf_ArmLDigit010     = 27,
		Dwarf_ArmLDigit011     = 28,
		Dwarf_ArmLDigit04      = 29,
		Dwarf_ArmLDigit05      = 30,
		Dwarf_ArmLDigit06      = 31,
		Dwarf_ArmLDigit07      = 32,
		Dwarf_HandL_Attach     = 33,
		Dwarf_ShoulderL_Attach = 34,
		Dwarf_ArmRShoulder     = 35,
		Dwarf_ArmR1            = 36,
		Dwarf_ArmR21           = 37,
		Dwarf_ArmR22           = 38,
		Dwarf_ArmRHand         = 39,
		Dwarf_ArmRDigit01      = 40,
		Dwarf_ArmRDigit02      = 41,
		Dwarf_ArmRDigit03      = 42,
		Dwarf_ArmRDigit012     = 43,
		Dwarf_ArmRDigit013     = 44,
		Dwarf_ArmRDigit014     = 45,
		Dwarf_ArmRDigit015     = 46,
		Dwarf_ArmRDigit016     = 47,
		Dwarf_ArmRDigit017     = 48,
		Dwarf_ArmRDigit018     = 49,
		Dwarf_ArmRDigit019     = 50,
		Dwarf_ArmRDigit08      = 51,
		Dwarf_ArmRDigit09      = 52,
		Dwarf_ArmRDigit010     = 53,
		Dwarf_ArmRDigit011     = 54,
		Dwarf_ArmRDigit04      = 55,
		Dwarf_ArmRDigit05      = 56,
		Dwarf_ArmRDigit06      = 57,
		Dwarf_ArmRDigit07      = 58,
		Dwarf_HandR_Attach     = 59,
		Dwarf_ShoulderR_Attach = 60
	};

	/**
	 * BoneSkeletalMesh SK_SentryGun_Engineer.SK_SentryGun_Engineer
	 */
	enum class EBone_SK_SentryGun_Engineer : uint8_t
	{
		BN_ROOT                   = 0,
		BN_Base_Bottom            = 1,
		BN_Leg01                  = 2,
		BN_Foot01                 = 3,
		BN_Leg03                  = 4,
		BN_Foot03                 = 5,
		BN_Leg02                  = 6,
		BN_Foot02                 = 7,
		BN_Base_Top               = 8,
		BN_SwivelPoint_Horizontal = 9,
		BN_Body                   = 10,
		BN_InnerBody_Front        = 11,
		BN_InnerBody_Back         = 12,
		BN_TopSlider              = 13,
		BN_Spring                 = 14,
		BN_BodyCase_Left          = 15,
		BN_BodyCase_Right         = 16,
		BN_SafeRail               = 17,
		BN_Spotlight              = 18,
		BN_BodyCase_Back          = 19,
		BN_Ejector                = 20,
		BN_SwivelPoint_Vertical   = 21,
		BN_BarrelHolder           = 22,
		BN_Muzzle_Top             = 23,
		BN_Muzzle_Bottom          = 24,
		BN_BarrelTop              = 25,
		BN_BarrelBottom           = 26,
		BN_BarrelSlider           = 27,
		BN_Base_Top_3             = 28,
		BN_Base_Top_2             = 29,
		BN_DrumMag_Right          = 30,
		BN_DrumMagSpinner_Right   = 31,
		BN_DrumMag_Left           = 32,
		BN_DrumMagSpinner_Left    = 33,
		BN_Belt_Left              = 34,
		BN_Belt_Right             = 35
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Mannequin_Head.SK_Vanity_Mannequin_Head
	 */
	enum class EBone_SK_Vanity_Mannequin_Head : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Mannequin_Body.SK_Vanity_Mannequin_Body
	 */
	enum class EBone_SK_Vanity_Mannequin_Body : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Plague_WormPod_01.SK_Plague_WormPod_01
	 */
	enum class EBone_SK_Plague_WormPod_01 : uint8_t
	{
		Jnt_WormPod_Base    = 0,
		Jnt_WormPod_Body    = 1,
		Jnt_WormPod_Core    = 2,
		Jnt_WormPod_CoreC   = 3,
		Jnt_WormPod_CoreB   = 4,
		Jnt_WormPod_CoreA   = 5,
		Jnt_WormPod_ArmA_01 = 6,
		Jnt_WormPod_ArmA_02 = 7,
		Jnt_WormPod_ArmB_01 = 8,
		Jnt_WormPod_ArmB_02 = 9,
		Jnt_WormPod_ArmC_01 = 10,
		Jnt_WormPod_ArmC_02 = 11
	};

	/**
	 * BoneSkeletalMesh SK_DropPod_MuleBay.SK_DropPod_MuleBay
	 */
	enum class EBone_SK_DropPod_MuleBay : uint8_t
	{
		MollyBay_Root           = 0,
		MollyBay_Hatch_Lower    = 1,
		MollyBay_Hatch_Upper    = 2,
		MollyBay_Base           = 3,
		MollyBay_Crane_Base     = 4,
		MollyBay_Crane_Grabber  = 5,
		MollyBay_Crane_Supports = 6,
		MollyBay_ParticleSocket = 7
	};

	/**
	 * BoneSkeletalMesh SK_DropPod_OreBox.SK_DropPod_OreBox
	 */
	enum class EBone_SK_DropPod_OreBox : uint8_t
	{
		Root_OreBox         = 0,
		OreBox_LidLower     = 1,
		OreBox_LidUpper     = 2,
		OreBox_Tray         = 3,
		OreBox_GrinderLower = 4,
		OreBox_GrinderUpper = 5
	};

	/**
	 * BoneSkeletalMesh SK_DropPod_Ramp02.SK_DropPod_Ramp02
	 */
	enum class EBone_SK_DropPod_Ramp02 : uint8_t
	{
		Root          = 0,
		RampSection01 = 1,
		RampSection02 = 2,
		RampSection03 = 3,
		RampSection04 = 4,
		RampSection05 = 5,
		RampSection06 = 6
	};

	/**
	 * BoneSkeletalMesh SK_HoopsGame_Slide.SK_HoopsGame_Slide
	 */
	enum class EBone_SK_HoopsGame_Slide : uint8_t
	{
		Object003   = 0,
		Cylinder009 = 1,
		Object004   = 2
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Headwear_GreatEggHunt2023_Egg.SK_Vanity_Headwear_GreatEggHunt2023_Egg
	 */
	enum class EBone_SK_Vanity_Headwear_GreatEggHunt2023_Egg : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Drone_Bartender_AnniversaryHat.SK_Drone_Bartender_AnniversaryHat
	 */
	enum class EBone_SK_Drone_Bartender_AnniversaryHat : uint8_t
	{
		Root = 0
	};

	/**
	 * BoneSkeletalMesh SK_Moustache_Rig_A_003.SK_Moustache_Rig_A_003
	 */
	enum class EBone_SK_Moustache_Rig_A_003 : uint8_t
	{
		Head_Root            = 0,
		Armor_Bone           = 1,
		Moustache_Rig_A_R_00 = 2,
		Moustache_Rig_A_R_01 = 3,
		Moustache_Rig_A_L_00 = 4,
		Moustache_Rig_A_L_01 = 5
	};

	/**
	 * BoneSkeletalMesh SK_Headwear_Lunar_Rabbit.SK_Headwear_Lunar_Rabbit
	 */
	enum class EBone_SK_Headwear_Lunar_Rabbit : uint8_t
	{
		Headwear_Lunar_Rabbit_Root        = 0,
		Headwear_Lunar_Rabbit_DanglieR_01 = 1,
		Headwear_Lunar_Rabbit_DanglieR_02 = 2,
		Headwear_Lunar_Rabbit_DanglieL_01 = 3,
		Headwear_Lunar_Rabbit_DanglieL_02 = 4,
		Headwear_Lunar_Rabbit_EarR_01     = 5,
		Headwear_Lunar_Rabbit_EarR_02     = 6,
		Headwear_Lunar_Rabbit_EarL_01     = 7,
		Headwear_Lunar_Rabbit_EarL_02     = 8
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Headwear_HatOktoberfest.SK_Vanity_Headwear_HatOktoberfest
	 */
	enum class EBone_SK_Vanity_Headwear_HatOktoberfest : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_BeachParty_FlowerCrown.SK_BeachParty_FlowerCrown
	 */
	enum class EBone_SK_BeachParty_FlowerCrown : uint8_t
	{
		Root = 0
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Headwear_XmasHat.SK_Vanity_Headwear_XmasHat
	 */
	enum class EBone_SK_Vanity_Headwear_XmasHat : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Vanity_Headwear_Halloween2019.SK_Vanity_Headwear_Halloween2019
	 */
	enum class EBone_SK_Vanity_Headwear_Halloween2019 : uint8_t
	{
		Dwarf_RootBone                        = 0,
		Dwarf_Pelvis                          = 1,
		Dwarf_Spine1                          = 2,
		Dwarf_Spine2                          = 3,
		Dwarf_Spine3                          = 4,
		Dwarf_Ribcage                         = 5,
		Dwarf_Neck                            = 6,
		Dwarf_Head                            = 7,
		Dwarf_EyeL                            = 8,
		Dwarf_EyeR                            = 9,
		Dwarf_Beard1                          = 10,
		Dwarf_Beard2                          = 11,
		Dwarf_Beard3                          = 12,
		Dwarf_Beard4                          = 13,
		Dwarf_BeardL                          = 14,
		Dwarf_BeardR                          = 15,
		Dwarf_Head_Attach                     = 16,
		Dwarf_ArmLShoulder                    = 17,
		Dwarf_ArmL1                           = 18,
		Dwarf_ArmL21                          = 19,
		Dwarf_ArmL22                          = 20,
		Dwarf_ArmLHand                        = 21,
		Dwarf_ArmLDigit01                     = 22,
		Dwarf_ArmLDigit02                     = 23,
		Dwarf_ArmLDigit03                     = 24,
		Dwarf_ArmLDigit012                    = 25,
		Dwarf_ArmLDigit013                    = 26,
		Dwarf_ArmLDigit014                    = 27,
		Dwarf_ArmLDigit015                    = 28,
		Dwarf_ArmLDigit016                    = 29,
		Dwarf_ArmLDigit017                    = 30,
		Dwarf_ArmLDigit018                    = 31,
		Dwarf_ArmLDigit019                    = 32,
		Dwarf_ArmLDigit08                     = 33,
		Dwarf_ArmLDigit09                     = 34,
		Dwarf_ArmLDigit010                    = 35,
		Dwarf_ArmLDigit011                    = 36,
		Dwarf_ArmLDigit04                     = 37,
		Dwarf_ArmLDigit05                     = 38,
		Dwarf_ArmLDigit06                     = 39,
		Dwarf_ArmLDigit07                     = 40,
		Dwarf_HandL_Attach                    = 41,
		Dwarf_ShoulderL_Attach                = 42,
		Dwarf_ArmL1_Engineer_Liquid           = 43,
		Dwarf_ArmRShoulder                    = 44,
		Dwarf_ArmR1                           = 45,
		Dwarf_ArmR21                          = 46,
		Dwarf_ArmR22                          = 47,
		Dwarf_ArmRHand                        = 48,
		Dwarf_ArmRDigit01                     = 49,
		Dwarf_ArmRDigit02                     = 50,
		Dwarf_ArmRDigit03                     = 51,
		Dwarf_ArmRDigit012                    = 52,
		Dwarf_ArmRDigit013                    = 53,
		Dwarf_ArmRDigit014                    = 54,
		Dwarf_ArmRDigit015                    = 55,
		Dwarf_ArmRDigit016                    = 56,
		Dwarf_ArmRDigit017                    = 57,
		Dwarf_ArmRDigit018                    = 58,
		Dwarf_ArmRDigit019                    = 59,
		Dwarf_ArmRDigit08                     = 60,
		Dwarf_ArmRDigit09                     = 61,
		Dwarf_ArmRDigit010                    = 62,
		Dwarf_ArmRDigit011                    = 63,
		Dwarf_ArmRDigit04                     = 64,
		Dwarf_ArmRDigit05                     = 65,
		Dwarf_ArmRDigit06                     = 66,
		Dwarf_ArmRDigit07                     = 67,
		Dwarf_HandR_Attach                    = 68,
		Dwarf_ShoulderR_Attach                = 69,
		Dwarf_BackHigh_Attach                 = 70,
		Dwarf_BackHigh_Attach_Engineer_Pump01 = 71,
		Dwarf_BackHigh_Attach_Engineer_Pump02 = 72,
		Dwarf_BackMid_Attach                  = 73,
		Dwarf_BackHigh_Attach_Engineer_Tubes  = 74,
		Dwarf_BackLow_Attach                  = 75,
		Dwarf_HipF_Attach                     = 76,
		Dwarf_HipR_Attach                     = 77,
		Dwarf_HipL_Attach                     = 78,
		Dwarf_LegL1                           = 79,
		Dwarf_LegL2                           = 80,
		Dwarf_LegLHeel                        = 81,
		Dwarf_LegLToe                         = 82,
		Dwarf_LegR1                           = 83,
		Dwarf_LegR2                           = 84,
		Dwarf_LegRHeel                        = 85,
		Dwarf_LegRToe                         = 86,
		Dwarf_LegR1_Engineer_Liquid           = 87,
		Dwarf_ArmR1_Scout_Liquid              = 88,
		Dwarf_ArmRShulder_Scout_Liquid        = 89,
		Dwarf_BackHigh_Attach_Scout_Pump01    = 90,
		Dwarf_BackHigh_Attach_Scout_Pump02    = 91,
		Dwarf_BackHigh_Attach_Scout_Tubes     = 92,
		Dwarf_LegL1_Scout_Liquid001           = 93,
		Dwarf_ArmL1_Driller_Liquid            = 94,
		Dwarf_ArmR1_Driller_Liquid            = 95,
		Dwarf_BackHigh_Attach_Driller_Pump01  = 96,
		Dwarf_BackHigh_Attach_Driller_Pump02  = 97,
		Dwarf_BackHigh_Attach_Driller_Tubes   = 98,
		Dwarf_LegL1_Driller_Liquid            = 99,
		Dwarf_ATT_R_00                        = 100,
		Dwarf_ATT_R_01                        = 101,
		Dwarf_ATT_R_02                        = 102,
		Dwarf_ATT_L_00                        = 103,
		Dwarf_ATT_L_01                        = 104,
		Dwarf_ATT_L_02                        = 105,
		Dwarf_ATT_Mid_R_00                    = 106,
		Dwarf_ATT_Mid_R_01                    = 107,
		Dwarf_ATT_Mid_R_02                    = 108,
		Dwarf_ATT_Mid_L_00                    = 109,
		Dwarf_ATT_Mid_L_01                    = 110,
		Dwarf_ATT_Mid_L_02                    = 111,
		Dwarf_ATT_L_Belt_00                   = 112,
		Dwarf_ATT_Low_R_00                    = 113,
		Dwarf_ATT_Low_R_01                    = 114,
		Dwarf_ATT_Low_L_00                    = 115,
		Dwarf_ATT_Low_L_01                    = 116,
		Dwarf_ATT_Back_High_R                 = 117,
		Dwarf_ATT_Back_High_L                 = 118,
		Dwarf_ATT_Back_Mid_R                  = 119,
		Dwarf_ATT_Back_Mid_L                  = 120,
		Dwarf_ATT_Belt_L                      = 121,
		Dwarf_ArmL1_Gunner_Liquid             = 122,
		Dwarf_ArmR1_Gunner_Liquid             = 123,
		Dwarf_BackHigh_Attach_Gunner_Liquid01 = 124,
		Dwarf_BackHigh_Attach_Gunner_Liquid02 = 125,
		Dwarf_BackHigh_Attach_Gunner_Tubes    = 126,
		Dwarf_ATT_Back_R                      = 127,
		Dwarf_ATT_Back_L                      = 128,
		Dwarf_ATT_Upper_L                     = 129,
		Dwarf_Att_Upper_R                     = 130,
		Dwarf_ATT_Lower_R                     = 131,
		Dwarf_ATT_Lower_L                     = 132,
		Dwarf_Camera_Attach                   = 133
	};

	/**
	 * BoneSkeletalMesh SK_Bosco_Bartender.SK_Bosco_Bartender
	 */
	enum class EBone_SK_Bosco_Bartender : uint8_t
	{
		MainBody        = 0,
		Hatch_Cover_R   = 1,
		Hatch_Cover_L   = 2,
		Ear_R           = 3,
		Ear_L           = 4,
		Gun_Arm_L       = 5,
		Gun_Case_L      = 6,
		Gun_Barrel01_L  = 7,
		Gun_Barrel02_L  = 8,
		Gun_Arm_R       = 9,
		Gun_Case_R      = 10,
		Gun_Barrel01_R  = 11,
		Gun_Barrel02__R = 12,
		LowerBody       = 13,
		Arm01_L         = 14,
		Arm02_L         = 15,
		Arm03_L         = 16,
		Arm01_R         = 17,
		Arm02_R         = 18,
		Arm03_R         = 19,
		MidRiff         = 20,
		Thruster_L      = 21,
		Thruster_R      = 22,
		Butterfly       = 23,
		Gun_Drum_L      = 24,
		Gun_Drum_R      = 25,
		Hat             = 26,
		Plague          = 27,
		Vial            = 28,
		Tube_back       = 29,
		Tube_R          = 30,
		Tube_L          = 31,
		Elf_hat01       = 32,
		Elf_hat02       = 33,
		Elf_hat03       = 34,
		Elf_hat04       = 35,
		Elf_hat05       = 36,
		Bag             = 37,
		Belt_M          = 38,
		Belt_R          = 39,
		Belt_L          = 40,
		Headband_M      = 41,
		Headband01_R    = 42,
		Headband02_R    = 43,
		Headband03_R    = 44,
		Headband01_L    = 45,
		Headband02_L    = 46,
		Headband03_L    = 47
	};

	/**
	 * BoneSkeletalMesh SK_TipMachine.SK_TipMachine
	 */
	enum class EBone_SK_TipMachine : uint8_t
	{
		TipMachine_Root       = 0,
		TipMachine_Base       = 1,
		TipMachine_FlapL      = 2,
		TipMachine_FlapL_Note = 3,
		TipMachine_FlapR      = 4,
		TipMachine_FlapR_Note = 5,
		TipMachine_ArmR1      = 6,
		TipMachine_ArmR2      = 7,
		TipMachine_ArmR_Note  = 8,
		TipMachine_ArmL1      = 9,
		TipMachine_ArmL2      = 10,
		TipMachine_ArmL_Note  = 11,
		TipMachine_Screen     = 12,
		TipMachine_StalkL1    = 13,
		TipMachine_StalkL2    = 14,
		TipMachine_StalkL3    = 15,
		TipMachine_StalkL_Eye = 16,
		TipMachine_StalkR1    = 17,
		TipMachine_StalkR2    = 18,
		TipMachine_StalkR3    = 19,
		TipMachine_StalkR_Eye = 20,
		TipMachine_Lid        = 21,
		TipMachine_LidNote    = 22
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
