#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_DroppodRamp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FSD_classes.hpp"


namespace CG
{

// AnimBlueprintGeneratedClass ABP_DroppodRamp.ABP_DroppodRamp_C
// 0x03F0 (0x06B0 - 0x02C0)
class UABP_DroppodRamp_C final : public UMiningPodAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x02F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0320(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0348(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0370(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_1;                 // 0x0398(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x03E8(0x0030)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x0418(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x0468(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0498(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0518(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0548(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x05C8(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x05F8(0x00B0)()

public:
	void ExecuteUbergraph_ABP_DroppodRamp(int32 EntryPoint);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DroppodRamp_AnimGraphNode_TransitionResult_B178AD27426F23F1EE7CCFBBAE4B7D38();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DroppodRamp_AnimGraphNode_TransitionResult_D963559D4F7D338C844A7B8D11940AE4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DroppodRamp_AnimGraphNode_TransitionResult_4C3FEBDE4E195AF67C9CDBA7D7290FAA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DroppodRamp_AnimGraphNode_TransitionResult_41AF7652437F3C10561791958CD250B8();
	void AnimGraph(struct FPoseLink* Param_AnimGraph);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_DroppodRamp_C">();
	}
	static class UABP_DroppodRamp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_DroppodRamp_C>();
	}
};
static_assert(alignof(UABP_DroppodRamp_C) == 0x000010, "Wrong alignment on UABP_DroppodRamp_C");
static_assert(sizeof(UABP_DroppodRamp_C) == 0x0006B0, "Wrong size on UABP_DroppodRamp_C");
static_assert(offsetof(UABP_DroppodRamp_C, UberGraphFrame) == 0x0002C0, "Member 'UABP_DroppodRamp_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_Root) == 0x0002C8, "Member 'UABP_DroppodRamp_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_TransitionResult_3) == 0x0002F8, "Member 'UABP_DroppodRamp_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_TransitionResult_2) == 0x000320, "Member 'UABP_DroppodRamp_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_TransitionResult_1) == 0x000348, "Member 'UABP_DroppodRamp_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_TransitionResult) == 0x000370, "Member 'UABP_DroppodRamp_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_SequenceEvaluator_1) == 0x000398, "Member 'UABP_DroppodRamp_C::AnimGraphNode_SequenceEvaluator_1' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_StateResult_3) == 0x0003E8, "Member 'UABP_DroppodRamp_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_SequenceEvaluator) == 0x000418, "Member 'UABP_DroppodRamp_C::AnimGraphNode_SequenceEvaluator' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_StateResult_2) == 0x000468, "Member 'UABP_DroppodRamp_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_SequencePlayer_1) == 0x000498, "Member 'UABP_DroppodRamp_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_StateResult_1) == 0x000518, "Member 'UABP_DroppodRamp_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_SequencePlayer) == 0x000548, "Member 'UABP_DroppodRamp_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_StateResult) == 0x0005C8, "Member 'UABP_DroppodRamp_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_DroppodRamp_C, AnimGraphNode_StateMachine) == 0x0005F8, "Member 'UABP_DroppodRamp_C::AnimGraphNode_StateMachine' has a wrong offset!");

}

