#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AFE_Burning

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass AFE_Burning.AFE_Burning_C
// 0x0000 (0x0028 - 0x0028)
class UAFE_Burning_C final : public UPawnBurningUniqueAfflictionEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AFE_Burning_C">();
	}
	static class UAFE_Burning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAFE_Burning_C>();
	}
};
static_assert(alignof(UAFE_Burning_C) == 0x000008, "Wrong alignment on UAFE_Burning_C");
static_assert(sizeof(UAFE_Burning_C) == 0x000028, "Wrong size on UAFE_Burning_C");

}

