#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Basic_ScrollBarBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_structs.hpp"
#include "Slate_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass Basic_ScrollBarBox.Basic_ScrollBarBox_C
// 0x0048 (0x02A8 - 0x0260)
class UBasic_ScrollBarBox_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USizeBox*                               OptionalSizeBox;                                   // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             PutStuffHere;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_Items;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Always_Show_Scroll_Bars;                           // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	EOrientation                                  Orientation;                                       // 0x0281(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2C80[0x2];                                     // 0x0282(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSizeBoxSettings                       SizeSettings;                                      // 0x0284(0x0020)(Edit, BlueprintVisible, NoDestructor)
	float                                         ScrollbarThickness;                                // 0x02A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Basic_ScrollBarBox(int32 EntryPoint);
	void ScrollToChild(class UWidget* WidgetToFind, bool AnimateScroll, EDescendantScrollDestination ScrollDestination);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Basic_ScrollBarBox_C">();
	}
	static class UBasic_ScrollBarBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBasic_ScrollBarBox_C>();
	}
};
static_assert(alignof(UBasic_ScrollBarBox_C) == 0x000008, "Wrong alignment on UBasic_ScrollBarBox_C");
static_assert(sizeof(UBasic_ScrollBarBox_C) == 0x0002A8, "Wrong size on UBasic_ScrollBarBox_C");
static_assert(offsetof(UBasic_ScrollBarBox_C, UberGraphFrame) == 0x000260, "Member 'UBasic_ScrollBarBox_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, OptionalSizeBox) == 0x000268, "Member 'UBasic_ScrollBarBox_C::OptionalSizeBox' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, PutStuffHere) == 0x000270, "Member 'UBasic_ScrollBarBox_C::PutStuffHere' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, ScrollBox_Items) == 0x000278, "Member 'UBasic_ScrollBarBox_C::ScrollBox_Items' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, Always_Show_Scroll_Bars) == 0x000280, "Member 'UBasic_ScrollBarBox_C::Always_Show_Scroll_Bars' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, Orientation) == 0x000281, "Member 'UBasic_ScrollBarBox_C::Orientation' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, SizeSettings) == 0x000284, "Member 'UBasic_ScrollBarBox_C::SizeSettings' has a wrong offset!");
static_assert(offsetof(UBasic_ScrollBarBox_C, ScrollbarThickness) == 0x0002A4, "Member 'UBasic_ScrollBarBox_C::ScrollbarThickness' has a wrong offset!");

}

