#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Hologram_Base

#include "Basic.hpp"


namespace CG::Params
{

// Function BP_Hologram_Base.BP_Hologram_Base_C.ExecuteUbergraph_BP_Hologram_Base
// 0x0004 (0x0004 - 0x0000)
struct BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base) == 0x000004, "Wrong alignment on BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base");
static_assert(sizeof(BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base) == 0x000004, "Wrong size on BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base");
static_assert(offsetof(BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base, EntryPoint) == 0x000000, "Member 'BP_Hologram_Base_C_ExecuteUbergraph_BP_Hologram_Base::EntryPoint' has a wrong offset!");

// Function BP_Hologram_Base.BP_Hologram_Base_C.SetHologramMaterials
// 0x0028 (0x0028 - 0x0000)
struct BP_Hologram_Base_C_SetHologramMaterials final
{
public:
	TArray<class UMaterialInterface*>             InMaterials;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1554[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Hologram_Base_C_SetHologramMaterials) == 0x000008, "Wrong alignment on BP_Hologram_Base_C_SetHologramMaterials");
static_assert(sizeof(BP_Hologram_Base_C_SetHologramMaterials) == 0x000028, "Wrong size on BP_Hologram_Base_C_SetHologramMaterials");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, InMaterials) == 0x000000, "Member 'BP_Hologram_Base_C_SetHologramMaterials::InMaterials' has a wrong offset!");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'BP_Hologram_Base_C_SetHologramMaterials::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, CallFunc_Greater_IntInt_ReturnValue) == 0x000014, "Member 'BP_Hologram_Base_C_SetHologramMaterials::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, CallFunc_Array_LastIndex_ReturnValue) == 0x000018, "Member 'BP_Hologram_Base_C_SetHologramMaterials::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, CallFunc_Clamp_ReturnValue) == 0x00001C, "Member 'BP_Hologram_Base_C_SetHologramMaterials::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Hologram_Base_C_SetHologramMaterials, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_Hologram_Base_C_SetHologramMaterials::CallFunc_Array_Get_Item' has a wrong offset!");

}

