#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InfectedState

#include "Basic.hpp"

#include "BP_InfectedState_classes.hpp"
#include "BP_InfectedState_parameters.hpp"


namespace CG
{

// Function BP_InfectedState.BP_InfectedState_C.ExecuteUbergraph_BP_InfectedState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InfectedState_C::ExecuteUbergraph_BP_InfectedState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfectedState_C", "ExecuteUbergraph_BP_InfectedState");

	Params::BP_InfectedState_C_ExecuteUbergraph_BP_InfectedState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InfectedState.BP_InfectedState_C.StartDamage
// (BlueprintCallable, BlueprintEvent)

void UBP_InfectedState_C::StartDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfectedState_C", "StartDamage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InfectedState.BP_InfectedState_C.ReceiveStateExit
// (Event, Protected, BlueprintEvent)

void UBP_InfectedState_C::ReceiveStateExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfectedState_C", "ReceiveStateExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InfectedState.BP_InfectedState_C.ReceiveStateEnter
// (Event, Protected, BlueprintEvent)

void UBP_InfectedState_C::ReceiveStateEnter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfectedState_C", "ReceiveStateEnter");

	UObject::ProcessEvent(Func, nullptr);
}

}

