#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PassedOut

#include "Basic.hpp"

#include "BP_PassedOut_classes.hpp"
#include "BP_PassedOut_parameters.hpp"


namespace CG
{

// Function BP_PassedOut.BP_PassedOut_C.ExecuteUbergraph_BP_PassedOut
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PassedOut_C::ExecuteUbergraph_BP_PassedOut(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "ExecuteUbergraph_BP_PassedOut");

	Params::BP_PassedOut_C_ExecuteUbergraph_BP_PassedOut Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PassedOut.BP_PassedOut_C.ReceiveTeamPassedOut
// (Event, Protected, BlueprintEvent)

void UBP_PassedOut_C::ReceiveTeamPassedOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "ReceiveTeamPassedOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.Remove Drinking Mugs
// (BlueprintCallable, BlueprintEvent)

void UBP_PassedOut_C::Remove_Drinking_Mugs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "Remove Drinking Mugs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.Turn Off Juke Box
// (BlueprintCallable, BlueprintEvent)

void UBP_PassedOut_C::Turn_Off_Juke_Box()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "Turn Off Juke Box");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.ReceiveStateExit
// (Event, Protected, BlueprintEvent)

void UBP_PassedOut_C::ReceiveStateExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "ReceiveStateExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.ReceiveStateEnter
// (Event, Protected, BlueprintEvent)

void UBP_PassedOut_C::ReceiveStateEnter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "ReceiveStateEnter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.BeginFadeToBlack
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void UBP_PassedOut_C::BeginFadeToBlack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "BeginFadeToBlack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_PassedOut_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PassedOut.BP_PassedOut_C.AllPassedOut
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_AllPassedOut                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PassedOut_C::AllPassedOut(bool* Param_AllPassedOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassedOut_C", "AllPassedOut");

	Params::BP_PassedOut_C_AllPassedOut Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AllPassedOut != nullptr)
		*Param_AllPassedOut = Parms.Param_AllPassedOut;
}

}

