#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpacerigSpectator

#include "Basic.hpp"


namespace CG::Params
{

// Function BP_SpacerigSpectator.BP_SpacerigSpectator_C.ExecuteUbergraph_BP_SpacerigSpectator
// 0x0018 (0x0018 - 0x0000)
struct BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3766[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFSDGameState*                          CallFunc_GetFSDGameState_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator) == 0x000008, "Wrong alignment on BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator");
static_assert(sizeof(BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator) == 0x000018, "Wrong size on BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator");
static_assert(offsetof(BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator, EntryPoint) == 0x000000, "Member 'BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator, CallFunc_GetFSDGameState_ReturnValue) == 0x000008, "Member 'BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator::CallFunc_GetFSDGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator, CallFunc_IsLocallyControlled_ReturnValue) == 0x000010, "Member 'BP_SpacerigSpectator_C_ExecuteUbergraph_BP_SpacerigSpectator::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");

}

