#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WalkingState

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass BP_WalkingState.BP_WalkingState_C
// 0x0000 (0x0160 - 0x0160)
class UBP_WalkingState_C final : public UWalkingStateComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WalkingState_C">();
	}
	static class UBP_WalkingState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_WalkingState_C>();
	}
};
static_assert(alignof(UBP_WalkingState_C) == 0x000008, "Wrong alignment on UBP_WalkingState_C");
static_assert(sizeof(UBP_WalkingState_C) == 0x000160, "Wrong size on UBP_WalkingState_C");

}

