#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_ReachedDropship

#include "Basic.hpp"

#include "BTTask_ReachedDropship_classes.hpp"
#include "BTTask_ReachedDropship_parameters.hpp"


namespace CG
{

// Function BTTask_ReachedDropship.BTTask_ReachedDropship_C.ExecuteUbergraph_BTTask_ReachedDropship
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_ReachedDropship_C::ExecuteUbergraph_BTTask_ReachedDropship(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_ReachedDropship_C", "ExecuteUbergraph_BTTask_ReachedDropship");

	Params::BTTask_ReachedDropship_C_ExecuteUbergraph_BTTask_ReachedDropship Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_ReachedDropship.BTTask_ReachedDropship_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_ReachedDropship_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_ReachedDropship_C", "ReceiveExecuteAI");

	Params::BTTask_ReachedDropship_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}

}

