#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_Impact

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass CameraShake_Impact.CameraShake_Impact_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShake_Impact_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_Impact_C">();
	}
	static class UCameraShake_Impact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_Impact_C>();
	}
};
static_assert(alignof(UCameraShake_Impact_C) == 0x000010, "Wrong alignment on UCameraShake_Impact_C");
static_assert(sizeof(UCameraShake_Impact_C) == 0x0001B0, "Wrong size on UCameraShake_Impact_C");

}

