#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DE_BlackoutStout

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass DE_BlackoutStout.DE_BlackoutStout_C
// 0x0028 (0x00E8 - 0x00C0)
class UDE_BlackoutStout_C final : public UDrinkEffectComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          PEffect;                                           // 0x00C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_32ED[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               Particle_Effect;                                   // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SoundComp;                                         // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SoundCompDown;                                     // 0x00E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_DE_BlackoutStout(int32 EntryPoint);
	void OnStopEffect();
	void OnStartEffect(class APlayerCharacter* Character);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DE_BlackoutStout_C">();
	}
	static class UDE_BlackoutStout_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDE_BlackoutStout_C>();
	}
};
static_assert(alignof(UDE_BlackoutStout_C) == 0x000008, "Wrong alignment on UDE_BlackoutStout_C");
static_assert(sizeof(UDE_BlackoutStout_C) == 0x0000E8, "Wrong size on UDE_BlackoutStout_C");
static_assert(offsetof(UDE_BlackoutStout_C, UberGraphFrame) == 0x0000C0, "Member 'UDE_BlackoutStout_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UDE_BlackoutStout_C, PEffect) == 0x0000C8, "Member 'UDE_BlackoutStout_C::PEffect' has a wrong offset!");
static_assert(offsetof(UDE_BlackoutStout_C, Particle_Effect) == 0x0000D0, "Member 'UDE_BlackoutStout_C::Particle_Effect' has a wrong offset!");
static_assert(offsetof(UDE_BlackoutStout_C, SoundComp) == 0x0000D8, "Member 'UDE_BlackoutStout_C::SoundComp' has a wrong offset!");
static_assert(offsetof(UDE_BlackoutStout_C, SoundCompDown) == 0x0000E0, "Member 'UDE_BlackoutStout_C::SoundCompDown' has a wrong offset!");

}

