#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DNA_Escort_LongAverage

#include "Basic.hpp"

#include "FSD_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass DNA_Escort_LongAverage.DNA_Escort_LongAverage_C
// 0x0000 (0x0058 - 0x0058)
class UDNA_Escort_LongAverage_C final : public UEscortMissionDNA
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DNA_Escort_LongAverage_C">();
	}
	static class UDNA_Escort_LongAverage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDNA_Escort_LongAverage_C>();
	}
};
static_assert(alignof(UDNA_Escort_LongAverage_C) == 0x000008, "Wrong alignment on UDNA_Escort_LongAverage_C");
static_assert(sizeof(UDNA_Escort_LongAverage_C) == 0x000058, "Wrong size on UDNA_Escort_LongAverage_C");

}

