#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DropPod_EscapeSign

#include "Basic.hpp"

#include "DropPod_EscapeSign_classes.hpp"
#include "DropPod_EscapeSign_parameters.hpp"


namespace CG
{

// Function DropPod_EscapeSign.DropPod_EscapeSign_C.ExecuteUbergraph_DropPod_EscapeSign
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDropPod_EscapeSign_C::ExecuteUbergraph_DropPod_EscapeSign(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropPod_EscapeSign_C", "ExecuteUbergraph_DropPod_EscapeSign");

	Params::DropPod_EscapeSign_C_ExecuteUbergraph_DropPod_EscapeSign Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DropPod_EscapeSign.DropPod_EscapeSign_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UDropPod_EscapeSign_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropPod_EscapeSign_C", "PreConstruct");

	Params::DropPod_EscapeSign_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

