#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_FlareIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_classes.hpp"
#include "ENUM_MenuColors_structs.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_FlareIcon.HUD_FlareIcon_C
// 0x0028 (0x02A8 - 0x0280)
class UHUD_FlareIcon_C final : public UFSDUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Ping;                                              // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UProgressBar*                           FlareProduction;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInventoryComponent*                    Inventory;                                         // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Index_HUD_FlareIcon_C;                             // 0x02A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LastProgress;                                      // 0x02A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HUD_FlareIcon(int32 EntryPoint);
	void On_Flare_Production_Finished();
	void PreConstruct(bool IsDesignTime);
	void OnFlareCountChanged(int32 CurrentCount, class UInventoryComponent* Param_Inventory);
	void Init(int32 Param_Index, class UInventoryComponent* Param_Inventory);
	void SetProgress(float Percent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_FlareIcon_C">();
	}
	static class UHUD_FlareIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_FlareIcon_C>();
	}
};
static_assert(alignof(UHUD_FlareIcon_C) == 0x000008, "Wrong alignment on UHUD_FlareIcon_C");
static_assert(sizeof(UHUD_FlareIcon_C) == 0x0002A8, "Wrong size on UHUD_FlareIcon_C");
static_assert(offsetof(UHUD_FlareIcon_C, UberGraphFrame) == 0x000280, "Member 'UHUD_FlareIcon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_FlareIcon_C, Ping) == 0x000288, "Member 'UHUD_FlareIcon_C::Ping' has a wrong offset!");
static_assert(offsetof(UHUD_FlareIcon_C, FlareProduction) == 0x000290, "Member 'UHUD_FlareIcon_C::FlareProduction' has a wrong offset!");
static_assert(offsetof(UHUD_FlareIcon_C, Inventory) == 0x000298, "Member 'UHUD_FlareIcon_C::Inventory' has a wrong offset!");
static_assert(offsetof(UHUD_FlareIcon_C, Index_HUD_FlareIcon_C) == 0x0002A0, "Member 'UHUD_FlareIcon_C::Index_HUD_FlareIcon_C' has a wrong offset!");
static_assert(offsetof(UHUD_FlareIcon_C, LastProgress) == 0x0002A4, "Member 'UHUD_FlareIcon_C::LastProgress' has a wrong offset!");

}

