#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_GrenadeIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_classes.hpp"
#include "ENUM_MenuColors_structs.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_GrenadeIcon.HUD_GrenadeIcon_C
// 0x0018 (0x0298 - 0x0280)
class UHUD_GrenadeIcon_C final : public UFSDUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_17;                                          // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsOn;                                              // 0x0290(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_HUD_GrenadeIcon(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetOn(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_GrenadeIcon_C">();
	}
	static class UHUD_GrenadeIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_GrenadeIcon_C>();
	}
};
static_assert(alignof(UHUD_GrenadeIcon_C) == 0x000008, "Wrong alignment on UHUD_GrenadeIcon_C");
static_assert(sizeof(UHUD_GrenadeIcon_C) == 0x000298, "Wrong size on UHUD_GrenadeIcon_C");
static_assert(offsetof(UHUD_GrenadeIcon_C, UberGraphFrame) == 0x000280, "Member 'UHUD_GrenadeIcon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_GrenadeIcon_C, Image_17) == 0x000288, "Member 'UHUD_GrenadeIcon_C::Image_17' has a wrong offset!");
static_assert(offsetof(UHUD_GrenadeIcon_C, IsOn) == 0x000290, "Member 'UHUD_GrenadeIcon_C::IsOn' has a wrong offset!");

}

