#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_BossFight_BaseEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_structs.hpp"
#include "FSD_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_BossFight_BaseEntry.HUD_BossFight_BaseEntry_C
// 0x0020 (0x0290 - 0x0270)
class UHUD_BossFight_BaseEntry_C final : public UBossFightWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBossFight                             BossFightInfo;                                     // 0x0278(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, ContainsInstancedReference)

public:
	void ExecuteUbergraph_HUD_BossFight_BaseEntry(int32 EntryPoint);
	void Setup_Invulnerability();
	void OnFightRemoved(const TScriptInterface<class IBossFightInterface>& Param_BossFight);
	void Construct();
	void OnHealthChanged(float Health);
	void OnDisengaged();
	void OnDeath();
	void OnCanTakeDamageChanged(bool OutCanTakeDamage);
	void GetBossFight(struct FBossFight* Param_BossFight);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_BossFight_BaseEntry_C">();
	}
	static class UHUD_BossFight_BaseEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_BossFight_BaseEntry_C>();
	}
};
static_assert(alignof(UHUD_BossFight_BaseEntry_C) == 0x000008, "Wrong alignment on UHUD_BossFight_BaseEntry_C");
static_assert(sizeof(UHUD_BossFight_BaseEntry_C) == 0x000290, "Wrong size on UHUD_BossFight_BaseEntry_C");
static_assert(offsetof(UHUD_BossFight_BaseEntry_C, UberGraphFrame) == 0x000270, "Member 'UHUD_BossFight_BaseEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_BossFight_BaseEntry_C, BossFightInfo) == 0x000278, "Member 'UHUD_BossFight_BaseEntry_C::BossFightInfo' has a wrong offset!");

}

