#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_PlayerName_Label

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_PlayerName_Label.HUD_PlayerName_Label_C
// 0x0020 (0x0280 - 0x0260)
class UHUD_PlayerName_Label_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             DATA_PlayerName;                                   // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInvalidationBox*                       InvalidationBox_1;                                 // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_PlayerSpeaking_C*                   PlayerSpeakingIcon;                                // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HUD_PlayerName_Label(int32 EntryPoint);
	void RefreshIconVisibility();
	void SetupSpeakIcon();
	void PreConstruct(bool IsDesignTime);
	void OnPlayerNameChanged(const class FString& NewName);
	void Construct();
	void UpdateCharacterName();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_PlayerName_Label_C">();
	}
	static class UHUD_PlayerName_Label_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_PlayerName_Label_C>();
	}
};
static_assert(alignof(UHUD_PlayerName_Label_C) == 0x000008, "Wrong alignment on UHUD_PlayerName_Label_C");
static_assert(sizeof(UHUD_PlayerName_Label_C) == 0x000280, "Wrong size on UHUD_PlayerName_Label_C");
static_assert(offsetof(UHUD_PlayerName_Label_C, UberGraphFrame) == 0x000260, "Member 'UHUD_PlayerName_Label_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_PlayerName_Label_C, DATA_PlayerName) == 0x000268, "Member 'UHUD_PlayerName_Label_C::DATA_PlayerName' has a wrong offset!");
static_assert(offsetof(UHUD_PlayerName_Label_C, InvalidationBox_1) == 0x000270, "Member 'UHUD_PlayerName_Label_C::InvalidationBox_1' has a wrong offset!");
static_assert(offsetof(UHUD_PlayerName_Label_C, PlayerSpeakingIcon) == 0x000278, "Member 'UHUD_PlayerName_Label_C::PlayerSpeakingIcon' has a wrong offset!");

}

