#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_RadarPoint_Player

#include "Basic.hpp"

#include "HUD_RadarPoint_Player_classes.hpp"
#include "HUD_RadarPoint_Player_parameters.hpp"


namespace CG
{

// Function HUD_RadarPoint_Player.HUD_RadarPoint_Player_C.Deactivate
// (Public, BlueprintCallable, BlueprintEvent)

void UHUD_RadarPoint_Player_C::Deactivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_RadarPoint_Player_C", "Deactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_RadarPoint_Player.HUD_RadarPoint_Player_C.UpdatePoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   VerticalDist                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Destroy                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHUD_RadarPoint_Player_C::UpdatePoint(float Alpha, float VerticalDist, bool* Destroy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_RadarPoint_Player_C", "UpdatePoint");

	Params::HUD_RadarPoint_Player_C_UpdatePoint Parms{};

	Parms.Alpha = Alpha;
	Parms.VerticalDist = VerticalDist;

	UObject::ProcessEvent(Func, &Parms);

	if (Destroy != nullptr)
		*Destroy = Parms.Destroy;
}


// Function HUD_RadarPoint_Player.HUD_RadarPoint_Player_C.Get3dPosition
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Pos                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_RadarPoint_Player_C::Get3dPosition(struct FVector* Pos)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_RadarPoint_Player_C", "Get3dPosition");

	Params::HUD_RadarPoint_Player_C_Get3dPosition Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Pos != nullptr)
		*Pos = std::move(Parms.Pos);
}


// Function HUD_RadarPoint_Player.HUD_RadarPoint_Player_C.InitPoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class URadarPointComponent*             RadarComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHUD_RadarPoint_Player_C::InitPoint(class URadarPointComponent* RadarComponent, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_RadarPoint_Player_C", "InitPoint");

	Params::HUD_RadarPoint_Player_C_InitPoint Parms{};

	Parms.RadarComponent = RadarComponent;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}

}

