#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_CharacterBeerLabel

#include "Basic.hpp"


namespace CG::Params
{

// Function HUD_CharacterBeerLabel.HUD_CharacterBeerLabel_C.ExecuteUbergraph_HUD_CharacterBeerLabel
// 0x0020 (0x0020 - 0x0000)
struct HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33E7[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel) == 0x000008, "Wrong alignment on HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel");
static_assert(sizeof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel) == 0x000020, "Wrong size on HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel");
static_assert(offsetof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel, EntryPoint) == 0x000000, "Member 'HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel::EntryPoint' has a wrong offset!");
static_assert(offsetof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel, K2Node_Event_IsDesignTime) == 0x000004, "Member 'HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000008, "Member 'HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel, K2Node_DynamicCast_AsTexture_2D) == 0x000010, "Member 'HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'HUD_CharacterBeerLabel_C_ExecuteUbergraph_HUD_CharacterBeerLabel::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function HUD_CharacterBeerLabel.HUD_CharacterBeerLabel_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct HUD_CharacterBeerLabel_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HUD_CharacterBeerLabel_C_PreConstruct) == 0x000001, "Wrong alignment on HUD_CharacterBeerLabel_C_PreConstruct");
static_assert(sizeof(HUD_CharacterBeerLabel_C_PreConstruct) == 0x000001, "Wrong size on HUD_CharacterBeerLabel_C_PreConstruct");
static_assert(offsetof(HUD_CharacterBeerLabel_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'HUD_CharacterBeerLabel_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

