#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_Chat

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_Chat.HUD_Chat_C
// 0x0088 (0x02E8 - 0x0260)
class UHUD_Chat_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       BackgroundFade;                                    // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                Border_0;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ChatBackground;                                    // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ChatBar;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           ChatMessages;                                      // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUD_ChatLine_C*                        HUD_ChatLine;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUD_ChatLine_C*                        HUD_ChatLine_1;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUD_ChatLine_C*                        HUD_ChatLine_2;                                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       NewChatEdit;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FadeTime;                                          // 0x02B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxLines;                                          // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InLoadMenu;                                        // 0x02BC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	EChatSenderType                               SenderType;                                        // 0x02BD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1033[0x2];                                     // 0x02BE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UEditableTextBox*                       OutsiteChatbox;                                    // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UEditableTextBox*                       InputChatBox;                                      // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MinLinesConst;                                     // 0x02D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxLinesConst;                                     // 0x02D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsChatOpen;                                        // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanChatBeOpened;                                   // 0x02D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1034[0x6];                                     // 0x02DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           ConsoleChatStartDelay;                             // 0x02E0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HUD_Chat(int32 EntryPoint);
	void Destruct();
	void ChatClosedCooldown();
	void ChatOpenCooldown();
	void PlatformDependentClose();
	void OnFontSizeChange(int32 NewValue);
	void Construct();
	void BndEvt__NewChatEdit_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text);
	void NewMesssage(const struct FFSDChatMessage& Message);
	void BndEvt__NewChatEdit_K2Node_ComponentBoundEvent_19_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void SendChatMessage(const class FText& InText, ETextCommit CommitMethod);
	void BndEvt__OutsiteChatbox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__OutsiteChatbox_K2Node_ComponentBoundEvent_0_OnEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void OnBackgroundFadeFinished();
	void CloseChat();
	void PreConstruct(bool IsDesignTime);
	void OnMessageHidden_Event();
	void Add_Chat_Message(const struct FFSDChatMessage& Msg);
	void Update_Chat_Background();
	void OnOpenChat();
	void BeginChat();
	void OpenChat();
	void GetSenderType(EChatSenderType* Param_SenderType);
	void UpdateChatMessages(bool ResetAge);
	void SetMaxLinesFromFontSize(int32 FontSize);
	void FilterProfanityMessage(const class FString& MessageToFilter, class FString* OutMessage);
	void FilterMessage(const struct FFSDChatMessage& InMessage, struct FFSDChatMessage* FilteredMessage);
	void FilterBlockedUserMessage(const struct FFSDChatMessage& InMessage, EChatMessageType* FilteredMessageType, class FString* FilteredMessage);

	void IsStringNotEmpty(const class FString& String, bool* IsEmpty) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_Chat_C">();
	}
	static class UHUD_Chat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_Chat_C>();
	}
};
static_assert(alignof(UHUD_Chat_C) == 0x000008, "Wrong alignment on UHUD_Chat_C");
static_assert(sizeof(UHUD_Chat_C) == 0x0002E8, "Wrong size on UHUD_Chat_C");
static_assert(offsetof(UHUD_Chat_C, UberGraphFrame) == 0x000260, "Member 'UHUD_Chat_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, BackgroundFade) == 0x000268, "Member 'UHUD_Chat_C::BackgroundFade' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, Border_0) == 0x000270, "Member 'UHUD_Chat_C::Border_0' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, ChatBackground) == 0x000278, "Member 'UHUD_Chat_C::ChatBackground' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, ChatBar) == 0x000280, "Member 'UHUD_Chat_C::ChatBar' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, ChatMessages) == 0x000288, "Member 'UHUD_Chat_C::ChatMessages' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, HUD_ChatLine) == 0x000290, "Member 'UHUD_Chat_C::HUD_ChatLine' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, HUD_ChatLine_1) == 0x000298, "Member 'UHUD_Chat_C::HUD_ChatLine_1' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, HUD_ChatLine_2) == 0x0002A0, "Member 'UHUD_Chat_C::HUD_ChatLine_2' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, NewChatEdit) == 0x0002A8, "Member 'UHUD_Chat_C::NewChatEdit' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, Duration) == 0x0002B0, "Member 'UHUD_Chat_C::Duration' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, FadeTime) == 0x0002B4, "Member 'UHUD_Chat_C::FadeTime' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, MaxLines) == 0x0002B8, "Member 'UHUD_Chat_C::MaxLines' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, InLoadMenu) == 0x0002BC, "Member 'UHUD_Chat_C::InLoadMenu' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, SenderType) == 0x0002BD, "Member 'UHUD_Chat_C::SenderType' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, OutsiteChatbox) == 0x0002C0, "Member 'UHUD_Chat_C::OutsiteChatbox' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, InputChatBox) == 0x0002C8, "Member 'UHUD_Chat_C::InputChatBox' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, MinLinesConst) == 0x0002D0, "Member 'UHUD_Chat_C::MinLinesConst' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, MaxLinesConst) == 0x0002D4, "Member 'UHUD_Chat_C::MaxLinesConst' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, IsChatOpen) == 0x0002D8, "Member 'UHUD_Chat_C::IsChatOpen' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, CanChatBeOpened) == 0x0002D9, "Member 'UHUD_Chat_C::CanChatBeOpened' has a wrong offset!");
static_assert(offsetof(UHUD_Chat_C, ConsoleChatStartDelay) == 0x0002E0, "Member 'UHUD_Chat_C::ConsoleChatStartDelay' has a wrong offset!");

}

