#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_ItemWheel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_structs.hpp"
#include "FSD_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass HUD_ItemWheel.HUD_ItemWheel_C
// 0x0078 (0x0330 - 0x02B8)
class UHUD_ItemWheel_C final : public UItemsBar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeInOut;                                         // 0x02C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_AdvancedLabel_C*                    Dpaddown;                                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_AdvancedLabel_C*                    Dpadleft;                                          // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_AdvancedLabel_C*                    Dpadright;                                         // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_AdvancedLabel_C*                    Dpadup;                                            // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        ImageSwitcher;                                     // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ItemHolder0;                                       // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ItemHolder1;                                       // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ItemHolder2;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ItemHolder3;                                       // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               SupplyItemHolder;                                  // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UOverlay*>                       ItemHolders;                                       // 0x0318(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	float                                         VisibleDuration;                                   // 0x0328(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WidgetVisible;                                     // 0x032C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_HUD_ItemWheel(int32 EntryPoint);
	void OnFadeInOutStarted();
	void OnFadeInOutFinished();
	void OnSupplyItemEquipped(class UItemsBarIcon* ItemIcon);
	void OnSupplyItemUnequipped(class UItemsBarIcon* ItemIcon);
	void OnSupplyItemAdded(class UItemsBarIcon* ItemIcon);
	void OnItemClicked();
	void Show();
	void OnInputSourceChanged(EFSDInputSource InputSource);
	void Construct();
	void OnClear();
	void AddIcon(class UItemsBarIcon* Icon, int32 Param_Index);
	void OnItemEquipped(class UItemsBarIcon* ItemIcon);
	void PreConstruct(bool IsDesignTime);
	void OnItemAdded(class UItemsBarIcon* ItemIcon);
	void SwapUpperItems(class UWidget* Unselected, class UWidget* Selected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HUD_ItemWheel_C">();
	}
	static class UHUD_ItemWheel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUD_ItemWheel_C>();
	}
};
static_assert(alignof(UHUD_ItemWheel_C) == 0x000008, "Wrong alignment on UHUD_ItemWheel_C");
static_assert(sizeof(UHUD_ItemWheel_C) == 0x000330, "Wrong size on UHUD_ItemWheel_C");
static_assert(offsetof(UHUD_ItemWheel_C, UberGraphFrame) == 0x0002B8, "Member 'UHUD_ItemWheel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, FadeInOut) == 0x0002C0, "Member 'UHUD_ItemWheel_C::FadeInOut' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, Dpaddown) == 0x0002C8, "Member 'UHUD_ItemWheel_C::Dpaddown' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, Dpadleft) == 0x0002D0, "Member 'UHUD_ItemWheel_C::Dpadleft' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, Dpadright) == 0x0002D8, "Member 'UHUD_ItemWheel_C::Dpadright' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, Dpadup) == 0x0002E0, "Member 'UHUD_ItemWheel_C::Dpadup' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ImageSwitcher) == 0x0002E8, "Member 'UHUD_ItemWheel_C::ImageSwitcher' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ItemHolder0) == 0x0002F0, "Member 'UHUD_ItemWheel_C::ItemHolder0' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ItemHolder1) == 0x0002F8, "Member 'UHUD_ItemWheel_C::ItemHolder1' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ItemHolder2) == 0x000300, "Member 'UHUD_ItemWheel_C::ItemHolder2' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ItemHolder3) == 0x000308, "Member 'UHUD_ItemWheel_C::ItemHolder3' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, SupplyItemHolder) == 0x000310, "Member 'UHUD_ItemWheel_C::SupplyItemHolder' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, ItemHolders) == 0x000318, "Member 'UHUD_ItemWheel_C::ItemHolders' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, VisibleDuration) == 0x000328, "Member 'UHUD_ItemWheel_C::VisibleDuration' has a wrong offset!");
static_assert(offsetof(UHUD_ItemWheel_C, WidgetVisible) == 0x00032C, "Member 'UHUD_ItemWheel_C::WidgetVisible' has a wrong offset!");

}

