#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_BarGlass_Item_PropHunt

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ITM_BarGlass_Item_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass ITM_BarGlass_Item_PropHunt.ITM_BarGlass_Item_PropHunt_C
// 0x0008 (0x0440 - 0x0438)
class AITM_BarGlass_Item_PropHunt_C final : public AITM_BarGlass_Item_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ITM_BarGlass_Item_PropHunt_C;       // 0x0438(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ITM_BarGlass_Item_PropHunt(int32 EntryPoint);
	void ReceiveConsumed();
	void ReceiveBeginPlay();
	void Refresh();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITM_BarGlass_Item_PropHunt_C">();
	}
	static class AITM_BarGlass_Item_PropHunt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AITM_BarGlass_Item_PropHunt_C>();
	}
};
static_assert(alignof(AITM_BarGlass_Item_PropHunt_C) == 0x000008, "Wrong alignment on AITM_BarGlass_Item_PropHunt_C");
static_assert(sizeof(AITM_BarGlass_Item_PropHunt_C) == 0x000440, "Wrong size on AITM_BarGlass_Item_PropHunt_C");
static_assert(offsetof(AITM_BarGlass_Item_PropHunt_C, UberGraphFrame_ITM_BarGlass_Item_PropHunt_C) == 0x000438, "Member 'AITM_BarGlass_Item_PropHunt_C::UberGraphFrame_ITM_BarGlass_Item_PropHunt_C' has a wrong offset!");

}

