#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_SeasonChallengeIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass ITM_SeasonChallengeIcon.ITM_SeasonChallengeIcon_C
// 0x0020 (0x0280 - 0x0260)
class UITM_SeasonChallengeIcon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Glow;                                              // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Icon_Glow;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Challenge;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ITM_SeasonChallengeIcon(int32 EntryPoint);
	void SetIconHovered(bool InHovered, class UTexture2D* Icon, const struct FLinearColor& Color);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITM_SeasonChallengeIcon_C">();
	}
	static class UITM_SeasonChallengeIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_SeasonChallengeIcon_C>();
	}
};
static_assert(alignof(UITM_SeasonChallengeIcon_C) == 0x000008, "Wrong alignment on UITM_SeasonChallengeIcon_C");
static_assert(sizeof(UITM_SeasonChallengeIcon_C) == 0x000280, "Wrong size on UITM_SeasonChallengeIcon_C");
static_assert(offsetof(UITM_SeasonChallengeIcon_C, UberGraphFrame) == 0x000260, "Member 'UITM_SeasonChallengeIcon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UITM_SeasonChallengeIcon_C, Glow) == 0x000268, "Member 'UITM_SeasonChallengeIcon_C::Glow' has a wrong offset!");
static_assert(offsetof(UITM_SeasonChallengeIcon_C, Icon_Glow) == 0x000270, "Member 'UITM_SeasonChallengeIcon_C::Icon_Glow' has a wrong offset!");
static_assert(offsetof(UITM_SeasonChallengeIcon_C, Image_Challenge) == 0x000278, "Member 'UITM_SeasonChallengeIcon_C::Image_Challenge' has a wrong offset!");

}

