#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_CommunityGoal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FSD_structs.hpp"
#include "FSD_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass ITM_CommunityGoal.ITM_CommunityGoal_C
// 0x03A0 (0x0620 - 0x0280)
class UITM_CommunityGoal_C final : public UFSDUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                BackgroundButton;                                  // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             BronzeGoalNumber;                                  // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Goal_0;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Goal_1;                                     // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Goal_2;                                     // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              CheckBox_Goal_Bronze;                              // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              CheckBox_Goal_Gold;                                // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              CheckBox_Goal_Silver;                              // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               CurrentSizebox;                                    // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CurrentTextBlock;                                  // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                FactionIconToolTip;                                // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             GoalText;                                          // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             GoldGoalNumber;                                    // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bronze;                                      // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Gold;                                        // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Silver;                                      // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_0;                                     // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_1;                                     // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_2;                                     // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SilverGoalNumber;                                  // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TitleText;                                         // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GradientMasked_Image_C*             UI_GradientMasked_Image;                           // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ImageTinted_C*                      UI_ImageTinted;                                    // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ImageTinted_C*                      UI_ImageTinted_267;                                // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Title;                                             // 0x0350(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	int32                                         TitleSize;                                         // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_3D4F[0x4];                                     // 0x036C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            IconImage;                                         // 0x0370(0x0088)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FProgressBarStyle                      BarStyle;                                          // 0x03F8(0x01A0)(Edit, BlueprintVisible, ExposeOnSpawn)
	float                                         Progress0;                                         // 0x0598(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Progress1;                                         // 0x059C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Progress2;                                         // 0x05A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           FillColor;                                         // 0x05A4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         AnimTime;                                          // 0x05B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TotalAnimTime;                                     // 0x05B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D50[0x4];                                     // 0x05BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CurrentGoalID;                                     // 0x05C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UCommunityGoal*                         CurrentGoal;                                       // 0x05D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurrentValue;                                      // 0x05D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentMembers;                                    // 0x05DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommunityGoalFaction*                  Faction;                                           // 0x05E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsShowingCurrentPlayerFaction;                     // 0x05E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D51[0x7];                                     // 0x05E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             HoverStarted;                                      // 0x05F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             HoverEnded;                                        // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UITM_CommunityGoalRewardToolTip_C*      ToolTip;                                           // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UITM_FactionToolTip_C*                  FactionToolTip;                                    // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void HoverStarted__DelegateSignature(class UCommunityGoalFaction* Param_Faction, class UCommunityGoal* Goal);
	void HoverEnded__DelegateSignature();
	void ExecuteUbergraph_ITM_CommunityGoal(int32 EntryPoint);
	void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void CheckFaction();
	void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_58_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
	void SetGoal(const class FString& GoalID, float GoalValue, int32 Members, bool ForceRefresh);
	void PreConstruct(bool IsDesignTime);
	void SetCommunityGoal(const class FText& Goal, float Bronze_Progress, float Silver_Progress, float Gold_Progress);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void ResetAnim();
	void SetFaction(class UCommunityGoalFaction* Param_Faction);
	void UpdateIcon();
	void UpdateTitle();
	void DoToolTip(class UWidget* ToolTipTarget, int32 Tier);
	void DoFactionToolTip();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITM_CommunityGoal_C">();
	}
	static class UITM_CommunityGoal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_CommunityGoal_C>();
	}
};
static_assert(alignof(UITM_CommunityGoal_C) == 0x000008, "Wrong alignment on UITM_CommunityGoal_C");
static_assert(sizeof(UITM_CommunityGoal_C) == 0x000620, "Wrong size on UITM_CommunityGoal_C");
static_assert(offsetof(UITM_CommunityGoal_C, UberGraphFrame) == 0x000280, "Member 'UITM_CommunityGoal_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, BackgroundButton) == 0x000288, "Member 'UITM_CommunityGoal_C::BackgroundButton' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, BronzeGoalNumber) == 0x000290, "Member 'UITM_CommunityGoal_C::BronzeGoalNumber' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Button_Goal_0) == 0x000298, "Member 'UITM_CommunityGoal_C::Button_Goal_0' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Button_Goal_1) == 0x0002A0, "Member 'UITM_CommunityGoal_C::Button_Goal_1' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Button_Goal_2) == 0x0002A8, "Member 'UITM_CommunityGoal_C::Button_Goal_2' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CheckBox_Goal_Bronze) == 0x0002B0, "Member 'UITM_CommunityGoal_C::CheckBox_Goal_Bronze' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CheckBox_Goal_Gold) == 0x0002B8, "Member 'UITM_CommunityGoal_C::CheckBox_Goal_Gold' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CheckBox_Goal_Silver) == 0x0002C0, "Member 'UITM_CommunityGoal_C::CheckBox_Goal_Silver' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentSizebox) == 0x0002C8, "Member 'UITM_CommunityGoal_C::CurrentSizebox' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentTextBlock) == 0x0002D0, "Member 'UITM_CommunityGoal_C::CurrentTextBlock' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, FactionIconToolTip) == 0x0002D8, "Member 'UITM_CommunityGoal_C::FactionIconToolTip' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, GoalText) == 0x0002E0, "Member 'UITM_CommunityGoal_C::GoalText' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, GoldGoalNumber) == 0x0002E8, "Member 'UITM_CommunityGoal_C::GoldGoalNumber' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Icon) == 0x0002F0, "Member 'UITM_CommunityGoal_C::Icon' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Image_Bronze) == 0x0002F8, "Member 'UITM_CommunityGoal_C::Image_Bronze' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Image_Gold) == 0x000300, "Member 'UITM_CommunityGoal_C::Image_Gold' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Image_Silver) == 0x000308, "Member 'UITM_CommunityGoal_C::Image_Silver' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, ProgressBar_0) == 0x000310, "Member 'UITM_CommunityGoal_C::ProgressBar_0' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, ProgressBar_1) == 0x000318, "Member 'UITM_CommunityGoal_C::ProgressBar_1' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, ProgressBar_2) == 0x000320, "Member 'UITM_CommunityGoal_C::ProgressBar_2' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, SilverGoalNumber) == 0x000328, "Member 'UITM_CommunityGoal_C::SilverGoalNumber' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, TitleText) == 0x000330, "Member 'UITM_CommunityGoal_C::TitleText' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, UI_GradientMasked_Image) == 0x000338, "Member 'UITM_CommunityGoal_C::UI_GradientMasked_Image' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, UI_ImageTinted) == 0x000340, "Member 'UITM_CommunityGoal_C::UI_ImageTinted' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, UI_ImageTinted_267) == 0x000348, "Member 'UITM_CommunityGoal_C::UI_ImageTinted_267' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Title) == 0x000350, "Member 'UITM_CommunityGoal_C::Title' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, TitleSize) == 0x000368, "Member 'UITM_CommunityGoal_C::TitleSize' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, IconImage) == 0x000370, "Member 'UITM_CommunityGoal_C::IconImage' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, BarStyle) == 0x0003F8, "Member 'UITM_CommunityGoal_C::BarStyle' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Progress0) == 0x000598, "Member 'UITM_CommunityGoal_C::Progress0' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Progress1) == 0x00059C, "Member 'UITM_CommunityGoal_C::Progress1' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Progress2) == 0x0005A0, "Member 'UITM_CommunityGoal_C::Progress2' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, FillColor) == 0x0005A4, "Member 'UITM_CommunityGoal_C::FillColor' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, AnimTime) == 0x0005B4, "Member 'UITM_CommunityGoal_C::AnimTime' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, TotalAnimTime) == 0x0005B8, "Member 'UITM_CommunityGoal_C::TotalAnimTime' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentGoalID) == 0x0005C0, "Member 'UITM_CommunityGoal_C::CurrentGoalID' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentGoal) == 0x0005D0, "Member 'UITM_CommunityGoal_C::CurrentGoal' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentValue) == 0x0005D8, "Member 'UITM_CommunityGoal_C::CurrentValue' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, CurrentMembers) == 0x0005DC, "Member 'UITM_CommunityGoal_C::CurrentMembers' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, Faction) == 0x0005E0, "Member 'UITM_CommunityGoal_C::Faction' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, IsShowingCurrentPlayerFaction) == 0x0005E8, "Member 'UITM_CommunityGoal_C::IsShowingCurrentPlayerFaction' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, HoverStarted) == 0x0005F0, "Member 'UITM_CommunityGoal_C::HoverStarted' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, HoverEnded) == 0x000600, "Member 'UITM_CommunityGoal_C::HoverEnded' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, ToolTip) == 0x000610, "Member 'UITM_CommunityGoal_C::ToolTip' has a wrong offset!");
static_assert(offsetof(UITM_CommunityGoal_C, FactionToolTip) == 0x000618, "Member 'UITM_CommunityGoal_C::FactionToolTip' has a wrong offset!");

}

