#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_ItemUnlockedIcon

#include "Basic.hpp"


namespace CG::Params
{

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.ExecuteUbergraph_ITM_ItemUnlockedIcon
// 0x0030 (0x0030 - 0x0000)
struct ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_358E[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_358F[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon) == 0x000008, "Wrong alignment on ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon) == 0x000030, "Wrong size on ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, EntryPoint) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::EntryPoint' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000004, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, CallFunc_Not_PreBool_ReturnValue) == 0x000018, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, CallFunc_PlayAnimation_ReturnValue) == 0x000020, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, CallFunc_IsVisible_ReturnValue) == 0x000028, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon, CallFunc_BooleanAND_ReturnValue) == 0x000029, "Member 'ITM_ItemUnlockedIcon_C_ExecuteUbergraph_ITM_ItemUnlockedIcon::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.SetItemIDArray
// 0x0018 (0x0018 - 0x0000)
struct ITM_ItemUnlockedIcon_C_SetItemIDArray final
{
public:
	TArray<class UObject*>                        ObjectsWithID;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          Param_MatchChildNotifications;                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CheckItemUINotification_HasNotification;  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_SetItemIDArray) == 0x000008, "Wrong alignment on ITM_ItemUnlockedIcon_C_SetItemIDArray");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_SetItemIDArray) == 0x000018, "Wrong size on ITM_ItemUnlockedIcon_C_SetItemIDArray");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_SetItemIDArray, ObjectsWithID) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_SetItemIDArray::ObjectsWithID' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_SetItemIDArray, Param_MatchChildNotifications) == 0x000010, "Member 'ITM_ItemUnlockedIcon_C_SetItemIDArray::Param_MatchChildNotifications' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_SetItemIDArray, CallFunc_CheckItemUINotification_HasNotification) == 0x000011, "Member 'ITM_ItemUnlockedIcon_C_SetItemIDArray::CallFunc_CheckItemUINotification_HasNotification' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.RemoveNotification
// 0x0001 (0x0001 - 0x0000)
struct ITM_ItemUnlockedIcon_C_RemoveNotification final
{
public:
	bool                                          CallFunc_CheckItemUINotification_HasNotification;  // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_RemoveNotification) == 0x000001, "Wrong alignment on ITM_ItemUnlockedIcon_C_RemoveNotification");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_RemoveNotification) == 0x000001, "Wrong size on ITM_ItemUnlockedIcon_C_RemoveNotification");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_RemoveNotification, CallFunc_CheckItemUINotification_HasNotification) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_RemoveNotification::CallFunc_CheckItemUINotification_HasNotification' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.AddChildNotification
// 0x0030 (0x0030 - 0x0000)
struct ITM_ItemUnlockedIcon_C_AddChildNotification final
{
public:
	class UITM_ItemUnlockedIcon_C*                ChildIcon;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_AddChildNotification) == 0x000008, "Wrong alignment on ITM_ItemUnlockedIcon_C_AddChildNotification");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_AddChildNotification) == 0x000030, "Wrong size on ITM_ItemUnlockedIcon_C_AddChildNotification");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_AddChildNotification, ChildIcon) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_AddChildNotification::ChildIcon' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_AddChildNotification, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'ITM_ItemUnlockedIcon_C_AddChildNotification::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_AddChildNotification, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'ITM_ItemUnlockedIcon_C_AddChildNotification::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_AddChildNotification, CallFunc_Array_AddUnique_ReturnValue) == 0x000028, "Member 'ITM_ItemUnlockedIcon_C_AddChildNotification::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_AddChildNotification, CallFunc_NotEqual_IntInt_ReturnValue) == 0x00002C, "Member 'ITM_ItemUnlockedIcon_C_AddChildNotification::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.ChildNotificationChanged
// 0x0028 (0x0028 - 0x0000)
struct ITM_ItemUnlockedIcon_C_ChildNotificationChanged final
{
public:
	bool                                          OldHasNotification;                                // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3590[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3591[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UITM_ItemUnlockedIcon_C*                CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged) == 0x000008, "Wrong alignment on ITM_ItemUnlockedIcon_C_ChildNotificationChanged");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged) == 0x000028, "Wrong size on ITM_ItemUnlockedIcon_C_ChildNotificationChanged");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, OldHasNotification) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::OldHasNotification' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, Temp_int_Array_Index_Variable) == 0x000004, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, CallFunc_Array_Get_Item) == 0x000018, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ChildNotificationChanged, CallFunc_Less_IntInt_ReturnValue) == 0x000020, "Member 'ITM_ItemUnlockedIcon_C_ChildNotificationChanged::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.ClearChildren
// 0x0020 (0x0020 - 0x0000)
struct ITM_ItemUnlockedIcon_C_ClearChildren final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3592[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UITM_ItemUnlockedIcon_C*                CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_ClearChildren) == 0x000008, "Wrong alignment on ITM_ItemUnlockedIcon_C_ClearChildren");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_ClearChildren) == 0x000020, "Wrong size on ITM_ItemUnlockedIcon_C_ClearChildren");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, Temp_int_Array_Index_Variable) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, CallFunc_Array_Get_Item) == 0x000010, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_ClearChildren, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'ITM_ItemUnlockedIcon_C_ClearChildren::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function ITM_ItemUnlockedIcon.ITM_ItemUnlockedIcon_C.Refresh
// 0x0003 (0x0003 - 0x0000)
struct ITM_ItemUnlockedIcon_C_Refresh final
{
public:
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CheckItemUINotification_HasNotification;  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_ItemUnlockedIcon_C_Refresh) == 0x000001, "Wrong alignment on ITM_ItemUnlockedIcon_C_Refresh");
static_assert(sizeof(ITM_ItemUnlockedIcon_C_Refresh) == 0x000003, "Wrong size on ITM_ItemUnlockedIcon_C_Refresh");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_Refresh, CallFunc_Not_PreBool_ReturnValue) == 0x000000, "Member 'ITM_ItemUnlockedIcon_C_Refresh::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_Refresh, CallFunc_CheckItemUINotification_HasNotification) == 0x000001, "Member 'ITM_ItemUnlockedIcon_C_Refresh::CallFunc_CheckItemUINotification_HasNotification' has a wrong offset!");
static_assert(offsetof(ITM_ItemUnlockedIcon_C_Refresh, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x000002, "Member 'ITM_ItemUnlockedIcon_C_Refresh::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");

}

