#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_ResetFaction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass ITM_ResetFaction.ITM_ResetFaction_C
// 0x0080 (0x02E0 - 0x0260)
class UITM_ResetFaction_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_ButtonScalable_C*                Basic_ButtonScalable;                              // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Menu_MinimalWindow_C*            Basic_Menu_MinimalWindow;                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CostTextBlock;                                     // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               CurrentSizebox;                                    // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FactionLogo;                                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             FactionNameTextBlock;                              // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_429;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GradientMasked_Image_C*             UI_GradientMasked_Image;                           // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ImageTinted_C*                      UI_ImageTinted;                                    // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommunityGoalFaction*                  CurrentFaction;                                    // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Cost;                                              // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_37AB[0x4];                                     // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             CheckState;                                        // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UCommunityGoalFaction*>          FactionArray;                                      // 0x02D0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)

public:
	void CheckState__DelegateSignature();
	void ExecuteUbergraph_ITM_ResetFaction(int32 EntryPoint);
	void OnFactionSwitch(bool Changed);
	void BndEvt__Basic_ButtonScalable_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void Set_Faction(class UCommunityGoalFaction* Faction);
	void PreConstruct(bool IsDesignTime);
	int32 CurrentFactionID();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITM_ResetFaction_C">();
	}
	static class UITM_ResetFaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_ResetFaction_C>();
	}
};
static_assert(alignof(UITM_ResetFaction_C) == 0x000008, "Wrong alignment on UITM_ResetFaction_C");
static_assert(sizeof(UITM_ResetFaction_C) == 0x0002E0, "Wrong size on UITM_ResetFaction_C");
static_assert(offsetof(UITM_ResetFaction_C, UberGraphFrame) == 0x000260, "Member 'UITM_ResetFaction_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, Basic_ButtonScalable) == 0x000268, "Member 'UITM_ResetFaction_C::Basic_ButtonScalable' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, Basic_Menu_MinimalWindow) == 0x000270, "Member 'UITM_ResetFaction_C::Basic_Menu_MinimalWindow' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, CostTextBlock) == 0x000278, "Member 'UITM_ResetFaction_C::CostTextBlock' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, CurrentSizebox) == 0x000280, "Member 'UITM_ResetFaction_C::CurrentSizebox' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, FactionLogo) == 0x000288, "Member 'UITM_ResetFaction_C::FactionLogo' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, FactionNameTextBlock) == 0x000290, "Member 'UITM_ResetFaction_C::FactionNameTextBlock' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, Image_429) == 0x000298, "Member 'UITM_ResetFaction_C::Image_429' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, UI_GradientMasked_Image) == 0x0002A0, "Member 'UITM_ResetFaction_C::UI_GradientMasked_Image' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, UI_ImageTinted) == 0x0002A8, "Member 'UITM_ResetFaction_C::UI_ImageTinted' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, CurrentFaction) == 0x0002B0, "Member 'UITM_ResetFaction_C::CurrentFaction' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, Cost) == 0x0002B8, "Member 'UITM_ResetFaction_C::Cost' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, CheckState) == 0x0002C0, "Member 'UITM_ResetFaction_C::CheckState' has a wrong offset!");
static_assert(offsetof(UITM_ResetFaction_C, FactionArray) == 0x0002D0, "Member 'UITM_ResetFaction_C::FactionArray' has a wrong offset!");

}

