#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LIB_PlayerControllerBase

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace CG
{

// BlueprintGeneratedClass LIB_PlayerControllerBase.LIB_PlayerControllerBase_C
// 0x0000 (0x0028 - 0x0028)
class ULIB_PlayerControllerBase_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetPlayerControllerBase(class UObject* __WorldContext, class ABP_PlayerControllerBase_C** Controller);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LIB_PlayerControllerBase_C">();
	}
	static class ULIB_PlayerControllerBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULIB_PlayerControllerBase_C>();
	}
};
static_assert(alignof(ULIB_PlayerControllerBase_C) == 0x000008, "Wrong alignment on ULIB_PlayerControllerBase_C");
static_assert(sizeof(ULIB_PlayerControllerBase_C) == 0x000028, "Wrong size on ULIB_PlayerControllerBase_C");

}

