#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MOD_Proxy_SpawnEnemy

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace CG::Params
{

// Function MOD_Proxy_SpawnEnemy.MOD_Proxy_SpawnEnemy_C.OnEnemySpawned__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature final
{
public:
	class APawn*                                  Param_Enemy;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature) == 0x000008, "Wrong alignment on MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature");
static_assert(sizeof(MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature) == 0x000008, "Wrong size on MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature, Param_Enemy) == 0x000000, "Member 'MOD_Proxy_SpawnEnemy_C_OnEnemySpawned__DelegateSignature::Param_Enemy' has a wrong offset!");

// Function MOD_Proxy_SpawnEnemy.MOD_Proxy_SpawnEnemy_C.ExecuteUbergraph_MOD_Proxy_SpawnEnemy
// 0x0070 (0x0070 - 0x0000)
struct MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2DDC[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class APawn* Enemy)>           K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	class AFSDGameMode*                           CallFunc_GetFSDGameMode_ReturnValue;               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_CustomEvent_enemy;                          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DDD[0x8];                                     // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0030(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SpawnEnemy_ReturnValue;                   // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy) == 0x000010, "Wrong alignment on MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy");
static_assert(sizeof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy) == 0x000070, "Wrong size on MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, EntryPoint) == 0x000000, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::EntryPoint' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, CallFunc_HasAuthority_ReturnValue) == 0x000004, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, CallFunc_GetFSDGameMode_ReturnValue) == 0x000018, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::CallFunc_GetFSDGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, K2Node_CustomEvent_enemy) == 0x000020, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::K2Node_CustomEvent_enemy' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, CallFunc_GetTransform_ReturnValue) == 0x000030, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy, CallFunc_SpawnEnemy_ReturnValue) == 0x000060, "Member 'MOD_Proxy_SpawnEnemy_C_ExecuteUbergraph_MOD_Proxy_SpawnEnemy::CallFunc_SpawnEnemy_ReturnValue' has a wrong offset!");

// Function MOD_Proxy_SpawnEnemy.MOD_Proxy_SpawnEnemy_C.spawned
// 0x0008 (0x0008 - 0x0000)
struct MOD_Proxy_SpawnEnemy_C_Spawned final
{
public:
	class APawn*                                  Param_Enemy;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MOD_Proxy_SpawnEnemy_C_Spawned) == 0x000008, "Wrong alignment on MOD_Proxy_SpawnEnemy_C_Spawned");
static_assert(sizeof(MOD_Proxy_SpawnEnemy_C_Spawned) == 0x000008, "Wrong size on MOD_Proxy_SpawnEnemy_C_Spawned");
static_assert(offsetof(MOD_Proxy_SpawnEnemy_C_Spawned, Param_Enemy) == 0x000000, "Member 'MOD_Proxy_SpawnEnemy_C_Spawned::Param_Enemy' has a wrong offset!");

}

