#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OBJ_DD_Elimination_Eggs

#include "Basic.hpp"

#include "FSD_structs.hpp"


namespace CG::Params
{

// Function OBJ_DD_Elimination_Eggs.OBJ_DD_Elimination_Eggs_C.GetObjectiveAmount
// 0x0008 (0x0008 - 0x0000)
struct OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount final
{
public:
	float                                         MissionLength;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount) == 0x000004, "Wrong alignment on OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount");
static_assert(sizeof(OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount) == 0x000008, "Wrong size on OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount");
static_assert(offsetof(OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount, MissionLength) == 0x000000, "Member 'OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount::MissionLength' has a wrong offset!");
static_assert(offsetof(OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount, ReturnValue) == 0x000004, "Member 'OBJ_DD_Elimination_Eggs_C_GetObjectiveAmount::ReturnValue' has a wrong offset!");

// Function OBJ_DD_Elimination_Eggs.OBJ_DD_Elimination_Eggs_C.GetMissionIcon
// 0x0030 (0x0030 - 0x0000)
struct OBJ_DD_Elimination_Eggs_C_GetMissionIcon final
{
public:
	struct FObjectiveMissionIcon                  ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FObjectiveMissionIcon                  CallFunc_GetPrimaryObjectiveIconFromAsset_ReturnValue; // 0x0018(0x0018)(NoDestructor)
};
static_assert(alignof(OBJ_DD_Elimination_Eggs_C_GetMissionIcon) == 0x000008, "Wrong alignment on OBJ_DD_Elimination_Eggs_C_GetMissionIcon");
static_assert(sizeof(OBJ_DD_Elimination_Eggs_C_GetMissionIcon) == 0x000030, "Wrong size on OBJ_DD_Elimination_Eggs_C_GetMissionIcon");
static_assert(offsetof(OBJ_DD_Elimination_Eggs_C_GetMissionIcon, ReturnValue) == 0x000000, "Member 'OBJ_DD_Elimination_Eggs_C_GetMissionIcon::ReturnValue' has a wrong offset!");
static_assert(offsetof(OBJ_DD_Elimination_Eggs_C_GetMissionIcon, CallFunc_GetPrimaryObjectiveIconFromAsset_ReturnValue) == 0x000018, "Member 'OBJ_DD_Elimination_Eggs_C_GetMissionIcon::CallFunc_GetPrimaryObjectiveIconFromAsset_ReturnValue' has a wrong offset!");

}

