#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Popup_MoreThanOneMainSave

#include "Basic.hpp"

#include "Popup_MoreThanOneMainSave_classes.hpp"
#include "Popup_MoreThanOneMainSave_parameters.hpp"


namespace CG
{

// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.OnOneMainSaveLeft__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::OnOneMainSaveLeft__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "OnOneMainSaveLeft__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.ExecuteUbergraph_Popup_MoreThanOneMainSave
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPopup_MoreThanOneMainSave_C::ExecuteUbergraph_Popup_MoreThanOneMainSave(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "ExecuteUbergraph_Popup_MoreThanOneMainSave");

	Params::Popup_MoreThanOneMainSave_C_ExecuteUbergraph_Popup_MoreThanOneMainSave Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.SaveDeleted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFSDSaveGame*                     Save                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPopup_MoreThanOneMainSave_C::SaveDeleted(class UFSDSaveGame* Save)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "SaveDeleted");

	Params::Popup_MoreThanOneMainSave_C_SaveDeleted Parms{};

	Parms.Save = Save;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPopup_MoreThanOneMainSave_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "PreConstruct");

	Params::Popup_MoreThanOneMainSave_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.SetColors
// (Public, BlueprintCallable, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::SetColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "SetColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.BindSaveslotEvents
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UITM_SaveSlot_Entry_C*            SaveslotWidget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPopup_MoreThanOneMainSave_C::BindSaveslotEvents(class UITM_SaveSlot_Entry_C* SaveslotWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "BindSaveslotEvents");

	Params::Popup_MoreThanOneMainSave_C_BindSaveslotEvents Parms{};

	Parms.SaveslotWidget = SaveslotWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.Reset Color on Non Selected Save
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFSDSaveGame*                     SaveSlot                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPopup_MoreThanOneMainSave_C::Reset_Color_on_Non_Selected_Save(class UFSDSaveGame* SaveSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "Reset Color on Non Selected Save");

	Params::Popup_MoreThanOneMainSave_C_Reset_Color_on_Non_Selected_Save Parms{};

	Parms.SaveSlot = SaveSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.CreateMainSaveslots
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::CreateMainSaveslots()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "CreateMainSaveslots");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.TransformSavenameByBranch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           InSaveName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Savename                                               (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UPopup_MoreThanOneMainSave_C::TransformSavenameByBranch(const class FString& InSaveName, class FString* Savename)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "TransformSavenameByBranch");

	Params::Popup_MoreThanOneMainSave_C_TransformSavenameByBranch Parms{};

	Parms.InSaveName = std::move(InSaveName);

	UObject::ProcessEvent(Func, &Parms);

	if (Savename != nullptr)
		*Savename = std::move(Parms.Savename);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.CreateTempSave
// (Public, BlueprintCallable, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::CreateTempSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "CreateTempSave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Popup_MoreThanOneMainSave.Popup_MoreThanOneMainSave_C.RemoveTempSave
// (Public, BlueprintCallable, BlueprintEvent)

void UPopup_MoreThanOneMainSave_C::RemoveTempSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Popup_MoreThanOneMainSave_C", "RemoveTempSave");

	UObject::ProcessEvent(Func, nullptr);
}

}

