#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TOOLTIP_Mod_Joining

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SimpleUGC_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass TOOLTIP_Mod_Joining.TOOLTIP_Mod_Joining_C
// 0x00A8 (0x0308 - 0x0260)
class UTOOLTIP_Mod_Joining_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_Label_C*                         Mod_ApprovalStatus_Text;                           // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Label_C*                         Mod_Author_Text;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Label_C*                         Mod_Description_Text;                              // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Label_C*                         Mod_Name_Text;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Mod_Thumbnail_Image;                               // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Label_C*                         Mod_Version_Text;                                  // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 ModId;                                             // 0x0298(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 Name_TOOLTIP_Mod_Joining_C;                        // 0x02A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 Version;                                           // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 Description;                                       // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 Author;                                            // 0x02D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	EUGCApprovalStatus                            ApprovalState;                                     // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2D38[0x7];                                     // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UModioModInfoWrapper*                   MetaData;                                          // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 ThumbnailID;                                       // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TOOLTIP_Mod_Joining(int32 EntryPoint);
	void LoadThumbnail();
	void PreConstruct(bool IsDesignTime);
	void FromMetaData(class UModioModInfoWrapper* InMetaData);
	void SetData(const class FString& InModID, const class FString& InName, const class FString& InVersion, const class FString& InDescription, const class FString& InAuthor, EUGCApprovalStatus InApprovalState, bool InFetchThumbnail);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TOOLTIP_Mod_Joining_C">();
	}
	static class UTOOLTIP_Mod_Joining_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTOOLTIP_Mod_Joining_C>();
	}
};
static_assert(alignof(UTOOLTIP_Mod_Joining_C) == 0x000008, "Wrong alignment on UTOOLTIP_Mod_Joining_C");
static_assert(sizeof(UTOOLTIP_Mod_Joining_C) == 0x000308, "Wrong size on UTOOLTIP_Mod_Joining_C");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, UberGraphFrame) == 0x000260, "Member 'UTOOLTIP_Mod_Joining_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_ApprovalStatus_Text) == 0x000268, "Member 'UTOOLTIP_Mod_Joining_C::Mod_ApprovalStatus_Text' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_Author_Text) == 0x000270, "Member 'UTOOLTIP_Mod_Joining_C::Mod_Author_Text' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_Description_Text) == 0x000278, "Member 'UTOOLTIP_Mod_Joining_C::Mod_Description_Text' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_Name_Text) == 0x000280, "Member 'UTOOLTIP_Mod_Joining_C::Mod_Name_Text' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_Thumbnail_Image) == 0x000288, "Member 'UTOOLTIP_Mod_Joining_C::Mod_Thumbnail_Image' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Mod_Version_Text) == 0x000290, "Member 'UTOOLTIP_Mod_Joining_C::Mod_Version_Text' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, ModId) == 0x000298, "Member 'UTOOLTIP_Mod_Joining_C::ModId' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Name_TOOLTIP_Mod_Joining_C) == 0x0002A8, "Member 'UTOOLTIP_Mod_Joining_C::Name_TOOLTIP_Mod_Joining_C' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Version) == 0x0002B8, "Member 'UTOOLTIP_Mod_Joining_C::Version' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Description) == 0x0002C8, "Member 'UTOOLTIP_Mod_Joining_C::Description' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, Author) == 0x0002D8, "Member 'UTOOLTIP_Mod_Joining_C::Author' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, ApprovalState) == 0x0002E8, "Member 'UTOOLTIP_Mod_Joining_C::ApprovalState' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, MetaData) == 0x0002F0, "Member 'UTOOLTIP_Mod_Joining_C::MetaData' has a wrong offset!");
static_assert(offsetof(UTOOLTIP_Mod_Joining_C, ThumbnailID) == 0x0002F8, "Member 'UTOOLTIP_Mod_Joining_C::ThumbnailID' has a wrong offset!");

}

