#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Bar_SupporterLabel

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace CG::Params
{

// Function UI_Bar_SupporterLabel.UI_Bar_SupporterLabel_C.ExecuteUbergraph_UI_Bar_SupporterLabel
// 0x0010 (0x0010 - 0x0000)
struct UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel) == 0x000004, "Wrong alignment on UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel");
static_assert(sizeof(UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel) == 0x000010, "Wrong size on UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel");
static_assert(offsetof(UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel, EntryPoint) == 0x000000, "Member 'UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel, CallFunc_MakeVector2D_ReturnValue) == 0x000004, "Member 'UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel, K2Node_Event_IsDesignTime) == 0x00000C, "Member 'UI_Bar_SupporterLabel_C_ExecuteUbergraph_UI_Bar_SupporterLabel::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_Bar_SupporterLabel.UI_Bar_SupporterLabel_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Bar_SupporterLabel_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Bar_SupporterLabel_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Bar_SupporterLabel_C_PreConstruct");
static_assert(sizeof(UI_Bar_SupporterLabel_C_PreConstruct) == 0x000001, "Wrong size on UI_Bar_SupporterLabel_C_PreConstruct");
static_assert(offsetof(UI_Bar_SupporterLabel_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Bar_SupporterLabel_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Bar_SupporterLabel.UI_Bar_SupporterLabel_C.SetDrinkable
// 0x0020 (0x0020 - 0x0000)
struct UI_Bar_SupporterLabel_C_SetDrinkable final
{
public:
	class UDrinkableDataAsset*                    Drinkable;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSpecialEdition;                                  // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_389A[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDrinkableDataAsset*                    OutDrinkable;                                      // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayInEditor_ReturnValue;               // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasSpecialEdition_ReturnValue;            // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsUnLocked_ReturnValue;                   // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_Bar_SupporterLabel_C_SetDrinkable) == 0x000008, "Wrong alignment on UI_Bar_SupporterLabel_C_SetDrinkable");
static_assert(sizeof(UI_Bar_SupporterLabel_C_SetDrinkable) == 0x000020, "Wrong size on UI_Bar_SupporterLabel_C_SetDrinkable");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, Drinkable) == 0x000000, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::Drinkable' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, IsSpecialEdition) == 0x000008, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::IsSpecialEdition' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, OutDrinkable) == 0x000010, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::OutDrinkable' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, CallFunc_IsPlayInEditor_ReturnValue) == 0x000018, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::CallFunc_IsPlayInEditor_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, CallFunc_HasSpecialEdition_ReturnValue) == 0x00001A, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::CallFunc_HasSpecialEdition_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, CallFunc_IsUnLocked_ReturnValue) == 0x00001B, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::CallFunc_IsUnLocked_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Bar_SupporterLabel_C_SetDrinkable, CallFunc_BooleanOR_ReturnValue) == 0x00001C, "Member 'UI_Bar_SupporterLabel_C_SetDrinkable::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

