#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BeerBuff_SpaceRig

#include "Basic.hpp"

#include "UI_BeerBuff_SpaceRig_classes.hpp"
#include "UI_BeerBuff_SpaceRig_parameters.hpp"


namespace CG
{

// Function UI_BeerBuff_SpaceRig.UI_BeerBuff_Spacerig_C.ExecuteUbergraph_UI_BeerBuff_Spacerig
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BeerBuff_Spacerig_C::ExecuteUbergraph_UI_BeerBuff_Spacerig(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeerBuff_Spacerig_C", "ExecuteUbergraph_UI_BeerBuff_Spacerig");

	Params::UI_BeerBuff_Spacerig_C_ExecuteUbergraph_UI_BeerBuff_Spacerig Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BeerBuff_SpaceRig.UI_BeerBuff_Spacerig_C.On Buff Changed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTemporaryBuff*                   buff                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BeerBuff_Spacerig_C::On_Buff_Changed(class UTemporaryBuff* buff)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeerBuff_Spacerig_C", "On Buff Changed");

	Params::UI_BeerBuff_Spacerig_C_On_Buff_Changed Parms{};

	Parms.buff = buff;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BeerBuff_SpaceRig.UI_BeerBuff_Spacerig_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_BeerBuff_Spacerig_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeerBuff_Spacerig_C", "PreConstruct");

	Params::UI_BeerBuff_Spacerig_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_BeerBuff_SpaceRig.UI_BeerBuff_Spacerig_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_BeerBuff_Spacerig_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeerBuff_Spacerig_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_BeerBuff_SpaceRig.UI_BeerBuff_Spacerig_C.OnLoaded_E76038A2482A1272456904B10D0684E1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_BeerBuff_Spacerig_C::OnLoaded_E76038A2482A1272456904B10D0684E1(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BeerBuff_Spacerig_C", "OnLoaded_E76038A2482A1272456904B10D0684E1");

	Params::UI_BeerBuff_Spacerig_C_OnLoaded_E76038A2482A1272456904B10D0684E1 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}

}

