#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InfoScreen

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "InputCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace CG::Params
{

// Function UI_InfoScreen.UI_InfoScreen_C.OnKeyDown
// 0x02C0 (0x02C0 - 0x0000)
struct UI_InfoScreen_C_OnKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0128(0x0018)(HasGetValueTypeHash)
	class UFSDGameUserSettings*                   CallFunc_GetFSDGameUserSettings_ReturnValue;       // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ToggleTranslatorDebugMode_ReturnValue;    // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x014A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x014B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_2;          // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3392[0x2];                                     // 0x014E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0150(0x00B8)()
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0208(0x00B8)()
};
static_assert(alignof(UI_InfoScreen_C_OnKeyDown) == 0x000008, "Wrong alignment on UI_InfoScreen_C_OnKeyDown");
static_assert(sizeof(UI_InfoScreen_C_OnKeyDown) == 0x0002C0, "Wrong size on UI_InfoScreen_C_OnKeyDown");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, MyGeometry) == 0x000000, "Member 'UI_InfoScreen_C_OnKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, InKeyEvent) == 0x000038, "Member 'UI_InfoScreen_C_OnKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, ReturnValue) == 0x000070, "Member 'UI_InfoScreen_C_OnKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_GetKey_ReturnValue) == 0x000128, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_GetFSDGameUserSettings_ReturnValue) == 0x000140, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_GetFSDGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x000148, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_ToggleTranslatorDebugMode_ReturnValue) == 0x000149, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_ToggleTranslatorDebugMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x00014A, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_BooleanOR_ReturnValue) == 0x00014B, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_2) == 0x00014C, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_BooleanAND_ReturnValue) == 0x00014D, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_Unhandled_ReturnValue) == 0x000150, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyDown, CallFunc_Handled_ReturnValue) == 0x000208, "Member 'UI_InfoScreen_C_OnKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.OnKeyUp
// 0x02A0 (0x02A0 - 0x0000)
struct UI_InfoScreen_C_OnKeyUp final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0128(0x00B8)()
	bool                                          CallFunc_IsOkMenu_ReturnValue;                     // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3393[0x7];                                     // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x01E8(0x00B8)()
};
static_assert(alignof(UI_InfoScreen_C_OnKeyUp) == 0x000008, "Wrong alignment on UI_InfoScreen_C_OnKeyUp");
static_assert(sizeof(UI_InfoScreen_C_OnKeyUp) == 0x0002A0, "Wrong size on UI_InfoScreen_C_OnKeyUp");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, MyGeometry) == 0x000000, "Member 'UI_InfoScreen_C_OnKeyUp::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, InKeyEvent) == 0x000038, "Member 'UI_InfoScreen_C_OnKeyUp::InKeyEvent' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, ReturnValue) == 0x000070, "Member 'UI_InfoScreen_C_OnKeyUp::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, CallFunc_Unhandled_ReturnValue) == 0x000128, "Member 'UI_InfoScreen_C_OnKeyUp::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, CallFunc_IsOkMenu_ReturnValue) == 0x0001E0, "Member 'UI_InfoScreen_C_OnKeyUp::CallFunc_IsOkMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_OnKeyUp, CallFunc_Handled_ReturnValue) == 0x0001E8, "Member 'UI_InfoScreen_C_OnKeyUp::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.UpdateButtons
// 0x0008 (0x0008 - 0x0000)
struct UI_InfoScreen_C_UpdateButtons final
{
public:
	bool                                          HasClaimed;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsFollowing;                                       // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_InfoScreen_C_UpdateButtons) == 0x000001, "Wrong alignment on UI_InfoScreen_C_UpdateButtons");
static_assert(sizeof(UI_InfoScreen_C_UpdateButtons) == 0x000008, "Wrong size on UI_InfoScreen_C_UpdateButtons");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, HasClaimed) == 0x000000, "Member 'UI_InfoScreen_C_UpdateButtons::HasClaimed' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, IsFollowing) == 0x000001, "Member 'UI_InfoScreen_C_UpdateButtons::IsFollowing' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_BooleanAND_ReturnValue) == 0x000002, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_Not_PreBool_ReturnValue) == 0x000003, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_BooleanAND_ReturnValue_1) == 0x000004, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_Not_PreBool_ReturnValue_1) == 0x000005, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_Not_PreBool_ReturnValue_2) == 0x000006, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_UpdateButtons, CallFunc_BooleanAND_ReturnValue_2) == 0x000007, "Member 'UI_InfoScreen_C_UpdateButtons::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.FadeIt
// 0x0018 (0x0018 - 0x0000)
struct UI_InfoScreen_C_FadeIt final
{
public:
	bool                                          Param_FadeIn;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3394[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Duration;                                          // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_InfoScreen_C_FadeIt) == 0x000008, "Wrong alignment on UI_InfoScreen_C_FadeIt");
static_assert(sizeof(UI_InfoScreen_C_FadeIt) == 0x000018, "Wrong size on UI_InfoScreen_C_FadeIt");
static_assert(offsetof(UI_InfoScreen_C_FadeIt, Param_FadeIn) == 0x000000, "Member 'UI_InfoScreen_C_FadeIt::Param_FadeIn' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_FadeIt, Duration) == 0x000004, "Member 'UI_InfoScreen_C_FadeIt::Duration' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_FadeIt, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'UI_InfoScreen_C_FadeIt::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_FadeIt, CallFunc_PlayAnimation_ReturnValue_1) == 0x000010, "Member 'UI_InfoScreen_C_FadeIt::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_InfoScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_InfoScreen_C_PreConstruct) == 0x000001, "Wrong alignment on UI_InfoScreen_C_PreConstruct");
static_assert(sizeof(UI_InfoScreen_C_PreConstruct) == 0x000001, "Wrong size on UI_InfoScreen_C_PreConstruct");
static_assert(offsetof(UI_InfoScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_InfoScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.ExecuteUbergraph_UI_InfoScreen
// 0x00C8 (0x00C8 - 0x0000)
struct UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_3395[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PlayerIsFollowingUsOnSteam_ReturnValue;   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3396[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFSDSaveGame*                           CallFunc_GetFSDSaveGame_ReturnValue;               // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFSDSaveGame*                           CallFunc_GetFSDSaveGame_ReturnValue_1;             // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue;  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_1; // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3397[0x2];                                     // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_AddCredits_ReturnValue;                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3398[0x3];                                     // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_MenuColors_OutputColor;                   // 0x0064(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3399[0x4];                                     // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0078(0x0028)()
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_2;            // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFSDSaveGame*                           CallFunc_GetFSDSaveGame_ReturnValue_2;             // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_2; // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen) == 0x000008, "Wrong alignment on UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen");
static_assert(sizeof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen) == 0x0000C8, "Wrong size on UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, EntryPoint) == 0x000000, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, K2Node_CreateDelegate_OutputDelegate_2) == 0x000024, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_PlayAnimation_ReturnValue) == 0x000038, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_PlayerIsFollowingUsOnSteam_ReturnValue) == 0x000040, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_PlayerIsFollowingUsOnSteam_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetFSDSaveGame_ReturnValue) == 0x000048, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetFSDSaveGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetFSDSaveGame_ReturnValue_1) == 0x000050, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetFSDSaveGame_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue) == 0x000058, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_1) == 0x000059, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_AddCredits_ReturnValue) == 0x00005C, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_AddCredits_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, K2Node_Event_IsDesignTime) == 0x000060, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_MenuColors_OutputColor) == 0x000064, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_MenuColors_OutputColor' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, K2Node_MakeStruct_SlateColor) == 0x000078, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000A0, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0000A8, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetOwningPlayer_ReturnValue_2) == 0x0000B0, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetOwningPlayer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetFSDSaveGame_ReturnValue_2) == 0x0000B8, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetFSDSaveGame_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen, CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_2) == 0x0000C0, "Member 'UI_InfoScreen_C_ExecuteUbergraph_UI_InfoScreen::CallFunc_GetHasClaimedSteamGroupLoot_ReturnValue_2' has a wrong offset!");

// Function UI_InfoScreen.UI_InfoScreen_C.OnClose__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_InfoScreen_C_OnClose__DelegateSignature final
{
public:
	class UUI_InfoScreen_C*                       Screen;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_InfoScreen_C_OnClose__DelegateSignature) == 0x000008, "Wrong alignment on UI_InfoScreen_C_OnClose__DelegateSignature");
static_assert(sizeof(UI_InfoScreen_C_OnClose__DelegateSignature) == 0x000008, "Wrong size on UI_InfoScreen_C_OnClose__DelegateSignature");
static_assert(offsetof(UI_InfoScreen_C_OnClose__DelegateSignature, Screen) == 0x000000, "Member 'UI_InfoScreen_C_OnClose__DelegateSignature::Screen' has a wrong offset!");

}

