#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ModdingProgressBar

#include "Basic.hpp"

#include "UI_ModdingProgressBar_classes.hpp"
#include "UI_ModdingProgressBar_parameters.hpp"


namespace CG
{

// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.ExecuteUbergraph_UI_ModdingProgressBar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ModdingProgressBar_C::ExecuteUbergraph_UI_ModdingProgressBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "ExecuteUbergraph_UI_ModdingProgressBar");

	Params::UI_ModdingProgressBar_C_ExecuteUbergraph_UI_ModdingProgressBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_ModdingProgressBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "PreConstruct");

	Params::UI_ModdingProgressBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.SetProgress
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Downloading                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Total                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ModdingProgressBar_C::SetProgress(bool Downloading, int32 Progress, int32 Total)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "SetProgress");

	Params::UI_ModdingProgressBar_C_SetProgress Parms{};

	Parms.Downloading = Downloading;
	Parms.Progress = Progress;
	Parms.Total = Total;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.Int2Text
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_ModdingProgressBar_C::Int2Text(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "Int2Text");

	Params::UI_ModdingProgressBar_C_Int2Text Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.FinishExtracting
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_ModdingProgressBar_C::FinishExtracting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "FinishExtracting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.Error
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUGCPackageError                        InErrorType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ModdingProgressBar_C::Error(EUGCPackageError InErrorType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "Error");

	Params::UI_ModdingProgressBar_C_Error Parms{};

	Parms.InErrorType = InErrorType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.GetTotal
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Total                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ModdingProgressBar_C::GetTotal(int32* Total)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "GetTotal");

	Params::UI_ModdingProgressBar_C_GetTotal Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Total != nullptr)
		*Total = Parms.Total;
}


// Function UI_ModdingProgressBar.UI_ModdingProgressBar_C.SetProgressCustomText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Total                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ModdingProgressBar_C::SetProgressCustomText(const class FText& Text, int32 Progress, int32 Total)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ModdingProgressBar_C", "SetProgressCustomText");

	Params::UI_ModdingProgressBar_C_SetProgressCustomText Parms{};

	Parms.Text = std::move(Text);
	Parms.Progress = Progress;
	Parms.Total = Total;

	UObject::ProcessEvent(Func, &Parms);
}

}

