#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_RoundedCanvas

#include "Basic.hpp"

#include "UI_RoundedCanvas_classes.hpp"
#include "UI_RoundedCanvas_parameters.hpp"


namespace CG
{

// Function UI_RoundedCanvas.UI_RoundedCanvas_C.ExecuteUbergraph_UI_RoundedCanvas
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_RoundedCanvas_C::ExecuteUbergraph_UI_RoundedCanvas(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_RoundedCanvas_C", "ExecuteUbergraph_UI_RoundedCanvas");

	Params::UI_RoundedCanvas_C_ExecuteUbergraph_UI_RoundedCanvas Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_RoundedCanvas.UI_RoundedCanvas_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_RoundedCanvas_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_RoundedCanvas_C", "PreConstruct");

	Params::UI_RoundedCanvas_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_RoundedCanvas.UI_RoundedCanvas_C.UpdateMaterial
// (Private, BlueprintCallable, BlueprintEvent)

void UUI_RoundedCanvas_C::UpdateMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_RoundedCanvas_C", "UpdateMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_RoundedCanvas.UI_RoundedCanvas_C.OnPaint
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FPaintContext                    Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UUI_RoundedCanvas_C::OnPaint(struct FPaintContext& Context) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_RoundedCanvas_C", "OnPaint");

	Params::UI_RoundedCanvas_C_OnPaint Parms{};

	Parms.Context = std::move(Context);

	UObject::ProcessEvent(Func, &Parms);

	Context = std::move(Parms.Context);
}

}

