#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_DropPod_MissionType

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace CG
{

// WidgetBlueprintGeneratedClass Widget_DropPod_MissionType.Widget_DropPod_MissionType_C
// 0x0090 (0x02F0 - 0x0260)
class UWidget_DropPod_MissionType_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_Menu_ColorBar_C*                 Basic_Menu_ColorBar;                               // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DATA_MissionName;                                  // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DATA_MissionType;                                  // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               DeepDiveIcon;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Mutators;                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_41;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_DeepDive_ObjectiveIcon_C*          ITM_DeepDive_ObjectiveIcon;                        // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_MisDesMutator_C*                   ITM_MisDesMutator;                                 // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_MisDesMutator_C*                   ITM_MisDesMutator_1;                               // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_MisSel_MissionIconBasic_C*         ITM_MisSel_MissionIconBasic;                       // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               NotDeepDiveIcon;                                   // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_MissionBarDropPod_Objective_C*     PrimaryObjective;                                  // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UITM_MissionBarDropPod_Objective_C*     SecundaryObjective;                                // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_MissionData;                           // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_0;                                  // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         TimePassed;                                        // 0x02E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MissionLength;                                     // 0x02E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MissionComplexity;                                 // 0x02E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Widget_DropPod_MissionType(int32 EntryPoint);
	void OnDifficultyChanged_Event_0(class UDifficultySetting* Setting);
	void OnGeneratedMissionChanged(class UGeneratedMission* OutGeneratedMission);
	void Construct();
	void SetGeneratedMission(class UGeneratedMission* In_Mission);
	void SetMutators(class UGeneratedMission* Mission);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Widget_DropPod_MissionType_C">();
	}
	static class UWidget_DropPod_MissionType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_DropPod_MissionType_C>();
	}
};
static_assert(alignof(UWidget_DropPod_MissionType_C) == 0x000008, "Wrong alignment on UWidget_DropPod_MissionType_C");
static_assert(sizeof(UWidget_DropPod_MissionType_C) == 0x0002F0, "Wrong size on UWidget_DropPod_MissionType_C");
static_assert(offsetof(UWidget_DropPod_MissionType_C, UberGraphFrame) == 0x000260, "Member 'UWidget_DropPod_MissionType_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, Basic_Menu_ColorBar) == 0x000268, "Member 'UWidget_DropPod_MissionType_C::Basic_Menu_ColorBar' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, DATA_MissionName) == 0x000270, "Member 'UWidget_DropPod_MissionType_C::DATA_MissionName' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, DATA_MissionType) == 0x000278, "Member 'UWidget_DropPod_MissionType_C::DATA_MissionType' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, DeepDiveIcon) == 0x000280, "Member 'UWidget_DropPod_MissionType_C::DeepDiveIcon' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, HorizontalBox_Mutators) == 0x000288, "Member 'UWidget_DropPod_MissionType_C::HorizontalBox_Mutators' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, Image_41) == 0x000290, "Member 'UWidget_DropPod_MissionType_C::Image_41' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, ITM_DeepDive_ObjectiveIcon) == 0x000298, "Member 'UWidget_DropPod_MissionType_C::ITM_DeepDive_ObjectiveIcon' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, ITM_MisDesMutator) == 0x0002A0, "Member 'UWidget_DropPod_MissionType_C::ITM_MisDesMutator' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, ITM_MisDesMutator_1) == 0x0002A8, "Member 'UWidget_DropPod_MissionType_C::ITM_MisDesMutator_1' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, ITM_MisSel_MissionIconBasic) == 0x0002B0, "Member 'UWidget_DropPod_MissionType_C::ITM_MisSel_MissionIconBasic' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, NotDeepDiveIcon) == 0x0002B8, "Member 'UWidget_DropPod_MissionType_C::NotDeepDiveIcon' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, PrimaryObjective) == 0x0002C0, "Member 'UWidget_DropPod_MissionType_C::PrimaryObjective' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, SecundaryObjective) == 0x0002C8, "Member 'UWidget_DropPod_MissionType_C::SecundaryObjective' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, VerticalBox_MissionData) == 0x0002D0, "Member 'UWidget_DropPod_MissionType_C::VerticalBox_MissionData' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, WidgetSwitcher_0) == 0x0002D8, "Member 'UWidget_DropPod_MissionType_C::WidgetSwitcher_0' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, TimePassed) == 0x0002E0, "Member 'UWidget_DropPod_MissionType_C::TimePassed' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, MissionLength) == 0x0002E4, "Member 'UWidget_DropPod_MissionType_C::MissionLength' has a wrong offset!");
static_assert(offsetof(UWidget_DropPod_MissionType_C, MissionComplexity) == 0x0002E8, "Member 'UWidget_DropPod_MissionType_C::MissionComplexity' has a wrong offset!");

}

