#pragma once

#define GAME_FNAMES(x) \
	x(Invalid) \
    x(Pawn) \
    x(Character) \
    x(PlayerCharacter) \
    x(DefaultPawn) \
    x(PathfinderVehicle) \
    x(PlayerCameraDrone) \
    x(FSDPawn) \
    x(Caretaker) \
    x(EscortMule) \
    x(TowerModuleBase) \
    x(GuntowerModule) \
    x(GuntowerWeakPoint) \
    x(TowerEventModule) \
    x(EnemyPawn) \
    x(StabberVineRoot) \
    x(ParasiteEnemy) \
    x(InsectSwarmSpawner) \
    x(HydraWeedHealer) \
    x(ShootingPlant) \
    x(HydraWeedCore) \
    x(FacilityTurret) \
    x(TentacleBase) \
    x(CaveLeech) \
    x(DeepPathfinderCharacter) \
    x(EnemyDeepPathfinderCharacter) \
    x(AFlyingBug) \
    x(ConvertedRobot) \
    x(FlyingEnemyDeepPathfinderCharacter) \
    x(FriendlyParasite) \
    x(HalloweenSkull) \
    x(InsectSwarmEnemy) \
    x(PatrolBot) \
    x(PlagueWorm) \
    x(ProspectorRobot) \
    x(SharkEnemy) \
    x(Shredder) \
    x(SpiderEnemy) \
    x(TerminatorEnemy) \
    x(WoodLouse) \
    x(BP_ShieldRegenerator_Mover_C) \
    x(ENE_Jelly_Passive_C) \
    x(Bosco) \
    x(CaveWorm) \
    x(Maggot) \
    x(DroneBase) \
    x(DroneCharacter) \
    x(MULE) \
    x(RecallableActor) \
    x(ITM_DeepDiveStatus_Stage_C) \
    x(ITM_MisDesMutator_C) \
    x(ITM_SeasonMenu_BG_C) \
    x(ITM_RestoreSaveCategoryList_Entry_C) \
    x(ITM_UpgGear_TierRow_C) \
    x(ITM_CommunityGoalProgress_C) \
    x(ITM_BarGlass_Item_PotOGold_C) \
    x(ITM_Overclocks_Equip_Item_C) \
    x(ITM_Loadout_ItemWindow_C) \
    x(ITM_MisSel_MissionIconBasic_Locked_C) \
    x(ITM_ItemCategories_C) \
    x(ITM_SeasonContentToggle_C) \
    x(ITM_Craft_ItemIcon_C) \
    x(ITM_LoadoutSelectorBar_C) \
    x(ITM_Overclock_Details_C) \
    x(ITM_FactionToolTip_C) \
    x(ITM_LoadoutSelectButton_C) \
    x(ITM_CommunityGoalRewardToolTip_C) \
    x(ITM_BarGlass_Item_WormholeSpecial_C) \
    x(ITM_BarGlass_Item_BlackOutStout_C) \
    x(ITM_PerkInfoBox_C) \
    x(ITM_PendingMod_C) \
    x(ITM_MissionComplete_MissionState_Failure_C) \
    x(ITM_BarGlass_Item_MaltRockBearer_C) \
    x(ITM_Wardrobe_ItemSelector_C) \
    x(ITM_Flare_Large_C) \
    x(ITM_LoadOut_PerksEquip_Item_C) \
    x(ITM_ServerList_AttentionBox_C) \
    x(ITM_Job_Section_Header_C) \
    x(ITM_Trading_ResourcePoster_C) \
    x(ITM_BarGlass_Item_DarkMokite_C) \
    x(ITM_Season_LevelInfinity_C) \
    x(ITM_WeeklyMissionOverlay_C) \
    x(ITM_MissionComplete_DeepDiveHeader_C) \
    x(ITM_Wardrobe_ItemSlot_Base_C) \
    x(ITM_DeepDive_MisCompBG_C) \
    x(ITM_MisSel_RegionImage_C) \
    x(ITM_WeaponInfo_C) \
    x(ITM_TopBar_CharacterLevel_C) \
    x(ITM_BarGlass_Item_GlyphidSlammer_Support_C) \
    x(ITM_SeasonEditor_Level_C) \
    x(ITM_CampaignItem_Member_C) \
    x(ITM_Biome_ResourceIcon_C) \
    x(ITM_DeepDives_ServerFilters_C) \
    x(ITM_BarGlass_Item_DUMMY_C) \
    x(ITM_SaveSlot_Entry_C) \
    x(ITM_TopBar_PlayerCounter_C) \
    x(ITM_Craft_ResourceBig_C) \
    x(ITM_SeasonEventBonus_C) \
    x(ITM_Refinery_Pipeline_C) \
    x(ITM_CharacterIcon_C) \
    x(ITM_LoadoutIconSelector_C) \
    x(ITM_Season_Level_C) \
    x(ITM_ServerEntry_TeamLine_C) \
    x(ITM_CurrentSaveSlot_RankOrLevelReadout_C) \
    x(ITM_BarGlass_Item_ArkenStout_C) \
    x(ITM_MissionBar_Objective_C) \
    x(ITM_DeepDives_ServerList_Entry_C) \
    x(ITM_PropHunt_HunterItem_C) \
    x(ITM_Season_NextReward_C) \
    x(ITM_AnyRetiredRequirement_C) \
    x(ITM_MissionComplete_MissionState_Success_C) \
    x(ITM_CommunityGoalRecruitment_C) \
    x(ITM_CommunityGoalResult_ConsoleScreenV1_C) \
    x(ITM_MutatorIcon_C) \
    x(ITM_SeasonProgressBar_C) \
    x(ITM_Mod_Joining_C) \
    x(ITM_MutatorsAndWarnings_Entry1_C) \
    x(ITM_LoadOut_PerksEquip_Slot_C) \
    x(ITM_Wardrobe_ItemSlot_ArmorVanity_C) \
    x(ITM_MissionInfo_C) \
    x(ITM_SocialMediaButtons_C) \
    x(ITM_Special_ButtonCutCorner_C) \
    x(ITM_BaseUpgradeIcon_C) \
    x(ITM_AOE_Grenade_Base_C) \
    x(ITM_Craft_ResourceSmall_C) \
    x(ITM_Season_CharacterIcon_C) \
    x(ITM_SegmentedHealthBar_C) \
    x(ITM_CreateNewSaveSlot_Entry_C) \
    x(ITM_Craft_Resource_C) \
    x(ITM_CreditsEntry_C) \
    x(ITM_MissionComplete_ResourceBox_C) \
    x(ITM_SeasonEditor_EmptySpot_C) \
    x(ITM_MisSel_Biome_C) \
    x(ITM_SeasonPlagueCleanBonus_C) \
    x(ITM_Craft_ItemBox_C) \
    x(ITM_DeepDiveHeader_C) \
    x(ITM_HealthBar_C) \
    x(ITM_FactionLogo_C) \
    x(ITM_BarGlass_Item_SmartStout_C) \
    x(ITM_CommunityGoal_TotalProgress_C) \
    x(ITM_Community_Console_ClaimReward_C) \
    x(ITM_Gear_Bar_C) \
    x(ITM_PrivatePublic_C) \
    x(ITM_Wardrobe_ItemSlot_VictoryMoves_C) \
    x(ITM_TopBar_PlayerRank_C) \
    x(ITM_BarGlass_Item_Gutwrecker_C) \
    x(ITM_CleanupDrop_C) \
    x(ITM_BarGlass_Item_SlayerStout_C) \
    x(ITM_DeepDiveInfo_C) \
    x(ITM_DLC_Entry_C) \
    x(ITM_Loadout_PerksEquip_Selection_C) \
    x(ITM_CommunityGoalFactionSelection_C) \
    x(ITM_BarGlass_Item_RockBlaster_C) \
    x(ITM_Modding_LoadoutSelection_C) \
    x(ITM_Flare_Small_Driller_C) \
    x(ITM_MisSel_DotMarker_WorkEnvironment_C) \
    x(ITM_MissionComplete_Resource_C) \
    x(ITM_MisSel_PlanetZone_C) \
    x(ITM_Trading_Resource_C) \
    x(ITM_Mod_C) \
    x(ITM_CampaignProgress_Small_C) \
    x(ITM_HackingTool_C) \
    x(ITM_CleanupDrop_WalkingPlagueHeart_C) \
    x(ITM_Season_RewardImageSingle_C) \
    x(ITM_MissionMapIcon_LevelLock_C) \
    x(ITM_MisSel_BG_Planet_C) \
    x(ITM_DragRotateCharacter_C) \
    x(ITM_DeepDive_StageIcon_C) \
    x(ITM_Tab_Modding_C) \
    x(ITM_SonyTeamLeader_C) \
    x(ITM_TimeText_C) \
    x(ITM_TopBar_Resources_C) \
    x(ITM_LoadoutIcon_C) \
    x(ITM_CampaignCompletedRequirement_C) \
    x(ITM_SupplyBarItem_C) \
    x(ITM_BarGlass_Item_MacteraBrew_C) \
    x(ITM_CampaignProgress_NoBrackets_C) \
    x(ITM_CommunityGoal_TotalProgress_ConsoleScreenV2_C) \
    x(ITM_Overclocks_Equip_C) \
    x(ITM_SeasonEditor_Reward_C) \
    x(ITM_MissionBar_Warning_C) \
    x(ITM_Season_ChallengeTimer_C) \
    x(ITM_TreeOfVanity_Node_C) \
    x(ITM_Wardrobe_ItemSlot_Vanity_C) \
    x(ITM_TreeOfVanityEditor_NodeIcon_C) \
    x(ITM_MisSel_ObjectiveSecondary_C) \
    x(ITM_ItemIcon_C) \
    x(ITM_RestoreSaveList_Entry_C) \
    x(ITM_UpgGear_UpgIconSingle_C) \
    x(ITM_MisSel_ResourceIcon_C) \
    x(ITM_MatrixCore_C) \
    x(ITM_MisSel_Timer_C) \
    x(ITM_SupplyBar_C) \
    x(ITM_HostIcon_C) \
    x(ITM_MasteryBar_Block_C) \
    x(ITM_MenuDamageIndicator_C) \
    x(ITM_ValidSeedRequirement_C) \
    x(ITM_BarGlass_Item_PropHunt_C) \
    x(ITM_SupplyDrop_C) \
    x(ITM_Season_Challenge_C) \
    x(ITM_MisSel_DotMarker_MissionLength_C) \
    x(ITM_DeepDives_ServerList_C) \
    x(ITM_Trading_BasketItem_C) \
    x(ITM_MissionMapIcon_Objective_C) \
    x(ITM_InfoBox_C) \
    x(ITM_BarGlass_Item_LeafloversSpecial_C) \
    x(ITM_Prerequisites_C) \
    x(ITM_Grenade_Base_C) \
    x(ITM_DeepDives_LaunchButton_C) \
    x(ITM_CharacterBuffIcon_C) \
    x(ITM_Overclock_Details_Item_C) \
    x(ITM_MisSel_RegionImage1_C) \
    x(ITM_BaseFlare_C) \
    x(ITM_Pickaxe_Slot_C) \
    x(ITM_Season_LevelEndGradient_C) \
    x(ITM_Wardrobe_ItemSelector_Entry_C) \
    x(ITM_BasicTutorialWindow_C) \
    x(ITM_Jobs_WeeklyBG_C) \
    x(ITM_BarGlass_Item_GlyphidSlammer_C) \
    x(ITM_CommunityGoal_C) \
    x(ITM_MisSel_DotMarker_C) \
    x(ITM_BarGlass_Item_TunnelRat_C) \
    x(ITM_Loadout_UpgradeBar_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_GrenadeIcon_Lock_C) \
    x(ITM_TerrainScanner_C) \
    x(ITM_CurrentSaveSlot_Resources_C) \
    x(ITM_BarGlass_Item_BurningLove_C) \
    x(ITM_MissionMap_Icon_BG_C) \
    x(ITM_MisSel_MissionCount_C) \
    x(ITM_DeepDives_RejoinButton_C) \
    x(ITM_SeasonEvent_C) \
    x(ITM_CampaignItem_SmallEmpty_C) \
    x(ITM_Loadout_PerksEquip_C) \
    x(ITM_Season_Progress_Small_C) \
    x(ITM_Flare_Small_Engineer_C) \
    x(ITM_ResetFaction_ConsoleScreenV1_C) \
    x(ITM_BarGlass_Item_OilyOafBrew_C) \
    x(ITM_RetirementBadge_C) \
    x(ITM_CampaignProgress_C) \
    x(ITM_HealthBarPercentWWarning_C) \
    x(ITM_DeepDives_Start_C) \
    x(ITM_MenuBackground_C) \
    x(ITM_GeneratedIcon_Item_C) \
    x(ITM_SaveSlot_Entry_ClassIcon_C) \
    x(ITM_MissionComplete_MissionState_C) \
    x(ITM_MisSel_BiomeBase_C) \
    x(ITM_SkinItem_C) \
    x(ITM_ServerList_Warning_C) \
    x(ITM_DeepDives_Join_C) \
    x(ITM_BarGlass_Item_FlintlockesDelight_C) \
    x(ITM_ObjectiveBox_InMission_C) \
    x(ITM_BarGlass_Item_SeasonedMoonrider_C) \
    x(ITM_MisSel_DotMarker_CaveDifficulty_C) \
    x(ITM_BarGlass_Item_BlacklockLager_C) \
    x(ITM_GrenadeThrow_C) \
    x(ITM_HealthBarSection_C) \
    x(ITM_LoadOut_PerksEquip_None_C) \
    x(ITM_Pipeline_BrokenIcon_C) \
    x(ITM_SeasonEndWarningTimer_C) \
    x(ITM_Flare_Small_C) \
    x(ITM_Season_LevelUp_C) \
    x(ITM_EscortMuleHealthBar_C) \
    x(ITM_BarGlass_Item_UnderhillDeluxe_C) \
    x(ITM_MisSel_MissionMapIcon_C) \
    x(ITM_MasteryBar_Icon_C) \
    x(ITM_RestoreSave_C) \
    x(ITM_Modding_ToolTip_Entry_C) \
    x(ITM_DeepDiveHeaderElite_C) \
    x(ITM_UpgGear_SideBar_C) \
    x(ITM_ServerList_Entry_C) \
    x(ITM_PreventDuplicateCharacters_C) \
    x(ITM_SeasonLogo_C) \
    x(ITM_SocialMediaButton_C) \
    x(ITM_CharacterSwitcherBar_C) \
    x(ITM_MisSel_FullBiome_C) \
    x(ITM_SeasonChallengeIcon_C) \
    x(ITM_MisSel_MissionIconBasic_C) \
    x(ITM_CommunityGoalRecruitment_ConsoleScreenV1_C) \
    x(ITM_Flare_Large_Scout_C) \
    x(ITM_FuelCannisterStatus_C) \
    x(ITM_DeepDiveStatus_Animator_C) \
    x(ITM_MisSel_ObjectivePrimary_C) \
    x(ITM_JobsEntry_Resource_C) \
    x(ITM_CommunityGoalResult_C) \
    x(ITM_Modding_Loadout_C) \
    x(ITM_SegmentedArmorBar_C) \
    x(ITM_BarGlass_Item_RandoWeisser_C) \
    x(ITM_UpgGear_GearStat_C) \
    x(ITM_UpgGear_GearTab_C) \
    x(ITM_Flare_Large_Gunner_C) \
    x(ITM_DeepDives_Launcher_C) \
    x(ITM_TopBar_ResourceCounter_C) \
    x(ITM_BarGlass_Item_Oktoberfest_C) \
    x(ITM_BarGlass_Item_BlackreachBlonde_C) \
    x(ITM_BarGlass_Item_RockyMountain_C) \
    x(ITM_NewsTicker_C) \
    x(ITM_Overclock_Icon_C) \
    x(ITM_Campaign_Icon_C) \
    x(ITM_ItemUnlockedIcon_C) \
    x(ITM_OnlineRestricted_C) \
    x(ITM_DragRotateCharacterShowroom_C) \
    x(ITM_ServerList_Entry_PlayerIcons_C) \
    x(ITM_BigButton_C) \
    x(ITM_CharacterDeepDive_C) \
    x(ITM_ResetFaction_C) \
    x(ITM_BossFightContainer_C) \
    x(ITM_EscMenu_BriefingV2_C) \
    x(ITM_Wardrobe_ClassSelector_C) \
    x(ITM_DeepDive_Codename_C) \
    x(ITM_Grenade_HE_Base_C) \
    x(ITM_WarningAndMutator_C) \
    x(ITM_Season_Progress_TerminalVersion_C) \
    x(ITM_ClassLevelRequirement_C) \
    x(ITM_StatusScreen_PerkItem_C) \
    x(ITM_SkinIcon_C) \
    x(ITM_Challenge_InfoBox_C) \
    x(ITM_TopBar_CharacterIcon_C) \
    x(ITM_WarningWithPercent_C) \
    x(ITM_FactionSelect_C) \
    x(ITM_MasteryBar_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_C) \
    x(ITM_CommunityGoalReward_C) \
    x(ITM_BarGlass_Item_OilyOafBrew_SupporterEdition_C) \
    x(ITM_MissionBarDropPod_Objective_C) \
    x(ITM_RestoreSave_Resources_C) \
    x(ITM_BarGlass_Item_SkullCrusherAle_C) \
    x(ITM_UpgGear_SideBar_GrenadeSelect_GrenadeIcon_C) \
    x(ITM_Trading_DailyDeal_C) \
    x(ITM_EscapeMenu_MissionModifier_C) \
    x(ITM_BarGlass_Item_Backbreaker_C) \
    x(ITM_UnlockedCelebration_C) \
    x(ITM_MisSel_MissionIcon_C) \
    x(ITM_MisSel_MissionIconSmall_C) \
    x(ITM_CommunityGoal_ConsoleScreenV2_C) \
    x(ITM_SaveSlot_Entry_Header_C) \
    x(ITM_DeepDive_ObjectiveIcon_C) \
    x(ITM_WeaponAndPerkInfo_C) \
    x(ITM_UpgGear_ResourceCounter_C) \
    x(ITM_BarGlass_Item_C) \
    x(ITM_CharacterData_C) \
    x(ITM_CommunityGoalInformation_C) \
    x(ITM_CommunityGoalCountdown_C) \
    x(ITM_Wardrobe_ItemSelector_ToolTip_C) \
    x(ITM_CampaignItem_C) \
    x(ITM_SeasonPlagueHeartBonus_C) \
    x(ITM_ChaCus_ItemSelector_C) \
    x(WPN_PlagueSoaper_C) \
    x(WPN_DualMPs_C) \
    x(WPN_DetPack_Detonator_Driller_C) \
    x(WPN_RocketRifle_C) \
    x(WPN_JetPackItem_C) \
    x(WPN_SMG_OneHand_C) \
    x(WPN_PlasmaCarbine_C) \
    x(WPN_LaserPistol_C) \
    x(WPN_PipelineBuilder_C) \
    x(WPN_ChargeBlaster_C) \
    x(WPN_OilExtractor_C) \
    x(WPN_BurstPistol_C) \
    x(WPN_HeavyParticleCannon_C) \
    x(WPN_Pickaxe_C) \
    x(WPN_Pickaxe_Engineer_C) \
    x(WPN_FlameThrower_C) \
    x(WPN_PlatformGun_C) \
    x(WPN_MicroMissileLauncher_C) \
    x(WPN_MicrowaveGun_C) \
    x(WPN_SoapVacuum_C) \
    x(WPN_RockCracker_Builder_C) \
    x(WPN_AssaultRifle_C) \
    x(WPN_Revolver_C) \
    x(WPN_CombatShotgun_C) \
    x(WPN_Pickaxe_Gunner_C) \
    x(WPN_Crossbow_C) \
    x(WPN_Pickaxe_Scout_C) \
    x(WPN_FuelLine_Builder_C) \
    x(WPN_GrenadeLauncher_C) \
    x(WPN_Gatling_C) \
    x(WPN_Autocannon_C) \
    x(WPN_GooCannon_C) \
    x(WPN_GrapplingGun_C) \
    x(WPN_RecallableSentryGun_C) \
    x(WPN_DetPack_Detonator_C) \
    x(WPN_LaserPointer_C) \
    x(WPN_LineCutter_C) \
    x(WPN_ZipLineGun_C) \
    x(WPN_CoilGun_C) \
    x(WPN_FlareGun_C) \
    x(WPN_Cryospray_C) \
    x(WPN_M1000_C) \
    x(WPN_LockOnRifle_C) \
    x(WPN_DoubleDrills_C) \
    x(WPN_Extractor_C) \
    x(WPN_SawedOffShotgun_C) \
    x(WPN_ShieldRegeneratorItem_C) \
    x(WPN_Pickaxe_Driller_C) \
    x(WPN_Pistol_A_C) \
    x(InProgress) \
    x(BP_BaubleHanging_C) \
    x(BP_Donkey_C) \
    x(BP_DorettaHead_C) \
    x(BP_CharCustomizationConsole_C) \
    x(BP_EndscreenBarrel_C) \
    x(BP_ExplodingPlant_Large_C) \
    x(BP_CreeperVine_Base_C) \
    x(BP_DamageOnReloadComponent_BRT_C) \
    x(BP_PhaseBomb_C) \
    x(BP_CrystalFormations_SlantedPillars_Base_C) \
    x(BP_Invitation_C) \
    x(BP_GooCannon_GooPuddle_ImprovedPoison_C) \
    x(BP_TutorialManager_Base_C) \
    x(BP_ExplodingPlant_Medium_C) \
    x(BP_FuelLine_EndPoint_C) \
    x(BP_CrystalArch_01_C) \
    x(BP_CaretakerDroneAction_UNUSED_C) \
    x(BP_JetBootsBurnTrigger_C) \
    x(BP_ChangeCharacterConsole_C) \
    x(BP_HeightenedSense_Discharge_C) \
    x(BP_FlamingCoconut_C) \
    x(BP_TikiTorch_C) \
    x(BP_InfectedMulePreplacement_C) \
    x(BP_RockFormation_Stone_011_C) \
    x(BP_LargeCoral_2_C) \
    x(BP_Spider_Spitter_Leg_C) \
    x(BP_BarGlass_TunnelRat_C) \
    x(BP_WeaponIconGenerator_C) \
    x(BP_WalkingPlagueHeart_PlagueCloud_C) \
    x(BP_GunkSeed_C) \
    x(BP_FracturedMissionDNA_C) \
    x(BP_ChimneyGeyser05_Carved_C) \
    x(BP_Barley3_2_C) \
    x(BP_PetUsable_C) \
    x(BP_RadioactiveGlowinggGreenCrystal_Hazard_C) \
    x(BP_PheromoneAttackerPositioning_Propogated_C) \
    x(BP_BarGlass_GlyphidSlammer_C) \
    x(BP_Widget_DropPod_Complexity_C) \
    x(BP_PlagueWormPod_C) \
    x(BP_PlagueGroundSpike_C) \
    x(BP_Collectible_Barley_B1_C) \
    x(BP_AlienEgg_C) \
    x(BP_CribrariaPlant_C) \
    x(BP_GuntowerEvent_C) \
    x(BP_ItemRack_Simple_Vacuum_C) \
    x(BP_Azure_HureRoots_Base_C) \
    x(BP_CrystalFormations_SlantedPillars_01_C) \
    x(BP_BarGlass_LeafloversSpecial_C) \
    x(BP_MicroRocket_HE_C) \
    x(BP_Spider_TankAmber_Leg__C) \
    x(BP_Bosco_Rocket_Ice_C) \
    x(BP_DropPod_Landing_Salvage_C) \
    x(BP_ZipLineState_C) \
    x(BP_LaserPointerWaypoint_C) \
    x(BP_DashActivation_C) \
    x(BP_CrystalFormation_SpikyBunch_03_C) \
    x(BP_Heartstone_Claw_C) \
    x(BP_SmallMangroveRoot_4_C) \
    x(BP_SaltFormation_Large_1_C) \
    x(BP_NetworkPlayerController_C) \
    x(BP_PropHunt_VentBox_C) \
    x(BP_SmallMeteor_C) \
    x(BP_ExplodingGooPlant_Fast_Base_C) \
    x(BP_PipelineBuilder_Marker_C) \
    x(BP_Portal_C) \
    x(BP_MonitorPanel_NoMesh_C) \
    x(BP_Plague_MedbayHallway_Disinfection_C) \
    x(BP_ExplodingIcePlant_C) \
    x(BP_DiscordEoMConsole_C) \
    x(BP_Widget_DropPod_BiomeRadar_C) \
    x(BP_LongStemFungus_C) \
    x(BP_IconGenerator_C) \
    x(BP_Geyser_Air_C) \
    x(BP_BansheeModule_Component_C) \
    x(BP_PeelingBark_5_C) \
    x(BP_NausicaaTreeTrunk_5_C) \
    x(BP_SmallMangroveRoot_1_C) \
    x(BP_BarGlass_UnderhillDeluxe_C) \
    x(BP_BoscoVacuum_C) \
    x(BP_RivalBombNode_C) \
    x(BP_CroppaChunk_C) \
    x(BP_CreeperVine_Large_03_C) \
    x(BP_BarrelDispenserBeacon_C) \
    x(BP_CreateBombOnHit_C) \
    x(BP_XmasCandleBlock_Item_C) \
    x(BP_SpikeyPlant_C) \
    x(BP_SwarmerTunnelsBase_C) \
    x(BP_LockOnRifle_AoE_C) \
    x(BP_Azure_HugeRoots_Ground_01_C) \
    x(BP_SandArch_1_C) \
    x(BP_JetBootsBox_Spacerig_C) \
    x(BP_Boolo_Cap_C) \
    x(BP_PheromoneAttackerPositioning_C) \
    x(BP_CabinOwnerSign_C) \
    x(BP_BossFight_Heartstone_C) \
    x(BP_Azure_MagicCrystal_Base_C) \
    x(BP_ShieldRegenerator_C) \
    x(BP_EscortRefuelTarget_C) \
    x(BP_SandblastedRockIsland_2_C) \
    x(BP_HugeCrystalStar_2_Double_C) \
    x(BP_Azure_MagicCrystal_A_C) \
    x(BP_BarGlass_RockMaltbearer_C) \
    x(BP_WormholeLocation_Base_C) \
    x(BP_MeteorShowerTimer_C) \
    x(BP_SpaceRig_Bartender_C) \
    x(BP_MainFacility_DataVault_C) \
    x(BP_CombatShotgun_PoisonPlatforms_C) \
    x(BP_Hoxxes01_C) \
    x(BP_BarGlass_Standard_C) \
    x(BP_Drop_CamShake_C) \
    x(BP_PushingState_C) \
    x(BP_IceFormation_Claw_A_C) \
    x(BP_Count_Randoms_Widget_C) \
    x(BP_SelectCharacterOnlyConsole_C) \
    x(BP_MemorialQuotes_C) \
    x(BP_SmallMangroveRoot_2_C) \
    x(BP_FoamPuddle_C) \
    x(BP_Plaguesoaper_Dropped_Hologram_C) \
    x(BP_AmberChunk_C) \
    x(BP_NausicaaTreeTrunk_4_Fallen_C) \
    x(BP_BrokenDNA_1_C) \
    x(BP_CandleBlock_C) \
    x(BP_SpaceRig_Gamemode_C) \
    x(BP_HeavyParticleCannon_StickyFlame_C) \
    x(BP_ReturningPromotionKey_C) \
    x(BP_SeasonsConsole_C) \
    x(BP_EscortCannisterUsable_C) \
    x(BP_GlowingRedCrystal_2_C) \
    x(BP_ShieldLinkComponent_C) \
    x(BP_WaterballoonItem_C) \
    x(BP_Pipeline_Movement_C) \
    x(BP_AnimatedFoliage_Base_C) \
    x(BP_JukeBox_C) \
    x(BP_DropPod_Escape_Damaged_C) \
    x(BP_RockCracker_Segment_C) \
    x(BP_TextDisplay_C) \
    x(BP_BurrowComponent_C) \
    x(BP_GameInstance_C) \
    x(BP_ExplosiveEnemiesDamageSmall_C) \
    x(BP_StickySpiderWeb_C) \
    x(BP_StabberVine_Claw_C) \
    x(BP_PetUseSphere_C) \
    x(BP_Phys_Bauble01_C) \
    x(BP_Refinery_ProgressBar_C) \
    x(BP_Anniversary_WallLamp_C) \
    x(BP_PropHunt_BiohazardSuit_C) \
    x(BP_HUD_SpaceRig_C) \
    x(BP_Character_ShowroomStage_C) \
    x(BP_JadizChunk_C) \
    x(BP_DropPod_Landing_Escort_C) \
    x(BP_Crossbow_Projectile_Stuck_Chemical_C) \
    x(BP_Grenade_IFG_Area_Base_C) \
    x(BP_Grenade_Incendiary_Flame_C) \
    x(BP_ExplosiveEnemiesDamageTiny_C) \
    x(BP_Spider_Leg_Base_C) \
    x(BP_SalvageFuelCells_Beacon_C) \
    x(BP_PostProcessing_MagmaCaves_C) \
    x(BP_Lunar_DragonStatue_C) \
    x(BP_WallMaggot_C) \
    x(BP_Refinery_RocketLamp_C) \
    x(BP_CreateBombOnHit_DualMP_C) \
    x(BP_CaretakerShredderAction_C) \
    x(BP_RockCracker_StartPoint_C) \
    x(BP_ExplosiveBarrelDispenser_Platform_C) \
    x(BP_EscortDestination_C) \
    x(BP_FuelLine_Segment_C) \
    x(BP_Microwave_Heatsink_C) \
    x(BP_MangroveRock_03_C) \
    x(BP_Guntower_Module_RandomFire_C) \
    x(BP_IronChunk_C) \
    x(BP_EnemyControlState_C) \
    x(BP_CreeperVine_BendThroughGround_02_C) \
    x(BP_JetBootsBox_C) \
    x(BP_CaterpillarTrack_C) \
    x(BP_RockFormation_Stone_014_C) \
    x(BP_Spider_TankBoss_FracturedArmor_C) \
    x(BP_Boss_AoEAttack_C) \
    x(BP_BarGlass_BlackoutStout_C) \
    x(BP_Anniversary_BalloonCluster_C) \
    x(BP_TruckerBalls_C) \
    x(BP_PropHunt_EggHunt_Bunny_C) \
    x(BP_Promotion_Console_C) \
    x(BP_WormPlant_Animated_Magma_C) \
    x(BP_GiftBox_Weightless_C) \
    x(BP_CoilgunTrail_Base_C) \
    x(BP_Widget_DropPod_DangerLevel_C) \
    x(BP_DropSpike_Ice_C) \
    x(BP_ShootingRangeConsole_C) \
    x(BP_Phys_Crate_F_C) \
    x(BP_SmallMeteorSpawner_C) \
    x(BP_MarathonGuy_SprintBoostTime_C) \
    x(BP_RockFormation_2Platuaes_B_C) \
    x(BP_PhysicsTumbleweed_C) \
    x(BP_PingPongPlant_A_C) \
    x(BP_NetFungus_C) \
    x(BP_QuantriteChunk_C) \
    x(BP_NetworkPlayGameMode_C) \
    x(BP_Salvage_FuelPoint_C) \
    x(BP_GoldChunk_C) \
    x(BP_CreeperVine_Small_03_C) \
    x(BP_Phys_Barrel01_Red_C) \
    x(BP_Anniversary_Trophy6_InCave_C) \
    x(BP_HackingPodDrillDebris_C) \
    x(BP_PeelingBark_Double_3_C) \
    x(BP_HeightenedSenses_C) \
    x(BP_SnowPile_C) \
    x(BP_ExplosiveEnemiesDamageHuge_C) \
    x(BP_TipJarUsable_C) \
    x(BP_PlagueHeartShield_C) \
    x(BP_News_Monitor_C) \
    x(BP_LaserPointer_Marker_MovieMode_C) \
    x(BP_PointOfInterest_C) \
    x(BP_CaveLeechPlacementCarver_C) \
    x(BP_CrystalArch_2_Big_C) \
    x(BP_PatrolBot_Wheel_C) \
    x(BP_GooCannon_GooPuddle_C) \
    x(BP_IceCrevasse_Trap_C) \
    x(BP_PostProcessing_SandblastedCorridors_C) \
    x(BP_GreatEggHunt_ThrowableEggItem_C) \
    x(BP_PlayerCameraDrone_C) \
    x(BP_PoisonGasFungus_C) \
    x(BP_HugeLongRoot_2_C) \
    x(BP_DBR_Salvage_OldSupplyPod_C) \
    x(BP_EscortGarage_C) \
    x(BP_BarGlass_DarkMorkite_C) \
    x(BP_ToxicCatalystComponent_C) \
    x(BP_Sentry_PlasmaBeam_C) \
    x(BP_RainFallLocal_C) \
    x(BP_PropHunt_WorkTable_002_C) \
    x(BP_PlagueMeteor_Indicator_C) \
    x(BP_Crossbow_Projectile_Stuck_Pheromone_C) \
    x(BP_TrackMovementState_C) \
    x(BP_Kickable_Base_C) \
    x(BP_LargeThornBranch_3_NEW_C) \
    x(BP_BrokenDNA_4_AutoRot_C) \
    x(BP_TipJar_Base_Blueprint_C) \
    x(BP_PropHunt_Barrel_C) \
    x(BP_CrystalFormation_SpikyBunch_04_C) \
    x(BP_RegenerativeMissionBP_C) \
    x(BP_Ping_Widget_C) \
    x(BP_Spider_FrostCloud_C) \
    x(BP_CaretakerMortarAction_C) \
    x(BP_Caretaker_AoE_Attack_C) \
    x(BP_PhazyoniteChunk_C) \
    x(BP_Refinery_Extractor_C) \
    x(BP_DataCell_C) \
    x(BP_Collectible_Base_C) \
    x(BP_ElectricReload_STE_Component_C) \
    x(BP_RockFormation_Stone_12_C) \
    x(BP_LaserEventStarter_C) \
    x(BP_CozyTreeHollow_Double_B_C) \
    x(BP_DeepCSGWorld_C) \
    x(BP_XmasBauble_Item_C) \
    x(BP_ModularLamp_C) \
    x(BP_ProceduralController_C) \
    x(BP_WeatherEffect_C) \
    x(BP_SwarmerTunnels_variant_2_C) \
    x(BP_PeelingBark_Double_2_C) \
    x(BP_Swarmageddon_C) \
    x(BP_DwarfVanityItemTester_C) \
    x(BP_MultiStageEventStarter_C) \
    x(BP_EscortMule_C) \
    x(BP_NausicaaTreeTrunk_Base_C) \
    x(BP_PostProcessing_CharSelect_C) \
    x(BP_PickaxeRandomizer_C) \
    x(BP_CrystalFormations_SlantedPillars_03_Small_C) \
    x(BP_EyeForEye_SYIHpassive_PerkComponent_C) \
    x(BP_RivalBomb_Cable_C) \
    x(BP_LowGravity_C) \
    x(BP_IntoxicationComponent_C) \
    x(BP_NausicaaTreeTrunk_6_C) \
    x(BP_Azure_ThinHangingRoots_SM_AzureWealdVines_02_C) \
    x(BP_Spider_RapidShooter_Leg_C) \
    x(BP_GreatEggHunt_KnockEgg_C) \
    x(BP_BeachParty_Inflatable_InCave_C) \
    x(BP_RepairTreasureboxItem_C) \
    x(BP_Crossbow_Projectile_Stuck_Fire_C) \
    x(BP_SupplyPod_Ammo_C) \
    x(BP_NausicaaTreeTrunk_3_Fallen_C) \
    x(BP_PropHunt_PaperStack_C) \
    x(BP_MainFacility_PowerCable_C) \
    x(BP_DropToTerrainDebris_Base_C) \
    x(BP_GooCannon_GooPuddle_ImprovedSlow_C) \
    x(BP_FlyingState_C) \
    x(BP_SmallMangroveRoot_3_C) \
    x(BP_Halloween_SmokyPumpkin_C) \
    x(BP_Heartstone_DefensiveCrystal_C) \
    x(BP_UITesting_C) \
    x(BP_Crossbow_Projectile_Stuck_Ice_C) \
    x(BP_PlasmaTrail_LineCutter_C) \
    x(BP_PersistentExplosionEffect_LineCutter_C) \
    x(BP_MagmaQuakeCrevasse_Trap_C) \
    x(BP_StickyFlame_C) \
    x(BP_StartMenu_GameMode_C) \
    x(BP_Anniversary_HeliumTank_C) \
    x(BP_FoamRocket_C) \
    x(BP_ThrowableNisse_C) \
    x(BP_DorettaHead_SpaceRig_C) \
    x(BP_Azure_HugeRoots_Single_04_C) \
    x(BP_StickyFrost_C) \
    x(BP_Spider_RadiationCloud_C) \
    x(BP_SteelDrum_C) \
    x(BP_Nametag_Actor_C) \
    x(BP_MovieMode_VanityCharacter_C) \
    x(BP_FireCrackerItem_C) \
    x(BP_MangroveRock_02_C) \
    x(BP_Minehead_Sentry_C) \
    x(BP_IceLight_C) \
    x(BP_GlowingBlueCrystal_Base_C) \
    x(BP_SR_PlayerControllerBase_C) \
    x(BP_ExplodingGooPlant_Puddle_C) \
    x(BP_FriendlyParasite_Mechanical_C) \
    x(BP_CharacterTeleportPlacement_C) \
    x(BP_CabinController_C) \
    x(BP_CrystalFormations_SlantedPillars_03Rot_C) \
    x(BP_PostProcessing_LushDownpour_C) \
    x(BP_CleanupPod_Marker_C) \
    x(BP_Plague_Rooms_Disinfection_C) \
    x(BP_ExplodingPlantA_Large_C) \
    x(BP_HotSpring_C) \
    x(BP_GlowingBlueCrystal_1_C) \
    x(BP_PLatformMushroom_M_C) \
    x(BP_SandArch_3_C) \
    x(BP_GooCannon_Cannister_C) \
    x(BP_FacilityTurretDrone_C) \
    x(BP_BoscoSkinRewarder_C) \
    x(BP_DropSpike_Salt_C) \
    x(BP_SupplyPod_Spawn_Beacon_C) \
    x(BP_CameraDrone_SplineMesh_C) \
    x(BP_DirtChunk_C) \
    x(BP_Refinery_Depositor_C) \
    x(BP_ExplodingPlant_Base_C) \
    x(BP_DeathStats_C) \
    x(BP_Mushroom_03_C) \
    x(BP_BarGlass_FlintlockLager_C) \
    x(BP_BarGlass_C) \
    x(BP_HumongousFungus_Base_C) \
    x(BP_Micro_Missile_Mag_C) \
    x(BP_HologramBiome_C) \
    x(BP_CrystalRockPillar_1_C) \
    x(BP_UnknownArtifact_C) \
    x(BP_Terminator_ElectricAttack_C) \
    x(BP_PostProcessing_FungusBogs_C) \
    x(BP_Barley3_3_C) \
    x(BP_Salvage_FuelPod_C) \
    x(BP_Azure_VoidBasket_C) \
    x(BP_CrystalFormationsSpikyBunch_Base_C) \
    x(BP_ThornVinesChokingWoodRoots_2_C) \
    x(BP_PropHunt_Trolley_C) \
    x(BP_ExplodingGooPlant_Fast_Large_C) \
    x(BP_LargeLongRootLoop_2_C) \
    x(BP_NausicaaTreeTrunk_4_C) \
    x(BP_GooCannon_Cannister_TP_C) \
    x(BP_CompleteMissionScreen_DorettaHead_C) \
    x(BP_Anniversary_CocktailGlass_C) \
    x(BP_Phys_Anniversary_Bottle_C) \
    x(BP_Phys_Barrel_Hoop_C) \
    x(BP_PhotographyState_C) \
    x(BP_SpacerigSpectator_C) \
    x(BP_DamageTriggerComponent_C) \
    x(BP_RivalFortifiedNodePlacer_C) \
    x(BP_ExplodingGooPlant_Fast_Medium_C) \
    x(BP_RockCracker_EndPoint_C) \
    x(BP_Snowball_C) \
    x(BP_ParalyzedState_C) \
    x(BP_SwarmerTunnels_variant_5_C) \
    x(BP_Component_Macros_C) \
    x(BP_RadioactiveBlobPlant_02_C) \
    x(BP_PoisonGasFungus_PoisonGasCloud_C) \
    x(BP_DualMug_C) \
    x(BP_Mainfacility_ShieldEmitter_ForceFieldProjector_C) \
    x(BP_Damage_Cloud_Flamable_Base_C) \
    x(BP_DeepDive_SEQ_DropPod_C) \
    x(BP_Motherlode_MiningHeadDropLocation_C) \
    x(BP_DLC_Audio_C) \
    x(BP_LargeCoral_1_C) \
    x(BP_SupplyPod_Marker_C) \
    x(BP_Spider_PlagueCloud_DiffuseSpawn_C) \
    x(BP_SmallMeteor_Indicator_C) \
    x(BP_Actor_Macros_C) \
    x(BP_Azure_HugeRoots_1_C) \
    x(BP_PostProcessing_SpaceRig_C) \
    x(BP_BarGlass_RandoWeisser_C) \
    x(BP_Branch_A_C) \
    x(BP_TunnelBlocker_C) \
    x(BP_WormholeLocation_OutsideBase_C) \
    x(BP_EnemySpawnerOwner_C) \
    x(BP_SwarmerTunnels_variant_4_C) \
    x(BP_StickySpiderWeb_New_Corner_C) \
    x(BP_Azure_MagicCrystal_C_C) \
    x(BP_GunkSeed_Hanger_C) \
    x(BP_SlimyFungus_XL_C) \
    x(BP_Geyser_Frost_C) \
    x(BP_Gem_Jadiz_C) \
    x(BP_Armor_Gunner_C) \
    x(BP_Spacerig_Comet_C) \
    x(BP_Barley2_1_C) \
    x(BP_Collectible_Barley_Base_C) \
    x(BP_WeaponSkinRewarder_C) \
    x(BP_ChimneyGeyser02_Carved_C) \
    x(BP_CreeperVine_Small_01_C) \
    x(BP_FuelLine_StartPoint_C) \
    x(BP_MorchellaFungus_C) \
    x(BP_OilShaleChunk_C) \
    x(BP_QuickRecoveryLogic_C) \
    x(BP_CameraDrone_Flare_C) \
    x(BP_FossilsBase_C) \
    x(BP_ElectricReload_DMG_Component_C) \
    x(BP_HandheldTablet_3P_C) \
    x(BP_HugeLongRoot_1_C) \
    x(BP_MissionControl_TrespassingWarning_C) \
    x(BP_GS_Tutorial_C) \
    x(BP_RedSugarRocksLogic_C) \
    x(BP_BarGlass_WormholeSpecial_C) \
    x(BP_RewardUsableComponent_C) \
    x(BP_AudioControl_LowHealth_C) \
    x(BP_JetBootsBoxLid_C) \
    x(BP_LocalWaveTrigger_C) \
    x(BP_ShowroomStageSeason_C) \
    x(BP_CrystalFormations_SlantedPillars_04_C) \
    x(BP_BarGlass_MacteraBrew_C) \
    x(BP_TutorialDroppodLocation_C) \
    x(BP_Anniversary_RoundLamp_C) \
    x(BP_Xmas_SpaceSanta_C) \
    x(BP_PostProcessing_HollowBough_C) \
    x(BP_CreeperVine_Large_01_C) \
    x(BP_SpringDwarfMiner_C) \
    x(BP_FSDCameraManager_C) \
    x(BP_Bosco_C) \
    x(BP_DropPod_Landing_NoMule_C) \
    x(BP_Fossil_BigLizard_Skull01_C) \
    x(BP_SpawnDroppodLocationItem_C) \
    x(BP_PlayerController_C) \
    x(BP_StickySpiderWeb_New_C) \
    x(BP_Spider_Exploder_Leg_C) \
    x(BP_GreatEggHunt_HiddenEgg_C) \
    x(BP_TransmitterNode_C) \
    x(BP_Mushroom_01_C) \
    x(BP_TurretbaseDebris_C) \
    x(BP_SpiderEgg3_C) \
    x(BP_WalkingState_C) \
    x(BP_VampireComponent_C) \
    x(BP_Plague_Spore_Tower_Carver04_C) \
    x(BP_PlatformIcePlant_C) \
    x(BP_PostProcessing_RadioactiveZone_C) \
    x(BP_Spider_PlagueCloud_Small_C) \
    x(BP_MiniMule_Salvage_C) \
    x(BP_RicochetArrow_Component_C) \
    x(BP_EnorChunk_C) \
    x(BP_Armor_Engineer_C) \
    x(BP_ItemRack_Simple_C) \
    x(BP_HoopsGame_C) \
    x(BP_MissionStats_C) \
    x(BP_SentryGun_Moveable_Heavy_C) \
    x(BP_ItemRack_Simple_Soaper_C) \
    x(BP_SentryGun_Moveable_C) \
    x(BP_Lunar_HangingFireCracker_C) \
    x(BP_BarGlass_RockyMountain_C) \
    x(BP_AmberEvent_C) \
    x(BP_LostPackStart_C) \
    x(BP_Electrobeam_C) \
    x(BP_ThornVinesChokingWoodRoots_1_C) \
    x(BP_Azure_HugeRoots_Single_05_C) \
    x(BP_TowerModuleController_C) \
    x(BP_BarGlass_BlacklockLager_C) \
    x(BP_Count_Randoms_C) \
    x(BP_Anniversary_Sparkler_C) \
    x(BP_MinersManual_Hologram_C) \
    x(BP_Barley2_4_C) \
    x(BP_IronWillActivation_C) \
    x(BP_OxygenTank_C) \
    x(BP_PersistentExplosionEffect_EPC_C) \
    x(BP_HugeCrystalStar_3_C) \
    x(BP_RockFormation_Stone_010_C) \
    x(BP_Barley4_1_C) \
    x(BP_SpaceRig_Cabin01_C) \
    x(BP_AutoReloadPerkActivation_C) \
    x(BP_Skysphere_HoxxesStars_C) \
    x(BP_Tutorial_Hint_BrokenMiniMule_C) \
    x(BP_PingPongPlant_B_C) \
    x(BP_Geyser_Lava_C) \
    x(BP_PilotingState_C) \
    x(BP_GlyphidImpactAudio_C) \
    x(BP_Azure_Flower_Insect_swarm_C) \
    x(BP_LunarFestival_Lamp01_C) \
    x(BP_Screen_C) \
    x(BP_UmaniteChunk_C) \
    x(BP_BarGlass_ArkenStout_C) \
    x(BP_SmallGenerator_C) \
    x(BP_Plague_BioTank_Big_C) \
    x(BP_FallingState_C) \
    x(BP_Azure_HugeRoots_SingleGround_06_C) \
    x(BP_Bulkhead01_C) \
    x(BP_CaretakerTurretAction_C) \
    x(BP_HugeThornBranch_Base_C) \
    x(BP_RefineryDNA_C) \
    x(BP_Refinery_Extractor_Blueprint_C) \
    x(BP_AzureWealdArch_1_C) \
    x(BP_GreatEggHunt_BunnyPlush_C) \
    x(BP_BomberAcidPuddle_C) \
    x(BP_BossFight_PlagueMeteor_C) \
    x(BP_Barley2_2_C) \
    x(BP_RadioactiveBlobPlant_01_C) \
    x(BP_Guntower_Module_LMG_C) \
    x(BP_BarGlass_BurningLove_C) \
    x(BP_Hologram_C) \
    x(BP_PumpkinFace_Item_C) \
    x(BP_ResourcePouch_C) \
    x(BP_HoverBootsBurnTrigger_C) \
    x(BP_BrokenDNA_3_C) \
    x(BP_Azure_HugeRoots_SingleGround_04_C) \
    x(BP_Azure_MagicHole_C) \
    x(BP_MangroveRock_04_C) \
    x(BP_Grenade_NeedleSprayer_C) \
    x(BP_MarathonGuy_SprintBoost_C) \
    x(BP_SingleMug_C) \
    x(BP_PlagueSpawnTarget_C) \
    x(BP_Tentacle_Part_C) \
    x(BP_ShieldBattery_C) \
    x(BP_WallMaggot_Deep_C) \
    x(BP_DeadTree_A_C) \
    x(BP_CreepyEyes_C) \
    x(BP_BismorChunk_C) \
    x(BP_Guntower_Module_RadialFire_new_C) \
    x(BP_SandArch_2_C) \
    x(BP_HydraWeedCoreFragment_03_C) \
    x(BP_MissionControlPointlight_C) \
    x(BP_OxygenRich_C) \
    x(BP_CrystalFormations_SlantedPillars_04Rot_C) \
    x(BP_Refinery_C) \
    x(BP_ExploderInfestation_C) \
    x(BP_BarGlass_PotsOGold_C) \
    x(BP_LargeLongRootLoop_4_C) \
    x(BP_ShortStemFungus_C) \
    x(BP_TutorialComponent_C) \
    x(BP_AudioVolume_DiscoverCave_C) \
    x(BP_PropHunt_BioTank_Small_C) \
    x(BP_GuntowerActivationPlatfrom_C) \
    x(BP_Plague_Spore_Tower_InfectionSource_C) \
    x(BP_Azure_UmbraSeeker_C) \
    x(BP_CreeperVine_BendThroughGround_01_C) \
    x(BP_Foliage_OpenOnProximity_C) \
    x(BP_RadioactiveGlyphidDeathGas_C) \
    x(BP_Halloween_CandleBlock_C) \
    x(BP_DropPod_Escape_NoMule_C) \
    x(BP_MangroveRock_Base_C) \
    x(BP_RadarDish01_C) \
    x(BP_Phys_GreatEggHunt_PaintedEgg_C) \
    x(BP_PropHunt_Throwable_C) \
    x(BP_Salvage_Point_Uplink_C) \
    x(BP_DeepDiveConsole_C) \
    x(BP_OldSupplyPod_Salvage_C) \
    x(BP_New_HeavyRain_Lush_C) \
    x(BP_TetherDispenserBeacon_C) \
    x(BP_BoscoStateDisplay_C) \
    x(BP_Pipeline_Start_C) \
    x(BP_LargeCoral_4_C) \
    x(BP_TutorialManager_Spacerig_C) \
    x(BP_DepthCount_C) \
    x(BP_BossFight_WalkingPlagueHeart_C) \
    x(BP_Halloween_Skull_C) \
    x(BP_DownedBomb_C) \
    x(BP_BarGlass_OilyOafBrew_SupporterEdition_C) \
    x(BP_Turret_Arc_Indicator_C) \
    x(BP_SwarmerTunnel_C) \
    x(BP_DepthCountWidget_C) \
    x(BP_RadarDish02_C) \
    x(BP_BarGlass_SkullCrusherAle_C) \
    x(BP_GameState_SpaceRig_C) \
    x(BP_LargeLongRootLoop_1_C) \
    x(BP_LargeThornBranch_2_NEW_C) \
    x(BP_HangingMistCloud_Azure_C) \
    x(BP_GlowingRedCrystal_1_C) \
    x(BP_ShieldDisruption_C) \
    x(BP_GameData_C) \
    x(BP_LostPack_C) \
    x(BP_HugeTrippleRoot_1_C) \
    x(BP_FloatingLightPlant2_C) \
    x(BP_SandArch_Base_C) \
    x(BP_ItemMarker_Base_C) \
    x(BP_GreenMaggot_AcidCloud_C) \
    x(BP_BerzerkComp_C) \
    x(BP_DropPod_Escape_Escort_C) \
    x(BP_GlowingPlant_C) \
    x(BP_Lunar2023_RabbitStatue_InCave_C) \
    x(BP_Collectible_Simple_C) \
    x(BP_SpiderEgg2_C) \
    x(BP_HugeCrystalStar_Base_C) \
    x(BP_FrozenState_C) \
    x(BP_AttackablePiplinesegmentActor_C) \
    x(BP_LaserPointer_Marker_C) \
    x(BP_PeelingBark_Double_1_C) \
    x(BP_NausicaaTreeTrunk_2_C) \
    x(BP_PlagueController_C) \
    x(BP_ExplosiveBoil_C) \
    x(BP_PickaxeIconGenerator_C) \
    x(BP_PlayerController_SpaceRig_C) \
    x(BP_MainShieldActvator_C) \
    x(BP_BarGlass_SeasonedMoonrider_C) \
    x(BP_GameState_C) \
    x(BP_CrystalFormations_SlantedPillars_01Rot_C) \
    x(BP_Endscreen_Drone_C) \
    x(BP_MissionStatScreen_C) \
    x(BP_Swarmer_Attachment_C) \
    x(BP_MissionControl_MemorialHallWelcome_C) \
    x(BP_TetherDispenser_C) \
    x(BP_RotatingSpotlight01_C) \
    x(BP_Phys_GiftBox01_C) \
    x(BP_Facility_PowerStation_GeneratorBase_C) \
    x(BP_TurretEMPDischarge_Indicator_C) \
    x(BP_DropPod_LandingZone_C) \
    x(BP_RedSugarChunk_C) \
    x(BP_PlagueWarning_C) \
    x(BP_Depositable_C) \
    x(BP_Refinery_ProjectorLight_C) \
    x(BP_CreeperVine_Large_02_C) \
    x(BP_MagniteChunk_C) \
    x(BP_CribrariaPlant_C_C) \
    x(BP_Fossil_C) \
    x(BP_DropPod_Escape_Base_C) \
    x(BP_Crossbow_Projectile_Stuck_Electric_C) \
    x(BP_TurretEMPDischarge_C) \
    x(BP_LargeCoral_6_C) \
    x(BP_DonkeyDestinationMarker_C) \
    x(BP_PostProcessing_AzureWeald_C) \
    x(BP_ConeAttackBase_C) \
    x(BP_Audio_Macros_C) \
    x(BP_Zhukov_IceMines_C) \
    x(BP_GameMacros_C) \
    x(BP_CreeperVine_BendThroughGround_03_C) \
    x(BP_NausicaaTreeTrunk_1_C) \
    x(BP_StickySpiderWeb_New_Big_C) \
    x(BP_BarGlass_GlyphidSlammer_Support_C) \
    x(BP_WalkingPlagueheart_SlimeTrailPuddle_C) \
    x(BP_Spider_Lobber_Puddle_C) \
    x(BP_SpectatorBase_C) \
    x(BP_ForgeScreen_C) \
    x(BP_Anniversary_MiniChandelier_C) \
    x(BP_FoamPuddle_WalkingPlagueheart_C) \
    x(BP_CaterpillarTrack_Right_C) \
    x(BP_Bosco_Rocket_Frag_C) \
    x(BP_GhostMutator_C) \
    x(BP_RefineryLanding_C) \
    x(BP_CraftingConsole_C) \
    x(BP_HangingDustCloud_C) \
    x(BP_PickaxeConsole_C) \
    x(BP_CreeperVine_ThroughGround_01_C) \
    x(BP_Grenade_IFG_Area_SlowAndWeak_C) \
    x(BP_EventSpawnTimer_C) \
    x(BP_RockCrackerPod_Beacon_C) \
    x(BP_GrabbedState_C) \
    x(BP_ShooterQueen_Projectile_AcidCloud_C) \
    x(BP_WaterballoonBucket_C) \
    x(BP_Salvage_Point_C) \
    x(BP_LostPackDebrisPart_C) \
    x(BP_WallSaw_C) \
    x(BP_VP_Pickaxe_C) \
    x(BP_SentryGun_Redeployable_Heavy_C) \
    x(BP_AttachedState_C) \
    x(BP_BrokenDNA_Base_C) \
    x(BP_Damage_Cloud_Base_C) \
    x(BP_CrystalFormations_SlantedPillar_Solo_2_C) \
    x(BP_Facility_Tentacle_SpawnPoint_C) \
    x(BP_Plague_Spore_Tower_Carver03_C) \
    x(BP_Refinery_Target_C) \
    x(BP_CrystalFormation_SpikyBunch_01_C) \
    x(BP_LureTarget_C) \
    x(BP_Phys_BeachBall_C) \
    x(BP_Donkey_Escort_C) \
    x(BP_SupplyDropToTerrainLogic_C) \
    x(BP_ThornVinesChokingWoodRoots_3_C) \
    x(BP_SmallLavaGeyser_C) \
    x(BP_Halloween_Ghost_C) \
    x(BP_WalkingPlagueheart_PlagueheartCollectionShoutManager_C) \
    x(BP_RewardFrame_C) \
    x(BP_PlatformMushroom_Base_C) \
    x(BP_TutorialTriggerManager_C) \
    x(BP_InCaveOktoberfestMug_C) \
    x(BP_NitraChunk_C) \
    x(BP_Xmas_CandyCane_C) \
    x(BP_BarGlass_Random_C) \
    x(BP_LasePointer_SecondaryMarker_C) \
    x(BP_IconGenerationManager_C) \
    x(BP_CoralTongue_Animated_C) \
    x(BP_Azure_MagicCrystal_C) \
    x(BP_DynamicReverb_C) \
    x(BP_CreeperVine_Small_02_C) \
    x(BP_BarrelDispenser_C) \
    x(BP_MeteorShower_C) \
    x(BP_AnimatedArrow_C) \
    x(BP_QuickJoinGameConsole_C) \
    x(BP_PlayerState_C) \
    x(BP_ThornVinesChokingWoodRoots_Base_C) \
    x(BP_SeeYouInHellField_C) \
    x(BP_Grenade_Neurotoxin_Cloud_C) \
    x(BP_FacilityTentacleManager_C) \
    x(BP_Spider_AcidCloud_C) \
    x(BP_PlagueHeart_C) \
    x(BP_New_SnowStorm_C) \
    x(BP_DeadState_C) \
    x(BP_XmasGift_Item_C) \
    x(BP_CoreInfuser_Rewards_Selector_C) \
    x(BP_Quake_C) \
    x(BP_BarrelSpawner_C) \
    x(BP_GreatEggHunt_PickupPile_C) \
    x(BP_Lunar_FirecrackerThrowables_C) \
    x(BP_CleanupPod_WalkingPlagueHeart_C) \
    x(BP_DropPod_Landing_C) \
    x(BP_BaseSpaceRigConsole_C) \
    x(BP_Widget_DropPod_MissionType_C) \
    x(BP_TentacleMeleeAttack_C) \
    x(BP_EletrocutedArrow_C) \
    x(BP_HugeRoots_Base_C) \
    x(BP_DiscordInstantUsable_C) \
    x(BP_Azure_HugeRoots_SingleGround_05_C) \
    x(BP_PlagueMeteorTimer_C) \
    x(BP_RockCrackerPod_C) \
    x(BP_MainFacility_ShieldEmitter_Hologram_C) \
    x(BP_Facility_PowerStation_ShieldGenerator_C) \
    x(BP_PeelingBark_1_C) \
    x(BP_ReverbVolume_C) \
    x(BP_E3trailer_AsteroidField_C) \
    x(BP_PostProcessing_CrystalCaves_C) \
    x(BP_LargeLongRootLoop_3_C) \
    x(BP_LargeCoral_Base_C) \
    x(BP_OldSupplyPod_FailSmokeCloud_C) \
    x(BP_EnorEmd_C) \
    x(BP_FireCracker_C) \
    x(BP_DrippingPlant_C) \
    x(BP_EnemyShowroomController_C) \
    x(BP_PeelingBark_3_C) \
    x(BP_MouthPlant_C) \
    x(BP_DiscordConsoleWhite_C) \
    x(BP_CreeperVine_Large_04_C) \
    x(BP_TentacleBurrowAttack_C) \
    x(BP_AudioVolume_Reverb_MediemCave_C) \
    x(BP_HydraWeedCoreFragment_02_C) \
    x(BP_Mactera_Shooter_Attack_Elite_C) \
    x(BP_Hologram_Hoxxes_C) \
    x(BP_SwarmerTunnels_variant_6_C) \
    x(BP_GravitySwitch_C) \
    x(BP_ResupplierLogic_C) \
    x(BP_BarGlass_Gutwrecker_C) \
    x(BP_PassedOut_C) \
    x(BP_SupplyPod_Spawn_C) \
    x(BP_UsingState_C) \
    x(BP_HugeCrystalStar_5_Double_C) \
    x(BP_Widget_DropPod_AltitudeMeter_C) \
    x(BP_PlagueHeartShield_Base_C) \
    x(BP_CactusShooterPlant_C) \
    x(BP_Mactera_Heavy_ProjectileAttack_C) \
    x(BP_CleanupPod_Beacon_C) \
    x(BP_FadeScreenSubSystem_C) \
    x(BP_Phys_Haybale_C) \
    x(BP_CribrariaPlant_A_C) \
    x(BP_RivalBombEvent_C) \
    x(BP_Fossil_BigLizard_Ribcage_C) \
    x(BP_HureRoots_Base_C) \
    x(BP_Azure_CombaCharm_Egg_C) \
    x(BP_BarGlass_SmartStout_C) \
    x(BP_MemorialScreenSpeedButton_C) \
    x(BP_PostProcessing_Tutorial_C) \
    x(BP_TentacleGrab_C) \
    x(BP_DropPod_Rig_C) \
    x(BP_SentryItem_PlaceMarker_C) \
    x(BP_SpinningFan01_C) \
    x(BP_BioTank_Small_C) \
    x(BP_Barley1_1_C) \
    x(BP_ZipLineConnector_C) \
    x(BP_LockOnBeam_C) \
    x(BP_ExplosiveReloadComponent_C) \
    x(BP_CharacterShowroomController_C) \
    x(BP_IceCrevasse_Trap_Big_C) \
    x(BP_TutorialConsole_C) \
    x(BP_EventParticipant_C) \
    x(BP_ChimneyGeyser01_Carved_C) \
    x(BP_ElevatorPlant_C) \
    x(BP_PostProcessing_SaltCaves_C) \
    x(BP_Armor_Driller_C) \
    x(BP_Phys_Newsstand_FreeBeer_C) \
    x(BP_Pipeline_StatusLamp_C) \
    x(BP_PlayerState_Tutorial_C) \
    x(BP_Salvage_Point_Base_C) \
    x(BP_DropSpike_Base_C) \
    x(BP_JetBootsMovement_C) \
    x(BP_ExplodingPlantA_Medium_C) \
    x(BP_Anniversary_Chandelier_C) \
    x(BP_PlayerControllerBase_C) \
    x(BP_MeteorSpawner_C) \
    x(BP_Mushroom_Base_C) \
    x(BP_CaveVine_C) \
    x(BP_NewSandStorm_C) \
    x(BP_HackerJunk_Can_C) \
    x(BP_SentryGun_MoveMarker_C) \
    x(BP_InflatablePretzel_C) \
    x(BP_NoMovementState_C) \
    x(BP_Crystal_VictoryScreen_C) \
    x(BP_MicroRocket_Base_C) \
    x(BP_RockFormation_Stone_009_C) \
    x(BP_GreatEggHunt_ThrowableEgg_C) \
    x(BP_Apoca_Bloom_C) \
    x(BP_Widget_DropPod_GarbageGen_C) \
    x(BP_Empty_C) \
    x(BP_Geyser_Sand_C) \
    x(BP_HydraWeedCoreFragment_01_C) \
    x(BP_Phys_Pumpkin_C) \
    x(BP_GreatEggHunt_Bunny_InCave_C) \
    x(BP_SpacerigTrashCompactor_C) \
    x(BP_PeelingBark_2_C) \
    x(BP_ConfettiPlane_C) \
    x(BP_Mushroom_02_C) \
    x(BP_SmallLavaGeyserFiledOrigin_C) \
    x(BP_MangroveRock_01_C) \
    x(BP_BombSpitter_C) \
    x(BP_CampaignManager_C) \
    x(BP_FacilityElectricAttack_C) \
    x(BP_WaterBalloon_C) \
    x(BP_Collectible_Barley_B2_C) \
    x(BP_Refinery_Lamp_C) \
    x(BP_Endscreen_Lamp_C) \
    x(BP_Spider_PlagueCloud_C) \
    x(BP_Plague_VialDispenser_C) \
    x(BP_JumpBoots_C) \
    x(BP_BrokenDNA_5_AutoRot_C) \
    x(BP_AzureWealdArch_3_C) \
    x(BP_Phys_GreatEggHunt_InflatableCarrot_C) \
    x(BP_PineconeSpawner_Base_C) \
    x(BP_TracerManager_C) \
    x(BP_BarGlass_OilyOafBrew_C) \
    x(BP_HackedPatrolBotComponent_C) \
    x(BP_RivalIncursionWarning_C) \
    x(BP_Crossbow_Electrobeam_C) \
    x(BP_SpawnerEyeComponent_C) \
    x(BP_Phys_Newsstand_Oktoberfest_C) \
    x(BP_PlagueMeteor_C) \
    x(BP_CameraDrone_FlareProjectile_C) \
    x(BP_Azure_CombaCharm_C) \
    x(BP_HugeRoots_1_C) \
    x(BP_CozyTreeHollow_Tripple_C) \
    x(BP_MonitorPanel_C) \
    x(BP_SphereTrigger_C) \
    x(BP_SoapVacuum_Dropped_Hologram_C) \
    x(BP_Coilgun_HellfireSegment_OLD_C) \
    x(BP_HugeTrippleRoot_2_C) \
    x(BP_Barley3_4_C) \
    x(BP_Object_Macros_C) \
    x(BP_PropHunt_Anniversary_Bottle_C) \
    x(BP_GuntowerWeakpoint_C) \
    x(BP_SaltFormation_Large_2_C) \
    x(BP_SentryGun_MoveMarker_Heavy_C) \
    x(BP_Compressed_Gold_C) \
    x(BP_DetPack_Charge_C) \
    x(BP_MOD_MakeElite_C) \
    x(BP_ImpactCompensators_C) \
    x(BP_RockEnemiesEvent_C) \
    x(BP_Pipeline_Build_Hologram_C) \
    x(BP_ExplodingPlantA_Small_C) \
    x(BP_DreadnoughtEgg_C) \
    x(BP_JobsConsole_C) \
    x(BP_CoilgunTrail_Burn_C) \
    x(BP_CozyTreeHollow_Single_C) \
    x(BP_HugeRoots_2_C) \
    x(BP_TreasureBox_C) \
    x(BP_BoscoConsole_C) \
    x(BP_DiscordConsole_C) \
    x(BP_Chimney_Geyser_Carved_Base_C) \
    x(BP_PostProcessing_IceCaves_C) \
    x(BP_MorkiteChunk_C) \
    x(BP_RockFormation_Base_C) \
    x(BP_HugeCrystalStar_4_Low_C) \
    x(BP_CrystalArch_01_Big_C) \
    x(BP_Mactera_TrippleShooter_Attack_Elite_C) \
    x(BP_GameMode_C) \
    x(BP_RecallableArrow_Component_C) \
    x(BP_Geyser_Base_C) \
    x(BP_SpacerigWeapon_C) \
    x(BP_SpiderEgg_Base_C) \
    x(BP_CribrariaPlant_B_C) \
    x(BP_EscortGarage_Beacon_C) \
    x(BP_Extractor_Lamp_C) \
    x(BP_PassiveFoliage_Base_C) \
    x(BP_Azure_MagicCrystal_B_C) \
    x(BP_LootbugAttach_C) \
    x(BP_Pumpkin_Item_C) \
    x(BP_LunarFestival_LampRandom_C) \
    x(BP_JetBootsBoxSpawner_C) \
    x(BP_FacilityCore_DataRack_C) \
    x(BP_MuleLeg_C) \
    x(BP_CrystalArch_Base_C) \
    x(BP_SandblastedRockIsland_3_C) \
    x(BP_Halloween_Skull_Throwable_C) \
    x(BP_BeastMaster_C) \
    x(BP_PeelingBark_4_C) \
    x(BP_BarGlass_BlackreachBlonde_C) \
    x(BP_Meet_Attack_C) \
    x(BP_Spider_Shooter_Leg_C) \
    x(BP_Azure_ThinHangingRoots_SM_AzureWealdVines_04_C) \
    x(BP_BomberAcidPuddle_Ice_C) \
    x(BP_GreatEggHunt_Cuties_C) \
    x(BP_CaretakerActionBase_C) \
    x(BP_SaltFormations_Base_C) \
    x(BP_OxygenTankSound_C) \
    x(BP_EscortGem_Heartstone_C) \
    x(BP_Pipeline_Segment_C) \
    x(BP_Donkey_Facility_C) \
    x(BP_SentryGun_Redeployable_C) \
    x(BP_Gem_Aquarq_C) \
    x(BP_PlagueHeartShield_A_C) \
    x(BP_MemorialWall_C) \
    x(BP_Phys_Barrel01_C) \
    x(BP_ExplosiveEnemiesDamageLarge_C) \
    x(BP_Donkey_Salvage_C) \
    x(BP_GreatEggHunt_EggWithBow_C) \
    x(BP_RivalFortifiedNode_C) \
    x(BP_MiniPlagueTower_C) \
    x(BP_PlayerStart_C) \
    x(BP_Plague_Spore_Tower_Carver05_C) \
    x(BP_Spider_Grunt_Leg_C) \
    x(BP_Spider_Tank_Leg_C) \
    x(BP_MatrixCore_Tester_C) \
    x(BP_SandblastedRockIsland_C) \
    x(BP_BarGlass_DUMMY_C) \
    x(BP_PropHunt_Chair003_C) \
    x(BP_CrystalFormations_SlantedPillars_05_C) \
    x(BP_CrystalFormations_SlantedPillar_Solo_Skinny_C) \
    x(BP_CameraDrone_Spline_C) \
    x(BP_Xmas_CandyCane_Physic_C) \
    x(BP_PhysicsPineCone_C) \
    x(BP_SlimyFungus_C) \
    x(BP_CaterpillarTrack_Left_C) \
    x(BP_JettyBoots_ClearHighscores_C) \
    x(BP_Refinery_LandingZone_C) \
    x(BP_CrystalFormations_SlantedPillars_02Rot_C) \
    x(BP_CreeperVine_ThroughGround_02_C) \
    x(BP_ThornsComponent_C) \
    x(BP_Phys_InflatableSausage_C) \
    x(BP_SentinelGoo_Puddle_C) \
    x(BP_BarGlass_PropHunt_C) \
    x(BP_Plague_Spore_Tower_C) \
    x(BP_CrystalFormations_SlantedPillars_02_C) \
    x(BP_HackerJunk_Box_C) \
    x(BP_TutorialHeadline_C) \
    x(BP_Lunar2024_DragonStatue_InCave_C) \
    x(BP_HydraWeedCoreFragment_C) \
    x(BP_CheatConsole_C) \
    x(BP_ExplosiveEnemiesDamageMedium_C) \
    x(BP_CrystalFormation_SpikyBunch_02_C) \
    x(BP_RockFormation_Stone_13_C) \
    x(BP_Azure_HugeRoots_Single_06_C) \
    x(BP_Ebonut_C) \
    x(BP_Crossbow_PheromoneAttackerPositioning_C) \
    x(BP_SpecialTutorialCrystal_C) \
    x(BP_CozyTreeHollow_Double_A_C) \
    x(BP_HumongousFungus_1_C) \
    x(BP_PetComponent_C) \
    x(BP_Spacerig_Spaceball_C) \
    x(BP_SpaceRig_Exterior_C) \
    x(BP_WormPlant_Animated_Radioactive_C) \
    x(BP_BrokenDNA_2_C) \
    x(BP_Barley4_3_C) \
    x(BP_PlagueHeartShield_B_C) \
    x(BP_DropPod_Escape_Normal_C) \
    x(BP_DownedBombDamage_C) \
    x(BP_BarGlass_SlayerStout_C) \
    x(BP_TextField_Screen_SeeThrough_C) \
    x(BP_RewardDispenser_C) \
    x(BP_Electrical_Antenna_C) \
    x(BP_SpiderEgg_C) \
    x(BP_FriendlyParasite_C) \
    x(BP_Glacier_2_C) \
    x(BP_SwarmerTunnels_variant_3_C) \
    x(BP_MagicHoleBottomDebris_C) \
    x(BP_PipeGrindingConnector_C) \
    x(BP_Halloween_Candle_C) \
    x(BP_ProspectorDataDeposit_C) \
    x(BP_JettyBoots_Arcade_C) \
    x(BP_HoloLid_C) \
    x(BP_GreatEggHunt_EggCluster_C) \
    x(BP_Extractor_Shell_C) \
    x(BP_HumongousFungus_3_C) \
    x(BP_BoscoAbillityProjectile_C) \
    x(BP_HeartstoneSpriteCore_C) \
    x(BP_BRT_Bomb_C) \
    x(BP_SnowballItem_C) \
    x(BP_CrystalArch_2_C) \
    x(BP_ChimneyGeyser04_Carved_C) \
    x(BP_Barley3_1_C) \
    x(BP_Phys_Balloon_C) \
    x(BP_CozyTreeHollow_Base_C) \
    x(BP_GlowingBlueCrystal_2_C) \
    x(BP_MotivationalQuotes_C) \
    x(BP_SummerEvent_PalmTree_C) \
    x(BP_Refinery_WarningLight_C) \
    x(BP_BurrowAttackComponent_C) \
    x(BP_BugThingComponent_C) \
    x(BP_ExplosiveBarrel_C) \
    x(BP_Grenade_Axe_Stuck_C) \
    x(BP_OxygenComponent_C) \
    x(BP_Phys_WoodBarrel_C) \
    x(BP_PlagueHeartShield_C_C) \
    x(BP_BarGlass_Oktoberfest_C) \
    x(BP_Nisse_C) \
    x(BP_HandheldTablet_UseProgress_C) \
    x(BP_PlayerState_SpaceRig_C) \
    x(BP_MinersManualConsole_C) \
    x(BP_ExplodingPlant_Small_C) \
    x(BP_TradingConsole_C) \
    x(BP_Crossbow_Projectile_Stuck_C) \
    x(BP_AsteroidField_C) \
    x(BP_TumbleweedSpawner_C) \
    x(BP_PhysicsPineCone_Small_C) \
    x(BP_SubsystemLoader_C) \
    x(BP_Bosco_FoamGlob_C) \
    x(BP_New_HeavyRain_Crystal_C) \
    x(BP_Azure_ThinHangingRoots_SM_AzureWealdVines_03_C) \
    x(BP_HollomiteChunk_C) \
    x(BP_SentryItem_PlaceMarker_Heavy_C) \
    x(BP_Spacerig_Spaceball_Goal_C) \
    x(BP_ForgeConsole_C) \
    x(BP_Tentacle_ClawParts_C) \
    x(BP_CleanupPod_Beacon_WalkingPlagueheart_C) \
    x(BP_Barley2_3_C) \
    x(BP_DrinksBox_C) \
    x(BP_ChimneyGeyser03_Carved_C) \
    x(BP_BossFight_NeutralEvent_C) \
    x(BP_Guntower_Module_Homing_C) \
    x(BP_Armor_Scout_C) \
    x(BP_TriggerBase_C) \
    x(BP_RockpoxBomber_PlaguePuddle_C) \
    x(BP_WormpodCarcass_C) \
    x(BP_Collectible_Barley_B4_C) \
    x(BP_Gem_Bittergem_C) \
    x(BP_EletrocutedSentry_C) \
    x(BP_DownedState_C) \
    x(BP_ExterminationContract_C) \
    x(BP_PineconeSpawner_4_C) \
    x(BP_Tentacle_RangedAttack_C) \
    x(BP_SaltColumnGrowth_02_C) \
    x(BP_HackerJunk_Base_C) \
    x(BP_MisComp_FXspawner_C) \
    x(BP_HumongousFungus_2_C) \
    x(BP_CrystalFormations_SlantedPillars_02Small_C) \
    x(BP_LargeCoral_5_C) \
    x(BP_BarGlass_RedRockBlaster_C) \
    x(BP_PetAttackerPositioning_C) \
    x(BP_SpaceSausage_C) \
    x(BP_Phys_Barrel_Cutie_C) \
    x(BP_MineHead_C) \
    x(BP_LargeRootKnob_1_C) \
    x(BP_GreatEggHunt_ThrowableBunny_C) \
    x(BP_HackingPod_C) \
    x(BP_ToxicCatalistExplosion_C) \
    x(BP_CrystalFormations_SlantedPillar_Solo_1_C) \
    x(BP_LargeRootHole_1_C) \
    x(BP_LargeCoral_3_C) \
    x(BP_Phys_Newsstand_C) \
    x(BP_RedThornFlower_Alone_C) \
    x(BP_Phys_KickableObject_Base_C) \
    x(BP_FriendlyShredder_C) \
    x(BP_HandheldTablet_Off_C) \
    x(BP_ConffetiPipe_A_C) \
    x(BP_Collectible_Barley_B3_C) \
    x(BP_FragilePlatform_C) \
    x(BP_SelfiePoint_C) \
    x(BP_HugeLongRoot_3_C) \
    x(BP_MiniNuke_RadiationCloud_C) \
    x(BP_Barley4_4_C) \
    x(BP_ExplosiveReloadComponent_DualMP_C) \
    x(BP_ExpertDepositorLogic_C) \
    x(BP_SpotLightInteractive_C) \
    x(BP_HUD_C) \
    x(BP_SwarmerTunnels_variant_1_C) \
    x(BP_HugeThornBranch_1_NEW_C) \
    x(BP_Barley4_2_C) \
    x(BP_SandblastedRockIsland_4_C) \
    x(BP_InfectedState_C) \
    x(BP_SeaUrchin_C) \
    x(BP_UIScreenTest_C) \
    x(BP_Minehead_LandingZone_C) \
    x(BP_IceFormation_Base_C) \
    x(BP_ItemDispenserBase_C) \
    x(BP_ExplosiveBarrelsEvent_C) \
    x(BP_Gem_C) \
    x(BP_Coilgun_Trailsegment_Base_C) \
    x(BP_SupplyPod_Beacon_C) \
    x(BP_HugeCrystalStar_1_Double_C) \
    x(BP_SuckingPlant__C) \
    x(BP_Phys_Hammer_C) \
    x(BP_CleanupPod_C) \
    x(BP_ShowroomStage_C) \
    x(BP_PineconeSpawner_3_C) \
    x(BP_FacilityTurretDrone_Sniper_C) \
    x(BP_AzureWealdArch_2_C) \
    x(BP_PropHunt_EggHunt_Egg_C) \
    x(BP_Hologram_Base_C) \
    x(BP_Shotgun_A_Shell_C) \
    x(BP_MedbaySign_C) \
    x(BP_DystrumChunk_C) \
    x(BP_MagneticArrow_Component_C) \
    x(BP_SMG_ElectrifiedPlatforms_C) \
    x(BP_Shotgun_A_ShellTP_C) \
    x(BP_CrystalFormations_SlantedPillars_06_C) \
    x(BP_BarGlass_BackbreakerStout_C) \
    x(BP_DropPod_Base_C) \
    x(BP_LargeStabbyThorn_C) \
    x(BP_LargeHollowLog_1_C) \
    x(BP_HumongousFungus_4_C) \
    x(BP_LightPost01_C) \
    x(BP_DropPodScreenTextWidget_C) \

